version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - funlen
    - interfacebloat
    - gocognit
    - perfsprint
    - nilerr
    - canonicalheader
    - maintidx
    - ineffassign
    - ireturn
    - gomoddirectives
    - makezero
    - gochecknoglobals
    - intrange
    - grouper
    - nakedret
    - exhaustive
    - goconst
    - containedctx
    - nolintlint
    - funcorder
    - errorlint
    - nosprintfhostport
    - sqlclosecheck
    - mirror
    - protogetter
    - forbidigo
    - inamedparam
    - gochecknoinits
    - gocyclo
    - wastedassign
    - rowserrcheck
    - loggercheck
    - testableexamples
    - cyclop
    - dupl
    - iface
    - asasalint
    - godot
    - ginkgolinter
    - contextcheck
    - testifylint
    - gosec
    - bodyclose
    - unconvert
    - sloglint
    - decorder
    - govet
    - dupword
    - importas
    - fatcontext
    - tagalign
    - wrapcheck
    - embeddedstructfieldcheck
    - whitespace
    - gomodguard
    - bidichk
    - spancheck
    - misspell
    - staticcheck
    - tparallel
    - thelper
    - unused
    - gochecksumtype
    - usestdlibvars
    - noctx
    - copyloopvar
    - durationcheck
    - gocritic
    - promlinter
    - goprintffuncname
    - errcheck
    - nilnesserr
    - zerologlint
issues: {}
