version: "2"
run:
  timeout: 5m
  go: ""
  build-tags: []
  allow-parallel-runners: false
  allow-serial-runners: false
  tests: true
output:
  formats: {}
linters:
  enable:
    - misspell
    - spancheck
    - interfacebloat
    - govet
    - makezero
    - predeclared
    - durationcheck
    - revive
    - errorlint
    - nakedret
    - paralleltest
    - gochecksumtype
    - usetesting
    - nestif
    - godot
    - rowserrcheck
    - goheader
    - gocognit
    - reassign
    - canonicalheader
    - asasalint
    - varnamelen
    - exhaustruct
    - gocritic
    - forbidigo
    - gocyclo
    - testifylint
    - gomoddirectives
    - thelper
    - grouper
    - nosprintfhostport
    - tagliatelle
    - nilerr
    - unparam
    - errcheck
    - bidichk
    - staticcheck
    - usestdlibvars
    - unconvert
    - iface
    - noctx
    - fatcontext
    - goconst
    - gomodguard
    - unused
    - funlen
    - nilnil
    - nolintlint
    - gosec
    - gochecknoinits
    - errchkjson
    - testpackage
    - prealloc
    - gocheckcompilerdirectives
    - zerologlint
    - promlinter
    - containedctx
    - gochecknoglobals
    - bodyclose
    - maintidx
    - gosmopolitan
    - dupword
    - protogetter
    - asciicheck
    - ireturn
    - dogsled
    - nilnesserr
    - decorder
    - forcetypeassert
    - tparallel
    - err113
    - loggercheck
    - godox
    - wastedassign
    - sqlclosecheck
    - ginkgolinter
    - recvcheck
    - cyclop
    - dupl
    - wrapcheck
    - contextcheck
    - copyloopvar
    - errname
    - testableexamples
    - ineffassign
    - sloglint
    - mnd
    - inamedparam
    - exhaustive
    - mirror
    - musttag
    - importas
    - nonamedreturns
    - nlreturn
    - whitespace
    - intrange
    - perfsprint
    - goprintffuncname
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 5
      min-occurrences: 4
    gocyclo:
      min-complexity: 15
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        - Printer
        - Hasher
        - Detector
        - Token
    wrapcheck:
      ignore-sigs:
        - errors.Wrap
        - errors.Wrapf
        - errors.WrapFile
        - fmt.Errorf(
        - errors.New(
        - stderrors.New(
        - domain.NewValidationError(
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - cyclop
          - gocognit
          - gocyclo
          - maintidx
          - dupl
          - gosec
          - err113
          - exhaustruct
          - paralleltest
          - testpackage
          - varnamelen
          - gochecknoglobals
          - forcetypeassert
          - forbidigo
          - mnd
          - tagliatelle
          - revive
          - wrapcheck
          - nestif
          - recvcheck
      - path: bdd/
        linters:
          - funlen
          - cyclop
          - gocognit
          - gocyclo
          - maintidx
          - dupl
          - gosec
          - err113
          - exhaustruct
          - paralleltest
          - testpackage
          - varnamelen
          - gochecknoglobals
          - forcetypeassert
          - forbidigo
          - mnd
          - tagliatelle
          - revive
          - wrapcheck
          - forbidigo
          - godox
          - nestif
      - path: examples/
        linters:
          - exhaustruct
          - varnamelen
          - mnd
          - tagliatelle
          - revive
      - path: testutils/
        linters:
          - exhaustruct
          - varnamelen
          - mnd
          - tagliatelle
          - revive
          - gosec
      - path: migration/
        linters:
          - typecheck
      - path: cmd/
        linters:
          - exhaustruct
      - path: syntax/
        linters:
          - gocyclo
          - cyclop
formatters:
  enable:
    - golines
issues: {}
