package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/art-dupl/pkg/filter"
	"github.com/stretchr/testify/assert"
)

// TestSmartFilteringIntegration is an integration test for smart filtering feature.
func TestSmartFilteringIntegration(t *testing.T) {
	t.Run("filters sqlc and templ files when filter-generated is set", func(t *testing.T) {
		// Create temporary test directory
		tmpDir := t.TempDir()

		// Create directory structure
		// tmpDir/
		//   main.go (regular)
		//   db/
		//     models.go (sqlc)
		//     querier.go (sqlc)
		//   components/
		//     header_templ.go (templ)
		//   service/
		//     user.go (regular)
		//     auth.go (regular)

		files := map[string]string{
			"main.go": `package main

func main() {
    println("Hello, World!")
}
`,
			"db/models.go": `// Code generated by sqlc. DO NOT EDIT.
package db

type User struct {
    ID   int64
    Name string
}
`,
			"db/querier.go": `// Code generated by sqlc. DO NOT EDIT.
package db

type Querier interface {
    GetUser(ctx context.Context, id int64) (User, error)
}
`,
			"components/header_templ.go": `// Code generated by templ DO NOT EDIT

package components

import (
    "context"
    "io"
    "github.com/a-h/templ"
)

func Header(title string) templ.Component {
    return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
        w.Write([]byte("<header>" + title + "</header>"))
        return nil
    })
}
`,
			"service/user.go": `package service

type User struct {
    Name string
}

func NewUser(name string) *User {
    return &User{Name: name}
}
`,
			"service/auth.go": `package service

func Authenticate(username, password string) bool {
    return username == "admin" && password == "secret"
}
`,
		}

		// Create all files
		for path, content := range files {
			fullPath := filepath.Join(tmpDir, path)
			assert.NoError(t, os.MkdirAll(filepath.Dir(fullPath), 0o750))
			assert.NoError(t, os.WriteFile(fullPath, []byte(content), 0o600))
		}

		// Test that filter correctly identifies files
		filter := filter.NewFilter(true, []filter.FilterOption{
			filter.FilterAll,
		})

		// Regular files should NOT be filtered
		assert.False(t, filter.ShouldFilter(filepath.Join(tmpDir, "main.go")), "main.go should not be filtered")
		assert.False(t, filter.ShouldFilter(filepath.Join(tmpDir, "service/user.go")), "service/user.go should not be filtered")
		assert.False(t, filter.ShouldFilter(filepath.Join(tmpDir, "service/auth.go")), "service/auth.go should not be filtered")

		// sqlc files SHOULD be filtered
		assert.True(t, filter.ShouldFilter(filepath.Join(tmpDir, "db/models.go")), "db/models.go should be filtered (sqlc)")
		assert.True(t, filter.ShouldFilter(filepath.Join(tmpDir, "db/querier.go")), "db/querier.go should be filtered (sqlc)")

		// templ files SHOULD be filtered
		assert.True(t, filter.ShouldFilter(filepath.Join(tmpDir, "components/header_templ.go")), "components/header_templ.go should be filtered (templ)")
	})

	t.Run("include sqlc but filter templ", func(t *testing.T) {
		tmpDir := t.TempDir()

		// Create test files
		files := map[string]string{
			"db/models.go": `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`,
			"components/header_templ.go": `package components
import "github.com/a-h/templ"
func Header() templ.Component { return nil }
`,
		}

		for path, content := range files {
			fullPath := filepath.Join(tmpDir, path)
			assert.NoError(t, os.MkdirAll(filepath.Dir(fullPath), 0o750))
			assert.NoError(t, os.WriteFile(fullPath, []byte(content), 0o600))
		}

		// Create filter with sqlc included (not filtered)
		filter := filter.NewFilter(true, []filter.FilterOption{
			filter.FilterTempl,
		})

		// sqlc should NOT be filtered (not in options)
		assert.False(t, filter.ShouldFilter(filepath.Join(tmpDir, "db/models.go")), "db/models.go should not be filtered")

		// templ SHOULD be filtered
		assert.True(t, filter.ShouldFilter(filepath.Join(tmpDir, "components/header_templ.go")), "components/header_templ.go should be filtered (templ)")
	})

	t.Run("include pattern takes precedence", func(t *testing.T) {
		tmpDir := t.TempDir()

		// Create a vendor directory with sqlc file
		vendorFile := filepath.Join(tmpDir, "vendor", "models.go")
		vendorContent := `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`
		assert.NoError(t, os.MkdirAll(filepath.Dir(vendorFile), 0o750))
		assert.NoError(t, os.WriteFile(vendorFile, []byte(vendorContent), 0o600))

		// Create filter with include pattern for vendor
		filter := filter.NewFilter(true, []filter.FilterOption{filter.FilterAll})
		filter.WithIncludePatterns([]string{"vendor/*"})

		// Vendor file should NOT be filtered due to include pattern
		assert.False(t, filter.ShouldFilter(vendorFile), "vendor/models.go should not be filtered (include pattern)")
	})
}
