// Package filter provides smart filtering of auto-generated Go code.
package filter

import (
	"os"
	"path/filepath"
	"strings"
)

// isAutoGenerated checks if a file is auto-generated based on content and patterns.
func (f *Filter) isAutoGenerated(filePath string) bool {
	return f.getAutoGeneratedReason(filePath) != ReasonNotFiltered
}

// getAutoGeneratedReason determines if and why a file is auto-generated.
// OPTIMIZATION: Do filename-based check FIRST (no I/O), only read file if necessary.
func (f *Filter) getAutoGeneratedReason(filePath string) FilterReason {
	// OPTIMIZATION: Try filename-based detection first (no I/O)
	// Only read file content if filename check is inconclusive
	filenameBasedReason := f.getFilenameBasedReason(filePath)
	if filenameBasedReason != ReasonNotFiltered {
		return filenameBasedReason
	}

	// Filename check was inconclusive, read file for content-based detection
	// OPTIMIZATION: Only read if filename suggests it might be generated
	content, err := os.ReadFile(filePath) //nolint:gosec //G304 filePath is from controlled source (path crawling)
	if err != nil {
		// If we can't read the file, fall back to filename-based detection only
		return filenameBasedReason
	}

	contentStr := string(content)

	// Check sqlc patterns
	if f.options[FilterSQLC] && isSQLCGenerated(filePath, contentStr) {
		return ReasonSQLC
	}

	// Check templ patterns
	if f.options[FilterTempl] && isTemplGenerated(filePath, contentStr) {
		return ReasonTempl
	}

	// Check go-enum patterns
	if f.options[FilterGoEnum] && isGoEnumGenerated(filePath, contentStr) {
		return ReasonGoEnum
	}

	return ReasonNotFiltered
}

// getFilenameBasedReason determines the filter reason based on filename only.
func (f *Filter) getFilenameBasedReason(filePath string) FilterReason {
	filename := filepath.Base(filePath)

	// sqlc patterns
	if f.options[FilterSQLC] {
		for _, pattern := range sqlcFilePatterns {
			if strings.Contains(filename, pattern) {
				return ReasonSQLC
			}
		}

		// Also check for *.sql.go pattern (SQLC generates files like articles.sql.go, users.sql.go, etc.)
		if strings.HasSuffix(filename, ".sql.go") {
			return ReasonSQLC
		}
	}

	// templ patterns
	if f.options[FilterTempl] && strings.HasSuffix(filename, "_templ.go") {
		return ReasonTempl
	}

	// go-enum patterns
	if f.options[FilterGoEnum] && strings.HasSuffix(filename, "_enum.go") {
		return ReasonGoEnum
	}

	return ReasonNotFiltered
}

// isSQLCGenerated checks if a file is generated by sqlc.dev.
func isSQLCGenerated(filePath, content string) bool {
	if !matchesSQLCFilename(filePath) {
		return false
	}

	return hasSQLCContent(content)
}

// matchesSQLCFilename checks if filename matches sqlc.dev naming patterns.
func matchesSQLCFilename(filePath string) bool {
	filename := filepath.Base(filePath)

	for _, pattern := range sqlcFilePatterns {
		if strings.Contains(filename, pattern) {
			return true
		}
	}

	return strings.HasSuffix(filename, ".sql.go")
}

// hasSQLCContent checks if content contains sqlc.dev specific markers.
func hasSQLCContent(content string) bool {
	// Check for sqlc comment header
	if strings.Contains(content, "// Code generated by sqlc. DO NOT EDIT.") {
		return true
	}

	// Check for sqlc version comment
	if strings.Contains(content, "sqlc ") && strings.Contains(content, "versions:") {
		return true
	}

	return hasSQLCCodePatterns(content)
}

// hasSQLCCodePatterns checks for sqlc-specific code patterns in content.
func hasSQLCCodePatterns(content string) bool {
	sqlcCodePatterns := []string{
		"sqlc.Arg",
		"sqlc.NamedArg",
		"sqlc.Literal",
		"sqlc.SliceArg",
		"sqlc.Narg",
		".query(ctx", // Common sqlc method pattern
	}

	for _, pattern := range sqlcCodePatterns {
		if strings.Contains(content, pattern) {
			return true
		}
	}

	return false
}

// isTemplGenerated checks if a file is generated by templ.guide.
func isTemplGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	// Check for templ file pattern (*_templ.go)
	if !strings.HasSuffix(filename, "_templ.go") {
		return false
	}

	// Check for templ-specific code patterns
	if strings.Contains(content, "templ.Component") {
		return true
	}

	// Check for templ render function signature
	if strings.Contains(content, "Render(ctx context.Context, w io.Writer) error") {
		return true
	}

	return false
}

// isGoEnumGenerated checks if a file is generated by go-enum.
func isGoEnumGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	// Check for go-enum file pattern (*_enum.go)
	if !strings.HasSuffix(filename, "_enum.go") {
		return false
	}

	// Check for go-enum comment header
	if strings.Contains(content, "// Code generated by go-enum") {
		return true
	}

	return false
}

// matchPattern checks if a path matches a pattern (supports * and ** wildcards).
func matchPattern(path, pattern string) bool {
	// If pattern contains a path separator, match against path components
	// This allows patterns like "pkg1/*" to match "/tmp/test/pkg1/file.go"
	if strings.Contains(pattern, string(filepath.Separator)) || strings.Contains(pattern, "/") {
		// Convert pattern to a simple path matching string
		// Replace "*" with empty string to get path prefix to match
		// e.g., "pkg1/*" -> "pkg1/"
		prefix := strings.Split(pattern, "*")[0]

		// Ensure prefix ends with separator for proper matching
		if !strings.HasSuffix(prefix, string(filepath.Separator)) && !strings.HasSuffix(prefix, "/") {
			prefix += "/"
		}

		// Check if path contains prefix
		return strings.Contains(path, prefix)
	}

	// Pattern has no path separator, use filepath.Match for filename matching
	// This handles patterns like "*.go" correctly
	filename := filepath.Base(path)
	matched, err := filepath.Match(pattern, filename)
	if err != nil {
		// Invalid pattern, don't match
		return false
	}
	return matched
}
