// Package filter provides smart filtering of auto-generated Go code.
//
// This package detects and filters out common auto-generated code patterns
// such as sqlc.dev and templ.guide generated files to avoid analyzing
// code that developers don't write manually.
package filter

// Filter provides smart filtering of auto-generated Go code.
type Filter struct {
	options         map[FilterOption]bool
	enabled         bool
	includePatterns []string
	excludePatterns []string
	metrics         *Metrics
}

// NewFilter creates a new filter with specified options.
// OPTIMIZATION: Only create metrics if filtering is actually enabled.
func NewFilter(enabled bool, options []FilterOption) *Filter {
	f := &Filter{
		enabled:         enabled,
		options:         make(map[FilterOption]bool),
		includePatterns: make([]string, 0),
		excludePatterns: make([]string, 0),
		// OPTIMIZATION: Only create metrics if filter is enabled
		metrics: nil,
	}

	for _, opt := range options {
		if opt == FilterAll {
			f.options[FilterSQLC] = true
			f.options[FilterTempl] = true
			f.options[FilterGoEnum] = true
		} else {
			f.options[opt] = true
		}
	}

	// OPTIMIZATION: Create metrics only if filter is enabled
	if enabled {
		f.metrics = NewMetrics()
	}

	return f
}

// WithIncludePatterns adds custom include patterns to the filter.
func (f *Filter) WithIncludePatterns(patterns []string) *Filter {
	f.includePatterns = append(f.includePatterns, patterns...)

	return f
}

// WithExcludePatterns adds custom exclude patterns to the filter.
func (f *Filter) WithExcludePatterns(patterns []string) *Filter {
	f.excludePatterns = append(f.excludePatterns, patterns...)

	return f
}

// recordChecked records that a file was checked but not filtered.
//
//nolint:funcorder // unexported method used by exported methods
func (f *Filter) recordChecked(filePath string) {
	if f.metrics != nil {
		f.metrics.RecordChecked(filePath)
	}
}

// recordFiltered records that a file was filtered for a given reason.
//
//nolint:funcorder // unexported helper method
func (f *Filter) recordFiltered(filePath string, reason FilterReason) {
	if f.metrics != nil {
		f.metrics.RecordFiltered(filePath, reason)
	}
}

// matchesIncludePatterns checks if a file matches any include pattern.
// Returns true if the file should be included (not filtered).
//
//nolint:funcorder // unexported helper method
func (f *Filter) matchesIncludePatterns(filePath string) bool {
	for _, pattern := range f.includePatterns {
		if matchPattern(filePath, pattern) {
			return true
		}
	}

	return false
}

// matchesExcludePatterns checks if a file matches any exclude pattern.
// Returns true if the file should be filtered.
//
//nolint:funcorder // unexported helper method
func (f *Filter) matchesExcludePatterns(filePath string) bool {
	for _, pattern := range f.excludePatterns {
		if matchPattern(filePath, pattern) {
			return true
		}
	}

	return false
}

// ShouldFilter determines if a file should be filtered out (excluded from analysis).
// Returns true if the file should be filtered, false otherwise.
func (f *Filter) ShouldFilter(filePath string) bool {
	if !f.enabled {
		f.recordChecked(filePath)

		return false
	}

	// If include patterns are specified, use strict include-only logic
	if len(f.includePatterns) > 0 {
		return f.shouldFilterWithIncludes(filePath)
	}

	// No include patterns specified, use exclude logic
	return f.shouldFilterWithExcludes(filePath)
}

// shouldFilterWithIncludes handles filtering when include patterns are specified.
// Only files matching include patterns are analyzed, all others are filtered out.
//
//nolint:funcorder // unexported helper method
func (f *Filter) shouldFilterWithIncludes(filePath string) bool {
	if f.matchesIncludePatterns(filePath) {
		f.recordChecked(filePath)

		return false // Don't filter if it matches include pattern
	}

	f.recordFiltered(filePath, ReasonIncludePattern)

	return true // Filter out if it doesn't match ANY include pattern
}

// shouldFilterWithExcludes handles filtering when exclude patterns or auto-generated checks are used.
//
//nolint:funcorder // unexported helper method
func (f *Filter) shouldFilterWithExcludes(filePath string) bool {
	// Check exclude patterns
	if f.matchesExcludePatterns(filePath) {
		f.recordFiltered(filePath, ReasonExcludePattern)

		return true
	}

	// Check auto-generated code patterns
	if f.isAutoGenerated(filePath) {
		reason := f.getAutoGeneratedReason(filePath)
		f.recordFiltered(filePath, reason)

		return true
	}

	f.recordChecked(filePath)

	return false
}

// GetMetrics returns the filter metrics tracker. Returns nil if metrics are disabled.
func (f *Filter) GetMetrics() *Metrics {
	return f.metrics
}

// GetStats returns a snapshot of filter statistics.
func (f *Filter) GetStats() FilterStats {
	if f.metrics == nil {
		return FilterStats{} //nolint:exhaustruct
	}

	return f.metrics.GetStats()
}
