package filter

import (
	"os"
	"path/filepath"
	"strings"
)

// FilterOption represents a type of generated code to filter.
type FilterOption string

const (
	// FilterSQLC filters sqlc.dev generated files.
	FilterSQLC FilterOption = "sqlc"

	// FilterTempl filters templ.guide generated files.
	FilterTempl FilterOption = "templ"

	// FilterAll filters all auto-generated code.
	FilterAll FilterOption = "all"
)

// Filter provides smart filtering of auto-generated Go code.
type Filter struct {
	options         map[FilterOption]bool
	enabled         bool
	includePatterns []string
	excludePatterns []string
}

// NewFilter creates a new filter with specified options.
func NewFilter(enabled bool, options []FilterOption) *Filter {
	f := &Filter{
		enabled:         enabled,
		options:         make(map[FilterOption]bool),
		includePatterns: make([]string, 0),
		excludePatterns: make([]string, 0),
	}

	for _, opt := range options {
		if opt == FilterAll {
			f.options[FilterSQLC] = true
			f.options[FilterTempl] = true
		} else {
			f.options[opt] = true
		}
	}

	return f
}

// WithIncludePatterns adds custom include patterns to the filter.
func (f *Filter) WithIncludePatterns(patterns []string) *Filter {
	f.includePatterns = append(f.includePatterns, patterns...)
	return f
}

// WithExcludePatterns adds custom exclude patterns to the filter.
func (f *Filter) WithExcludePatterns(patterns []string) *Filter {
	f.excludePatterns = append(f.excludePatterns, patterns...)
	return f
}

// ShouldFilter determines if a file should be filtered out (excluded from analysis).
// Returns true if the file should be filtered, false otherwise.
func (f *Filter) ShouldFilter(filePath string) bool {
	if !f.enabled {
		return false
	}

	// If include patterns are specified, use strict include-only logic
	// Only files matching include patterns are analyzed, all others are filtered out
	if len(f.includePatterns) > 0 {
		for _, pattern := range f.includePatterns {
			if matchPattern(filePath, pattern) {
				return false // Don't filter if it matches include pattern
			}
		}
		return true // Filter out if it doesn't match ANY include pattern
	}

	// No include patterns specified, use exclude logic
	// Check exclude patterns
	for _, pattern := range f.excludePatterns {
		if matchPattern(filePath, pattern) {
			return true // Filter if it matches exclude pattern
		}
	}

	// Check auto-generated code patterns
	return f.isAutoGenerated(filePath)
}

// isAutoGenerated checks if a file is auto-generated based on content and patterns.
func (f *Filter) isAutoGenerated(filePath string) bool {
	// Read file content for content-based detection
	content, err := os.ReadFile(filePath) //nolint:gosec //G304 filePath is from controlled source (path crawling)
	if err != nil {
		// If we can't read the file, fall back to filename-based detection only
		return f.isGeneratedByFilename(filePath)
	}

	contentStr := string(content)

	// Check sqlc patterns
	if f.options[FilterSQLC] && isSQLCGenerated(filePath, contentStr) {
		return true
	}

	// Check templ patterns
	if f.options[FilterTempl] && isTemplGenerated(filePath, contentStr) {
		return true
	}

	return false
}

// isGeneratedByFilename performs filename-based detection only.
func (f *Filter) isGeneratedByFilename(filePath string) bool {
	filename := filepath.Base(filePath)

	// sqlc patterns
	if f.options[FilterSQLC] {
		sqlcPatterns := []string{
			"models.go",
			"querier.go",
			"query.sql.go",
			"batch.go",
		}
		for _, pattern := range sqlcPatterns {
			if strings.Contains(filename, pattern) {
				return true
			}
		}
	}

	// templ patterns
	if f.options[FilterTempl] && strings.HasSuffix(filename, "_templ.go") {
		return true
	}

	return false
}

// matchPattern checks if a path matches a pattern (supports * and ** wildcards).
func matchPattern(path, pattern string) bool {
	// If pattern contains a path separator, match against path components
	// This allows patterns like "pkg1/*" to match "/tmp/test/pkg1/file.go"
	if strings.Contains(pattern, string(filepath.Separator)) || strings.Contains(pattern, "/") {
		// Convert pattern to a simple path matching string
		// Replace "*" with empty string to get path prefix to match
		// e.g., "pkg1/*" -> "pkg1/"
		prefix := strings.Split(pattern, "*")[0]

		// Ensure prefix ends with separator for proper matching
		if !strings.HasSuffix(prefix, string(filepath.Separator)) && !strings.HasSuffix(prefix, "/") {
			prefix += "/"
		}

		// Check if path contains prefix
		return strings.Contains(path, prefix)
	}

	// Pattern has no path separator, use filepath.Match for filename matching
	// This handles patterns like "*.go" correctly
	filename := filepath.Base(path)
	matched, err := filepath.Match(pattern, filename)
	if err != nil {
		// Invalid pattern, don't match
		return false
	}
	return matched
}

// isSQLCGenerated checks if a file is generated by sqlc.dev.
func isSQLCGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	// Check for sqlc file patterns
	sqlcFilePatterns := []string{
		"models.go",
		"querier.go",
		"query.sql.go",
		"batch.go",
	}
	isSQLCFile := false
	for _, pattern := range sqlcFilePatterns {
		if strings.Contains(filename, pattern) {
			isSQLCFile = true
			break
		}
	}

	if !isSQLCFile {
		return false
	}

	// Check for sqlc comment header
	if strings.Contains(content, "// Code generated by sqlc. DO NOT EDIT.") {
		return true
	}

	// Check for sqlc version comment
	if strings.Contains(content, "sqlc ") && strings.Contains(content, "versions:") {
		return true
	}

	// Check for sqlc-specific code patterns
	sqlcCodePatterns := []string{
		"sqlc.Arg",
		"sqlc.NamedArg",
		"sqlc.Literal",
		"sqlc.SliceArg",
		"sqlc.Narg",
		".query(ctx", // Common sqlc method pattern
	}
	for _, pattern := range sqlcCodePatterns {
		if strings.Contains(content, pattern) {
			return true
		}
	}

	return false
}

// isTemplGenerated checks if a file is generated by templ.guide.
func isTemplGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	// Check for templ file pattern (*_templ.go)
	if !strings.HasSuffix(filename, "_templ.go") {
		return false
	}

	// Check for templ-specific code patterns
	if strings.Contains(content, "templ.Component") {
		return true
	}

	// Check for templ render function signature
	if strings.Contains(content, "Render(ctx context.Context, w io.Writer) error") {
		return true
	}

	return false
}
