package filter

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewFilter(t *testing.T) {
	t.Run("creates disabled filter", func(t *testing.T) {
		f := NewFilter(false, nil)
		assert.False(t, f.enabled)
		assert.Empty(t, f.options)
	})

	t.Run("creates enabled filter with options", func(t *testing.T) {
		f := NewFilter(true, []FilterOption{FilterSQLC, FilterTempl})
		assert.True(t, f.enabled)
		assert.True(t, f.options[FilterSQLC])
		assert.True(t, f.options[FilterTempl])
	})

	t.Run("creates enabled filter with FilterAll", func(t *testing.T) {
		f := NewFilter(true, []FilterOption{FilterAll})
		assert.True(t, f.enabled)
		assert.True(t, f.options[FilterSQLC])
		assert.True(t, f.options[FilterTempl])
	})
}

func TestWithIncludePatterns(t *testing.T) {
	f := NewFilter(true, []FilterOption{FilterAll})
	f.WithIncludePatterns([]string{"vendor/*", "generated/keep.go"})

	assert.Len(t, f.includePatterns, 2)
	assert.Contains(t, f.includePatterns, "vendor/*")
	assert.Contains(t, f.includePatterns, "generated/keep.go")
}

func TestWithExcludePatterns(t *testing.T) {
	f := NewFilter(true, []FilterOption{FilterAll})
	f.WithExcludePatterns([]string{"test/*", "*.pb.go"})

	assert.Len(t, f.excludePatterns, 2)
	assert.Contains(t, f.excludePatterns, "test/*")
	assert.Contains(t, f.excludePatterns, "*.pb.go")
}

func TestShouldFilter(t *testing.T) {
	t.Run("disabled filter never filters", func(t *testing.T) {
		f := NewFilter(false, []FilterOption{FilterAll})
		assert.False(t, f.ShouldFilter("any/file.go"))
	})

	t.Run("enabled filter with no patterns filters by auto-generated detection", func(t *testing.T) {
		tmpDir := t.TempDir()

		// Create sqlc file
		sqlcFile := filepath.Join(tmpDir, "models.go")
		sqlcContent := `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`
		assert.NoError(t, os.WriteFile(sqlcFile, []byte(sqlcContent), 0o600)) //nolint:gosec //G306 Test file permissions

		// Create templ file
		templFile := filepath.Join(tmpDir, "header_templ.go")
		templContent := `package components
import "github.com/a-h/templ"
func header() templ.Component { return nil }
`
		assert.NoError(t, os.WriteFile(templFile, []byte(templContent), 0o600)) //nolint:gosec //G306 Test file permissions

		// Create regular file
		regularFile := filepath.Join(tmpDir, "main.go")
		regularContent := `package main
func main() {}
`
		assert.NoError(t, os.WriteFile(regularFile, []byte(regularContent), 0o600)) //nolint:gosec //G306 Test file permissions

		f := NewFilter(true, []FilterOption{FilterAll})
		assert.True(t, f.ShouldFilter(sqlcFile), "should filter sqlc file")
		assert.True(t, f.ShouldFilter(templFile), "should filter templ file")
		assert.False(t, f.ShouldFilter(regularFile), "should not filter regular file")
	})
}

func TestMatchPattern(t *testing.T) {
	tests := []struct {
		name     string
		path     string
		pattern  string
		expected bool
	}{
		{
			name:     "exact match",
			path:     "file.go",
			pattern:  "file.go",
			expected: true,
		},
		{
			name:     "wildcard match",
			path:     "test.go",
			pattern:  "*.go",
			expected: true,
		},
		{
			name:     "wildcard no match",
			path:     "test.txt",
			pattern:  "*.go",
			expected: false,
		},
		{
			name:     "directory pattern",
			path:     "vendor/file.go",
			pattern:  "vendor/*",
			expected: true,
		},
		{
			name:     "complex pattern",
			path:     "generated/sqlc/models.go",
			pattern:  "generated/sqlc/*.go",
			expected: true,
		},
		{
			name:     "filename matches pattern in any directory",
			path:     "src/file.go",
			pattern:  "file.go",
			expected: true, // Pattern without path separator matches filename only
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := matchPattern(tt.path, tt.pattern)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestIsSQLCGenerated(t *testing.T) { //nolint:funlen
	tests := []struct {
		name     string
		filePath string
		content  string
		expected bool
	}{
		{
			name:     "sqlc models with comment",
			filePath: "db/models.go",
			content: `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package db

type User struct {
	ID int
}
`,
			expected: true,
		},
		{
			name:     "sqlc query with version comment",
			filePath: "db/query.sql.go",
			content: `package db

// versions:
//   sqlc v1.25.0

const getAuthors = ` + "`-- name: GetAuthors :many\nSELECT * FROM authors`" + `
`,
			expected: true,
		},
		{
			name:     "sqlc with sqlc.Arg",
			filePath: "db/querier.go",
			content: `package db

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, sqlc.Narg("id"))
	var i Author
	err := row.Scan(&i.ID)
	return i, err
}
`,
			expected: true,
		},
		{
			name:     "not sqlc - regular Go file",
			filePath: "models/user.go",
			content: `package models

type User struct {
	ID string
}
`,
			expected: false,
		},
		{
			name:     "sqlc batch.go",
			filePath: "db/batch.go",
			content: `// Code generated by sqlc. DO NOT EDIT.
package db

type Batch struct {
	// batch implementation
}
`,
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isSQLCGenerated(tt.filePath, tt.content)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestIsTemplGenerated(t *testing.T) { //nolint:funlen
	tests := []struct {
		name     string
		filePath string
		content  string
		expected bool
	}{
		{
			name:     "templ generated file",
			filePath: "components/header_templ.go",
			content: `// Code generated by templ DO NOT EDIT

package components

import (
	"context"
	"io"
	"github.com/a-h/templ"
)

func header(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		// implementation
		return nil
	})
}
`,
			expected: true,
		},
		{
			name:     "templ without Component interface",
			filePath: "components/footer_templ.go",
			content: `package components

func footer() string {
	return "footer"
}
`,
			expected: false,
		},
		{
			name:     "not templ - regular file",
			filePath: "components/helper.go",
			content: `package components

func Helper() string {
	return "helper"
}
`,
			expected: false,
		},
		{
			name:     "templ with Render signature",
			filePath: "views/index_templ.go",
			content: `package views

import (
	"context"
	"io"
)

type Index struct{}

func (i Index) Render(ctx context.Context, w io.Writer) error {
	// implementation
	return nil
}
`,
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isTemplGenerated(tt.filePath, tt.content)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestIsGeneratedByFilename(t *testing.T) { //nolint:funlen
	tests := []struct {
		name     string
		options  []FilterOption
		filePath string
		expected bool
	}{
		{
			name:     "sqlc models.go",
			options:  []FilterOption{FilterSQLC},
			filePath: "db/models.go",
			expected: true,
		},
		{
			name:     "sqlc querier.go",
			options:  []FilterOption{FilterSQLC},
			filePath: "db/querier.go",
			expected: true,
		},
		{
			name:     "sqlc query.sql.go",
			options:  []FilterOption{FilterSQLC},
			filePath: "db/query.sql.go",
			expected: true,
		},
		{
			name:     "sqlc batch.go",
			options:  []FilterOption{FilterSQLC},
			filePath: "db/batch.go",
			expected: true,
		},
		{
			name:     "templ file",
			options:  []FilterOption{FilterTempl},
			filePath: "components/header_templ.go",
			expected: true,
		},
		{
			name:     "not templ - regular .go file",
			options:  []FilterOption{FilterTempl},
			filePath: "components/helper.go",
			expected: false,
		},
		{
			name:     "all filters - sqlc file",
			options:  []FilterOption{FilterAll},
			filePath: "db/models.go",
			expected: true,
		},
		{
			name:     "all filters - templ file",
			options:  []FilterOption{FilterAll},
			filePath: "components/header_templ.go",
			expected: true,
		},
		{
			name:     "all filters - regular file",
			options:  []FilterOption{FilterAll},
			filePath: "main.go",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := NewFilter(true, tt.options)
			result := f.isGeneratedByFilename(tt.filePath)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestShouldFilterIntegration(t *testing.T) { //nolint:funlen
	// Create temporary directory structure
	tmpDir := t.TempDir()

	t.Run("filters sqlc file", func(t *testing.T) {
		sqlcFile := filepath.Join(tmpDir, "models.go")
		content := `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`
		assert.NoError(t, os.WriteFile(sqlcFile, []byte(content), 0o600)) //nolint:gosec //G306 Test file permissions

		f := NewFilter(true, []FilterOption{FilterSQLC})
		assert.True(t, f.ShouldFilter(sqlcFile))
	})

	t.Run("filters templ file", func(t *testing.T) {
		templFile := filepath.Join(tmpDir, "header_templ.go")
		content := `package components
import "github.com/a-h/templ"
func header() templ.Component { return nil }
`
		assert.NoError(t, os.WriteFile(templFile, []byte(content), 0o644))

		f := NewFilter(true, []FilterOption{FilterTempl})
		assert.True(t, f.ShouldFilter(templFile))
	})

	t.Run("does not filter regular file", func(t *testing.T) {
		regularFile := filepath.Join(tmpDir, "main.go")
		content := `package main
func main() {}
`
		assert.NoError(t, os.WriteFile(regularFile, []byte(content), 0o644))

		f := NewFilter(true, []FilterOption{FilterAll})
		assert.False(t, f.ShouldFilter(regularFile))
	})

	t.Run("include pattern takes precedence", func(t *testing.T) {
		sqlcFile := filepath.Join(tmpDir, "vendor", "models.go")
		content := `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`
		assert.NoError(t, os.MkdirAll(filepath.Dir(sqlcFile), 0o755))
		assert.NoError(t, os.WriteFile(sqlcFile, []byte(content), 0o644))

		f := NewFilter(true, []FilterOption{FilterAll})
		f.WithIncludePatterns([]string{"vendor/*"})
		assert.False(t, f.ShouldFilter(sqlcFile)) // Should not filter due to include pattern
	})

	t.Run("exclude pattern filters", func(t *testing.T) {
		testFile := filepath.Join(tmpDir, "test.go")
		content := `package test
func TestSomething() {}
`
		assert.NoError(t, os.WriteFile(testFile, []byte(content), 0o644))

		f := NewFilter(true, []FilterOption{})
		f.WithExcludePatterns([]string{"test*.go"})
		assert.True(t, f.ShouldFilter(testFile))
	})
}
