package filter

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/gogenfilter"
)

func TestNewFilterWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(true, []FilterOption{FilterSQLC, FilterTempl})
	if f == nil {
		t.Fatal("NewFilter returned nil")
	}

	if !f.ShouldFilter("db/models.go") {
		t.Error("Expected SQLC file to be filtered")
	}
}

func TestFilterAllWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(true, []FilterOption{FilterAll})

	if !f.ShouldFilter("db/models.go") {
		t.Error("Expected SQLC file to be filtered with FilterAll")
	}

	if !f.ShouldFilter("page_templ.go") {
		t.Error("Expected templ file to be filtered with FilterAll")
	}
}

func TestDisabledFilterWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(false, []FilterOption{FilterAll})
	if f.ShouldFilter("db/models.go") {
		t.Error("Disabled filter should not filter")
	}
}

func TestIncludePatternsWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(true, nil).WithIncludePatterns([]string{"pkg/*"})

	if !f.ShouldFilter("other/file.go") {
		t.Error("Non-matching include pattern should filter")
	}

	if f.ShouldFilter("pkg/main.go") {
		t.Error("Matching include pattern should not filter")
	}
}

func TestExcludePatternsWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(true, nil).WithExcludePatterns([]string{"*.pb.go"})

	if !f.ShouldFilter("test.pb.go") {
		t.Error("Matching exclude pattern should filter")
	}
}

func TestFilterStatsWrapper(t *testing.T) {
	t.Parallel()

	f := NewFilter(true, []FilterOption{FilterAll})
	_ = f.ShouldFilter("db/models.go")
	_ = f.ShouldFilter("main.go")

	stats := f.GetStats()
	if stats.TotalFilesChecked != 2 {
		t.Errorf("Expected 2 checked, got %d", stats.TotalFilesChecked)
	}

	if stats.TotalFiltered() < 1 {
		t.Errorf("Expected at least 1 filtered, got %d", stats.TotalFiltered())
	}
}

func TestMatchPatternWrapper(t *testing.T) {
	t.Parallel()

	tests := []struct {
		path, pattern string
		want          bool
	}{
		{"file.go", "*.go", true},
		{"test.txt", "*.go", false},
		{"vendor/file.go", "vendor/*", true},
	}

	for _, tt := range tests {
		got := gogenfilter.MatchPattern(tt.path, tt.pattern)
		if got != tt.want {
			t.Errorf("MatchPattern(%q, %q) = %v, want %v", tt.path, tt.pattern, got, tt.want)
		}
	}
}

func TestDetectionFunctionsWrapper(t *testing.T) {
	t.Parallel()

	if !gogenfilter.IsSQLCGenerated(
		"db/models.go",
		"// Code generated by sqlc. DO NOT EDIT.\npackage db",
	) {
		t.Error("IsSQLCGenerated should detect sqlc file")
	}

	if !gogenfilter.IsTemplGenerated(
		"page_templ.go",
		"package p\nimport \"github.com/a-h/templ\"\nfunc Page() templ.Component { return nil }",
	) {
		t.Error("IsTemplGenerated should detect templ file")
	}

	if !gogenfilter.IsGoEnumGenerated(
		"status_enum.go",
		"// Code generated by go-enum DO NOT EDIT.\npackage p",
	) {
		t.Error("IsGoEnumGenerated should detect go-enum file")
	}
}

func TestMetricsWrapper(t *testing.T) {
	t.Parallel()

	m := NewMetrics()
	m.RecordFiltered("test.go", ReasonSQLC)

	stats := m.GetStats()
	if stats.TotalFilesChecked != 1 {
		t.Errorf("Expected 1 checked, got %d", stats.TotalFilesChecked)
	}
}

func TestSQLCConfigWrapper(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "sqlc.yaml")

	content := `version: "2"
sql:
  - schema: "schema.sql"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "internal/db"
`
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	configs, err := FindSQLCConfigs([]string{tmpDir})
	if err != nil {
		t.Fatalf("FindSQLCConfigs error: %v", err)
	}

	if len(configs) != 1 {
		t.Errorf("Expected 1 config, got %d", len(configs))
	}

	dirs, err := GetSQLOutputDirs([]string{tmpDir})
	if err != nil {
		t.Fatalf("GetSQLOutputDirs error: %v", err)
	}

	if len(dirs) != 1 {
		t.Errorf("Expected 1 output dir, got %d", len(dirs))
	}
}
