package filtertest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
	"github.com/LarsArtmann/gogenfilter"
)

// TestSmartFilteringIntegration is an integration test for smart filtering feature.
func TestSmartFilteringIntegration(t *testing.T) {
	t.Run("filters sqlc and templ files when filter-generated is set", func(t *testing.T) {
		// Create temporary test directory
		setup := testutil.NewTestFileSetup(t)

		// Create directory structure
		// tmpDir/
		//   main.go (regular)
		//   db/
		//     models.go (sqlc)
		//     querier.go (sqlc)
		//   components/
		//     header_templ.go (templ)
		//   service/
		//     user.go (regular)
		//     auth.go (regular)

		files := map[string]string{
			"main.go": `package main

func main() {
    println("Hello, World!")
}
`,
			"db/models.go": `// Code generated by sqlc. DO NOT EDIT.
package db

type User struct {
    ID   int64
    Name string
}
`,
			"db/querier.go": `// Code generated by sqlc. DO NOT EDIT.
package db

type Querier interface {
    GetUser(ctx context.Context, id int64) (User, error)
}
`,
			"components/header_templ.go": `// Code generated by templ DO NOT EDIT

package components

import (
    "context"
    "io"
    "github.com/a-h/templ"
)

func Header(title string) templ.Component {
    return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
        w.Write([]byte("<header>" + title + "</header>"))
        return nil
    })
}`,
			"service/user.go": `package service

type User struct {
    Name string
}

func NewUser(name string) *User {
    return &User{Name: name}
}`,
			"service/auth.go": `package service

func Authenticate(username, password string) bool {
    return username == "admin" && password == "secret"
}`,
		}

		// Create all files using testutil
		err := setup.CreateTestFiles(files)
		if err != nil {
			t.Fatalf("CreateTestFiles failed: %v", err)
		}

		// Test that filter correctly identifies files
		filterConfig, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
		if err != nil {
			t.Fatalf("WithFilterOptions() error: %v", err)
		}

		fltr, err := gogenfilter.NewFilter(
			filterConfig,
			gogenfilter.WithFS(os.DirFS("/")),
		)
		if err != nil {
			t.Fatalf("NewFilter() error: %v", err)
		}

		// Regular files should NOT be filtered
		AssertFileShouldNotBeFiltered(t, fltr, setup.GetFilePath("main.go"))
		AssertFileShouldNotBeFiltered(t, fltr, setup.GetFilePath("service/user.go"))
		AssertFileShouldNotBeFiltered(t, fltr, setup.GetFilePath("service/auth.go"))

		// sqlc files SHOULD be filtered
		AssertFilesShouldBeFiltered(t, fltr, []string{
			setup.GetFilePath("db/models.go"),
			setup.GetFilePath("db/querier.go"),
		})

		// templ files SHOULD be filtered
		AssertFileShouldBeFiltered(t, fltr, setup.GetFilePath("components/header_templ.go"))
	})

	t.Run("include sqlc but filter templ", func(t *testing.T) {
		setup := testutil.NewTestFileSetup(t)

		// Create test files
		files := map[string]string{
			"db/models.go": `// Code generated by sqlc. DO NOT EDIT.
package db
type User struct {}
`,
			"components/header_templ.go": `package components
import "github.com/a-h/templ"
func Header() templ.Component { return nil }
`,
		}

		err := setup.CreateTestFiles(files)
		if err != nil {
			t.Fatalf("CreateTestFiles failed: %v", err)
		}

		// Create filter with sqlc included (not filtered)
		filterConfig, err := gogenfilter.WithFilterOptions(gogenfilter.FilterTempl)
		if err != nil {
			t.Fatalf("WithFilterOptions() error: %v", err)
		}

		fltr, err := gogenfilter.NewFilter(
			filterConfig,
			gogenfilter.WithFS(os.DirFS("/")),
		)
		if err != nil {
			t.Fatalf("NewFilter() error: %v", err)
		}

		// sqlc should NOT be filtered (not in options)
		if filtered, err := fltr.Filter(
			toFSPath(setup.GetFilePath("db/models.go")),
		); err == nil &&
			filtered {
			t.Errorf("db/models.go should not be filtered")
		}

		// templ SHOULD be filtered
		if filtered, err := fltr.Filter(
			toFSPath(setup.GetFilePath("components/header_templ.go")),
		); err == nil &&
			!filtered {
			t.Errorf("components/header_templ.go should be filtered (templ)")
		}
	})

	t.Run("include pattern takes precedence", func(t *testing.T) {
		setup := testutil.NewTestFileSetup(t)

		// Create a vendor directory with non-generated code
		// Use a filename that doesn't match sqlc filename patterns (models.go is detected as sqlc by filename)
		vendorFile := setup.GetFilePath(filepath.Join("vendor", "helpers.go"))
		vendorContent := `package db

func Helper() {}
`

		files := map[string]string{
			filepath.Join("vendor", "helpers.go"): vendorContent,
		}

		err := setup.CreateTestFiles(files)
		if err != nil {
			t.Fatalf("CreateTestFiles failed: %v", err)
		}

		filterConfig, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
		if err != nil {
			t.Fatalf("WithFilterOptions() error: %v", err)
		}

		fltr, err := gogenfilter.NewFilter(
			filterConfig,
			gogenfilter.WithIncludePatterns("**/vendor/*"),
			gogenfilter.WithFS(os.DirFS("/")),
		)
		if err != nil {
			t.Fatalf("NewFilter() error: %v", err)
		}

		// Vendor file should NOT be filtered - non-generated code that matches include pattern
		if filtered, err := fltr.Filter(toFSPath(vendorFile)); err == nil && filtered {
			t.Errorf("vendor/helpers.go should not be filtered (include pattern, non-generated)")
		}
	})

	t.Run("subdirectory analysis with sqlc.yaml in parent", func(t *testing.T) {
		setup := testutil.NewTestFileSetup(t)

		// Create project structure
		// tmpDir/
		//   sqlc.yaml (config)
		//   main.go (regular)
		//   db/
		//     models.go (sqlc)
		//     user.go (regular)
		//   service/
		//     auth.go (regular)
		files := map[string]string{
			"sqlc.yaml": `version: "2"
sql:
  - engine: "postgresql"
    schema: "./db/schema.sql"
    queries: "./db/query.sql"
    gen:
      go:
        package: "db"
        out: "./db"
`,
			"main.go": `package main

func main() {
    println("Hello, World!")
}`,
			"db/models.go": `// Code generated by sqlc. DO NOT EDIT.
package db

type User struct {
    ID   int64
    Name string
}`,
			"db/user.go": `package db

type User struct {
    Name string
}`,
			"service/auth.go": `package service

func Authenticate(username, password string) bool {
    return username == "admin" && password == "secret"
}`,
		}

		err := setup.CreateTestFiles(files)
		if err != nil {
			t.Fatalf("CreateTestFiles failed: %v", err)
		}

		// Test FindSQLCConfigs from subdirectory path
		// Simulate running: art-dupl ./db
		configs, findErr := gogenfilter.FindSQLCConfigs([]string{setup.GetFilePath("db")})
		if findErr != nil {
			t.Fatalf("FindSQLCConfigs failed: %v", findErr)
		}

		// Should find sqlc.yaml in parent directory
		if len(configs) == 0 {
			t.Errorf("should find sqlc.yaml in parent directory")
		}

		// Verify the config path
		foundConfigPath := ""
		configRoot := ""

		for configPath, root := range configs {
			foundConfigPath = configPath
			configRoot = root
		}

		expectedConfigPath := setup.GetFilePath("sqlc.yaml")
		expectedRoot := setup.TmpDir

		if foundConfigPath != expectedConfigPath {
			t.Errorf("config path = %v, want %v", foundConfigPath, expectedConfigPath)
		}

		if configRoot != expectedRoot {
			t.Errorf("config root = %v, want %v", configRoot, expectedRoot)
		}

		// Test filtering from subdirectory perspective
		filterConfig, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC)
		if err != nil {
			t.Fatalf("WithFilterOptions() error: %v", err)
		}

		fltr, err := gogenfilter.NewFilter(
			filterConfig,
			gogenfilter.WithFS(os.DirFS("/")),
		)
		if err != nil {
			t.Fatalf("NewFilter() error: %v", err)
		}

		// db/models.go should be filtered (sqlc)
		if filtered, err := fltr.Filter(
			toFSPath(setup.GetFilePath("db/models.go")),
		); err == nil &&
			!filtered {
			t.Errorf("db/models.go should be filtered")
		}

		// db/user.go should NOT be filtered (regular)
		AssertFileShouldNotBeFiltered(t, fltr, setup.GetFilePath("db/user.go"))

		// main.go should NOT be filtered (not in subdirectory being analyzed)
		AssertFileShouldNotBeFiltered(t, fltr, setup.GetFilePath("main.go"))
	})
}
