package filtertest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/art-dupl/pkg/filter"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestUserScenario_RealSQLCProject tests the exact scenario from the user's issue:
// - sqlc.yaml in project root
// - SQLC generates files like articles.sql.go, users.sql.go
// - Running art-dupl should filter these SQLC files automatically.
func TestUserScenario_RealSQLCProject(t *testing.T) {
	// Create temporary directory structure
	tmpDir := t.TempDir()

	// Create sqlc.yaml in project root (matching user's structure)
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/articles.sql"
    gen:
      go:
        package: "queries"
        out: "internal/storage/queries"
  - engine: "postgresql" 
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "internal/storage/queries"
`
	configPath := filepath.Join(tmpDir, "sqlc.yaml")
	err := os.WriteFile(configPath, []byte(sqlcConfig), 0o644)
	require.NoError(t, err)

	// Create directory structure
	queriesDir := filepath.Join(tmpDir, "internal/storage/queries")
	require.NoError(t, os.MkdirAll(queriesDir, 0o755))

	repoDir := filepath.Join(tmpDir, "internal/storage/repository")
	require.NoError(t, os.MkdirAll(repoDir, 0o755))

	// Create SQLC generated files (these should be filtered)
	articlesSQLC := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
    "context"
    "database/sql"
)

type Article struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
    CreatedAt   sql.NullTime
    UpdatedAt   sql.NullTime
}

type Category struct {
    ID          int64
    Name        string
    Description string
}

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
    return Article{}, nil
}

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
    return nil, nil
}
`
	require.NoError(t, os.WriteFile(filepath.Join(queriesDir, "articles.sql.go"), []byte(articlesSQLC), 0o644))

	usersSQLC := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
    "context"
    "database/sql"
)

type User struct {
    ID        int64
    Email     string
    Password  string
    CreatedAt sql.NullTime
    UpdatedAt sql.NullTime
}

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
    return User{}, nil
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
    return User{}, nil
}
`
	require.NoError(t, os.WriteFile(filepath.Join(queriesDir, "users.sql.go"), []byte(usersSQLC), 0o644))

	// Create regular Go files with duplicate code (these should be detected)
	articleRepo := `package repository

type ArticleModel struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
}

type CategoryModel struct {
    ID          int64
    Name        string
    Description string
}

func (r *Repository) SaveArticle(article ArticleModel) error {
    return nil
}
`
	require.NoError(t, os.WriteFile(filepath.Join(repoDir, "article_repository.go"), []byte(articleRepo), 0o644))

	mockRepo := `package repository

type ArticleModel struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
}

type CategoryModel struct {
    ID          int64
    Name        string
    Description string
}

func (m *MockRepository) SaveArticle(article ArticleModel) error {
    return nil
}
`
	require.NoError(t, os.WriteFile(filepath.Join(repoDir, "mock_repository.go"), []byte(mockRepo), 0o644))

	// Test FindSQLCConfigs finds the config
	configs, err := filter.FindSQLCConfigs([]string{tmpDir})
	require.NoError(t, err)
	assert.NotEmpty(t, configs, "Should find sqlc.yaml in project root")
	assert.Contains(t, configs, configPath, "Should find the config file we created")

	// Test GetSQLOutputDirs extracts correct output directories
	outputDirs, err := filter.GetSQLOutputDirs([]string{tmpDir})
	require.NoError(t, err)
	assert.NotEmpty(t, outputDirs, "Should extract output directories from sqlc.yaml")

	expectedOutputDir := filepath.Join(tmpDir, "internal/storage/queries")
	assert.Contains(t, outputDirs, expectedOutputDir, "Should have the queries output directory")

	// Test that filter correctly identifies SQLC files
	fltr := filter.NewFilter(true, []filter.FilterOption{filter.FilterSQLC})

	// SQLC files should be filtered
	assert.True(t, fltr.ShouldFilter(filepath.Join(queriesDir, "articles.sql.go")),
		"articles.sql.go should be filtered (SQLC generated)")
	assert.True(t, fltr.ShouldFilter(filepath.Join(queriesDir, "users.sql.go")),
		"users.sql.go should be filtered (SQLC generated)")

	// Regular files should NOT be filtered
	assert.False(t, fltr.ShouldFilter(filepath.Join(repoDir, "article_repository.go")),
		"article_repository.go should NOT be filtered (regular Go file)")
	assert.False(t, fltr.ShouldFilter(filepath.Join(repoDir, "mock_repository.go")),
		"mock_repository.go should NOT be filtered (regular Go file)")
}

// TestSQLCOutputDirectoryFiltering tests that files in SQLC output directories are filtered.
func TestSQLCOutputDirectoryFiltering(t *testing.T) {
	tmpDir := t.TempDir()

	// Create sqlc.yaml with nested output directory (matching user's structure)
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "db/sqlc"
`
	configPath := filepath.Join(tmpDir, "sqlc.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(sqlcConfig), 0o644))

	// Create nested directory structure
	queriesDir := filepath.Join(tmpDir, "db/sqlc")
	require.NoError(t, os.MkdirAll(queriesDir, 0o755))

	// Create SQLC file in nested directory
	sqlcFile := `// Code generated by sqlc. DO NOT EDIT.
package queries

type User struct {
    ID   int64
    Name string
}
`
	sqlcFilePath := filepath.Join(queriesDir, "users.sql.go")
	require.NoError(t, os.WriteFile(sqlcFilePath, []byte(sqlcFile), 0o644))

	// Test GetSQLOutputDirs finds the nested directory
	outputDirs, err := filter.GetSQLOutputDirs([]string{tmpDir})
	require.NoError(t, err)

	expectedOutputDir := filepath.Join(tmpDir, "db/sqlc")
	found := false
	for _, dir := range outputDirs {
		if dir == expectedOutputDir {
			found = true
			break
		}
	}
	assert.True(t, found, "Should find nested SQLC output directory: %s", expectedOutputDir)

	// Test filter recognizes SQLC files by both name and content
	fltr := filter.NewFilter(true, []filter.FilterOption{filter.FilterSQLC})
	assert.True(t, fltr.ShouldFilter(sqlcFilePath),
		"users.sql.go in SQLC output directory should be filtered")
}

// TestParentDirectorySQLCDetection tests finding sqlc.yaml in parent directories.
func TestParentDirectorySQLCDetection(t *testing.T) {
	tmpDir := t.TempDir()

	// Create sqlc.yaml in "project root"
	projectRoot := tmpDir
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "internal/db"
`
	configPath := filepath.Join(projectRoot, "sqlc.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(sqlcConfig), 0o644))

	// Create subdirectory structure (simulating running art-dupl on a subdirectory)
	subDir := filepath.Join(projectRoot, "internal/db")
	require.NoError(t, os.MkdirAll(subDir, 0o755))

	// Create SQLC file in subdirectory
	sqlcFile := `// Code generated by sqlc. DO NOT EDIT.
package queries

type User struct {
    ID   int64
    Name string
}
`
	sqlcFilePath := filepath.Join(subDir, "users.sql.go")
	require.NoError(t, os.WriteFile(sqlcFilePath, []byte(sqlcFile), 0o644))

	// Test that FindSQLCConfigs finds sqlc.yaml even when analyzing subdirectory
	configs, err := filter.FindSQLCConfigs([]string{subDir})
	require.NoError(t, err)
	assert.NotEmpty(t, configs, "Should find sqlc.yaml in parent directory")
	assert.Contains(t, configs, configPath, "Should find config in project root")

	// Test that output directory is correct (relative to project root)
	outputDirs, err := filter.GetSQLOutputDirs([]string{subDir})
	require.NoError(t, err)

	expectedOutputDir := filepath.Join(projectRoot, "internal/db")
	assert.Contains(t, outputDirs, expectedOutputDir,
		"Should resolve output directory relative to project root")
}
