package filtertest

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/LarsArtmann/art-dupl/pkg/filter"
)

// TestUserScenario_RealSQLCProject tests the exact scenario from the user's issue:
// - sqlc.yaml in project root
// - SQLC generates files like articles.sql.go, users.sql.go
// - Running art-dupl should filter these SQLC files automatically.
func TestUserScenario_RealSQLCProject(t *testing.T) {
	// Create temporary directory structure
	tmpDir := t.TempDir()

	// Create sqlc.yaml in project root (matching user's structure)
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/articles.sql"
    gen:
      go:
        package: "queries"
        out: "internal/storage/queries"
  - engine: "postgresql" 
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "internal/storage/queries"
`
	configPath := filepath.Join(tmpDir, "sqlc.yaml")

	err := os.WriteFile(configPath, []byte(sqlcConfig), 0o644)
	if err != nil {
		t.Fatalf("failed to write sqlc.yaml: %v", err)
	}

	// Create directory structure
	queriesDir := filepath.Join(tmpDir, "internal/storage/queries")
	if err := os.MkdirAll(queriesDir, 0o755); err != nil {
		t.Fatalf("failed to create queries dir: %v", err)
	}

	repoDir := filepath.Join(tmpDir, "internal/storage/repository")
	if err := os.MkdirAll(repoDir, 0o755); err != nil {
		t.Fatalf("failed to create repo dir: %v", err)
	}

	// Create SQLC generated files (these should be filtered)
	articlesSQLC := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
    "context"
    "database/sql"
)

type Article struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
    CreatedAt   sql.NullTime
    UpdatedAt   sql.NullTime
}

type Category struct {
    ID          int64
    Name        string
    Description string
}

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
    return Article{}, nil
}

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
    return nil, nil
}
`
	if err := os.WriteFile(
		filepath.Join(queriesDir, "articles.sql.go"),
		[]byte(articlesSQLC),
		0o644,
	); err != nil {
		t.Fatalf("failed to write articles.sql.go: %v", err)
	}

	usersSQLC := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
    "context"
    "database/sql"
)

type User struct {
    ID        int64
    Email     string
    Password  string
    CreatedAt sql.NullTime
    UpdatedAt sql.NullTime
}

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
    return User{}, nil
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
    return User{}, nil
}
`
	if err := os.WriteFile(
		filepath.Join(queriesDir, "users.sql.go"),
		[]byte(usersSQLC),
		0o644,
	); err != nil {
		t.Fatalf("failed to write users.sql.go: %v", err)
	}

	// Create regular Go files with duplicate code (these should be detected)
	articleRepo := `package repository

type ArticleModel struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
}

type CategoryModel struct {
    ID          int64
    Name        string
    Description string
}

func (r *Repository) SaveArticle(article ArticleModel) error {
    return nil
}
`
	if err := os.WriteFile(
		filepath.Join(repoDir, "article_repository.go"),
		[]byte(articleRepo),
		0o644,
	); err != nil {
		t.Fatalf("failed to write article_repository.go: %v", err)
	}

	mockRepo := `package repository

type ArticleModel struct {
    ID          int64
    Title       string
    Content     string
    CategoryID  int64
}

type CategoryModel struct {
    ID          int64
    Name        string
    Description string
}

func (m *MockRepository) SaveArticle(article ArticleModel) error {
    return nil
}
`
	if err := os.WriteFile(
		filepath.Join(repoDir, "mock_repository.go"),
		[]byte(mockRepo),
		0o644,
	); err != nil {
		t.Fatalf("failed to write mock_repository.go: %v", err)
	}

	// Test FindSQLCConfigs finds the config
	configs, err := filter.FindSQLCConfigs([]string{tmpDir})
	if err != nil {
		t.Fatalf("FindSQLCConfigs failed: %v", err)
	}

	if len(configs) == 0 {
		t.Error("Should find sqlc.yaml in project root")
	}

	// Test GetSQLOutputDirs extracts correct output directories
	outputDirs, err := filter.GetSQLOutputDirs([]string{tmpDir})
	if err != nil {
		t.Fatalf("GetSQLOutputDirs failed: %v", err)
	}

	if len(outputDirs) == 0 {
		t.Error("Should extract output directories from sqlc.yaml")
	}

	expectedOutputDir := filepath.Join(tmpDir, "internal/storage/queries")
	found := slices.Contains(outputDirs, expectedOutputDir)

	if !found {
		t.Errorf("Should have the queries output directory: %s", expectedOutputDir)
	}

	// Test that filter correctly identifies SQLC files
	fltr := filter.NewFilter(true, []filter.FilterOption{filter.FilterSQLC})

	// SQLC files should be filtered
	if !fltr.ShouldFilter(filepath.Join(queriesDir, "articles.sql.go")) {
		t.Error("articles.sql.go should be filtered (SQLC generated)")
	}

	if !fltr.ShouldFilter(filepath.Join(queriesDir, "users.sql.go")) {
		t.Error("users.sql.go should be filtered (SQLC generated)")
	}

	// Regular files should NOT be filtered
	if fltr.ShouldFilter(filepath.Join(repoDir, "article_repository.go")) {
		t.Error("article_repository.go should NOT be filtered (regular Go file)")
	}

	if fltr.ShouldFilter(filepath.Join(repoDir, "mock_repository.go")) {
		t.Error("mock_repository.go should NOT be filtered (regular Go file)")
	}
}

// TestSQLCOutputDirectoryFiltering tests that files in SQLC output directories are filtered.
func TestSQLCOutputDirectoryFiltering(t *testing.T) {
	tmpDir := t.TempDir()

	// Create sqlc.yaml with nested output directory (matching user's structure)
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "db/sqlc"
`

	configPath := filepath.Join(tmpDir, "sqlc.yaml")
	if err := os.WriteFile(configPath, []byte(sqlcConfig), 0o644); err != nil {
		t.Fatalf("failed to write sqlc.yaml: %v", err)
	}

	// Create nested directory structure
	queriesDir := filepath.Join(tmpDir, "db/sqlc")
	if err := os.MkdirAll(queriesDir, 0o755); err != nil {
		t.Fatalf("failed to create queries dir: %v", err)
	}

	// Create SQLC file in nested directory
	sqlcFile := `// Code generated by sqlc. DO NOT EDIT.
package queries

type User struct {
    ID   int64
    Name string
}
`

	sqlcFilePath := filepath.Join(queriesDir, "users.sql.go")
	if err := os.WriteFile(sqlcFilePath, []byte(sqlcFile), 0o644); err != nil {
		t.Fatalf("failed to write users.sql.go: %v", err)
	}

	// Test GetSQLOutputDirs finds the nested directory
	outputDirs, err := filter.GetSQLOutputDirs([]string{tmpDir})
	if err != nil {
		t.Fatalf("GetSQLOutputDirs failed: %v", err)
	}

	expectedOutputDir := filepath.Join(tmpDir, "db/sqlc")
	if !slices.Contains(outputDirs, expectedOutputDir) {
		t.Errorf("Should find nested SQLC output directory: %s", expectedOutputDir)
	}

	// Test filter recognizes SQLC files by both name and content
	fltr := filter.NewFilter(true, []filter.FilterOption{filter.FilterSQLC})
	if !fltr.ShouldFilter(sqlcFilePath) {
		t.Error("users.sql.go in SQLC output directory should be filtered")
	}
}

// TestParentDirectorySQLCDetection tests finding sqlc.yaml in parent directories.
func TestParentDirectorySQLCDetection(t *testing.T) {
	tmpDir := t.TempDir()

	// Create sqlc.yaml in "project root"
	projectRoot := tmpDir
	sqlcConfig := `version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/users.sql"
    gen:
      go:
        package: "queries"
        out: "internal/db"
`

	configPath := filepath.Join(projectRoot, "sqlc.yaml")
	if err := os.WriteFile(configPath, []byte(sqlcConfig), 0o644); err != nil {
		t.Fatalf("failed to write sqlc.yaml: %v", err)
	}

	// Create subdirectory structure (simulating running art-dupl on a subdirectory)
	subDir := filepath.Join(projectRoot, "internal/db")
	if err := os.MkdirAll(subDir, 0o755); err != nil {
		t.Fatalf("failed to create subdir: %v", err)
	}

	// Create SQLC file in subdirectory
	sqlcFile := `// Code generated by sqlc. DO NOT EDIT.
package queries

type User struct {
    ID   int64
    Name string
}
`

	sqlcFilePath := filepath.Join(subDir, "users.sql.go")
	if err := os.WriteFile(sqlcFilePath, []byte(sqlcFile), 0o644); err != nil {
		t.Fatalf("failed to write users.sql.go: %v", err)
	}

	// Test that FindSQLCConfigs finds sqlc.yaml even when analyzing subdirectory
	configs, err := filter.FindSQLCConfigs([]string{subDir})
	if err != nil {
		t.Fatalf("FindSQLCConfigs failed: %v", err)
	}

	if len(configs) == 0 {
		t.Error("Should find sqlc.yaml in parent directory")
	}

	// Test that output directory is correct (relative to project root)
	outputDirs, err := filter.GetSQLOutputDirs([]string{subDir})
	if err != nil {
		t.Fatalf("GetSQLOutputDirs failed: %v", err)
	}

	expectedOutputDir := filepath.Join(projectRoot, "internal/db")
	found := slices.Contains(outputDirs, expectedOutputDir)

	if !found {
		t.Errorf("Should resolve output directory relative to project root: %s", expectedOutputDir)
	}
}
