package config

import (
	"slices"
	"time"
)

// DetectionMethods is a slice of DetectionMethod for type safety.
type DetectionMethods []DetectionMethod

// IsDefault checks if methods have default value.
func (dm DetectionMethods) IsDefault() bool {
	return len(dm) == 1 && dm[0] == DetectionMethodArtDupl
}

// Contains checks if method is in methods list.
func (dm DetectionMethods) Contains(method DetectionMethod) bool {
	return slices.Contains(dm, method)
}

// IsEmpty checks if methods list is empty.
func (dm DetectionMethods) IsEmpty() bool {
	return len(dm) == 0
}

// IsHashOnly checks if only hash detection method is selected.
// This is useful for optimizing the analysis pipeline - when only hash detection
// is used, we can skip AST parsing and work directly with file paths.
func (dm DetectionMethods) IsHashOnly() bool {
	return len(dm) == 1 && dm[0] == DetectionMethodHash
}

// Config represents the dupl configuration with strong typing.
//
// Note: Config uses primitive types (int, string, bool) for JSON marshaling
// compatibility. Typed enums (FileType, DetectionMethod, etc.) provide validation.
type Config struct {
	// Threshold sets the minimum token sequence size to consider as duplicate
	Threshold int `json:"threshold,omitempty"`

	// IncludeVendor includes vendor directory in analysis
	IncludeVendor bool `json:"includeVendor,omitempty"`

	// IncludeNodeModules includes node_modules directory in hash-based analysis.
	// By default, node_modules is excluded in hash detection mode to avoid
	// processing large dependency directories. Set to true to include them.
	IncludeNodeModules bool `json:"includeNodeModules,omitempty"`

	// FilesFromStdin reads file paths from stdin when true
	FilesFromStdin bool `json:"filesFromStdin,omitempty"`

	// OutputFormat sets the output format with type safety
	OutputFormat OutputFormat `json:"outputFormat,omitempty"`

	// Verbose enables verbose output
	Verbose bool `json:"verbose,omitempty"`

	// Paths specifies the paths to analyze
	Paths []string `json:"paths,omitempty"`

	// IgnoreFiles specifies file patterns to ignore
	IgnoreFiles []string `json:"ignoreFiles,omitempty"`

	// MaxChildrenSerial sets the maximum children serial for large slices
	MaxChildrenSerial int `json:"maxChildrenSerial,omitempty"`

	// OutputFile specifies the output file (if not stdout)
	OutputFile string `json:"outputFile,omitempty"`

	// SortBy specifies sorting criteria for clone groups
	SortBy SortCriteria `json:"sortBy,omitempty"`

	// DetectionMethods specifies which detection methods to use
	DetectionMethods DetectionMethods `json:"detectionMethods,omitempty"`

	// Profile enables performance profiling output
	Profile bool `json:"profile,omitempty"`

	// Timeout specifies maximum execution time (0 = no timeout)
	Timeout time.Duration `json:"timeout,omitempty"`

	// IncludeSQLC includes sqlc.dev generated files in analysis (default: false, filtered)
	IncludeSQLC bool `json:"includeSQLC,omitempty"`

	// IncludeTempl includes templ-generated *_templ.go files in analysis (default: false, filtered).
	// .templ source files are always included regardless of this setting.
	IncludeTempl bool `json:"includeTempl,omitempty"`

	// IncludeProtobuf includes protobuf generated files (.pb.go, _grpc.pb.go)
	IncludeProtobuf bool `json:"includeProtobuf,omitempty"`

	// IncludeMockgen includes mockgen generated files
	IncludeMockgen bool `json:"includeMockgen,omitempty"`

	// IncludeStringer includes stringer generated files
	IncludeStringer bool `json:"includeStringer,omitempty"`

	// IncludeGeneric includes files with standard "Code generated by" comments in analysis (default: false, filtered).
	// This is a catch-all that catches any tool following the Go convention from https://go.dev/s/generatedcode.
	// Includes protoc-gen-connect-go, oapi-codegen, wire, deepcopy-gen, and any other generator.
	IncludeGeneric bool `json:"includeGeneric,omitempty"`

	// Only restricts analysis to a specific file type (FileTypeGo or FileTypeTempl).
	// FileTypeAll (empty string) means analyze all file types.
	Only FileType `json:"only,omitempty"`

	// IncludePatterns specifies file patterns to always include (takes precedence over filter)
	IncludePatterns []string `json:"includePatterns,omitempty"`

	// ExcludePatterns specifies additional file patterns to exclude
	ExcludePatterns []string `json:"excludePatterns,omitempty"`

	// Incremental enables incremental analysis (only analyze changed files)
	Incremental bool `json:"incremental,omitempty"`

	// CacheDir specifies the cache directory for AST caching
	// If empty, uses default .cache/art-dupl
	CacheDir string `json:"cacheDir,omitempty"`

	// ClearCache clears the cache before running (useful for forced full rebuild)
	ClearCache bool `json:"clearCache,omitempty"`

	// DetectionMode controls how identifier names participate in matching.
	// - "semantic" (default): alpha-normalized identifiers — detects Type 2 renamed clones.
	// - "exact": verbatim name hashing — Type 1 copy-paste only.
	// - "structural": AST shape only, ignores names entirely.
	DetectionMode DetectionMode `json:"detectionMode,omitempty"`

	// Workers specifies the number of concurrent workers for file parsing.
	// 0 or negative means use runtime.GOMAXPROCS(0).
	// 1 means sequential processing (same as Parse()).
	Workers int `json:"workers,omitempty"`

	// DiffMode enables diff visualization for HTML output.
	// When enabled, duplicate occurrences are shown with visual diff highlighting.
	DiffMode DiffMode `json:"diffMode,omitempty"`

	// RichText enables enhanced text output with classification badges,
	// priority indicators, and actionable suggestions.
	RichText bool `json:"richText,omitempty"`

	// SuppressTestLow suppresses test-file clones classified as low priority.
	// Reduces noise from test boilerplate without hiding production issues.
	SuppressTestLow bool `json:"suppressTestLow,omitempty"`

	// TestThreshold sets a separate minimum token count for test files.
	// When 0, defaults to max(30, Threshold) — test files need substantial
	// clones to be reported, filtering out common test boilerplate noise.
	TestThreshold int `json:"testThreshold,omitempty"`

	// IgnoreTests excludes all *_test.go files from analysis entirely.
	// Use --include-tests to override and analyze test files normally.
	IgnoreTests bool `json:"ignoreTests,omitempty"`

	// IncludeTests disables ALL test-specific filtering: treats *_test.go files
	// identically to production files. Overrides IgnoreTests, SuppressTestLow,
	// and TestThreshold defaults.
	IncludeTests bool `json:"includeTests,omitempty"`
}

// DefaultThreshold is the default minimum number of duplicated statements to report.
// With statement-level tokenization, each Go statement produces one composite token.
// A threshold of 1 means "report any duplicated statement." Users who want less
// noise should increase to 3-5. Post-hoc filters (overlap elimination, test
// suppression, actionability patterns) handle most noise automatically.
const DefaultThreshold = 1

// DefaultConfig returns a default configuration.
func DefaultConfig() *Config {
	return &Config{
		Threshold:          DefaultThreshold,
		IncludeVendor:      false,
		IncludeNodeModules: false,
		FilesFromStdin:     false,
		OutputFormat:       OutputFormatText,
		Verbose:            false,
		Paths:              []string{"."},
		IgnoreFiles:        []string{},
		MaxChildrenSerial:  10000,
		OutputFile:         "",
		SortBy:             SortBySize,
		DetectionMethods:   DetectionMethods{DetectionMethodArtDupl},
		Profile:            false,
		Timeout:            0,
		IncludeSQLC:        false,
		IncludeTempl:       false,
		IncludeProtobuf:    false,
		IncludeMockgen:     false,
		IncludeStringer:    false,
		IncludeGeneric:     false,
		Only:               "",
		IncludePatterns:    []string{},
		ExcludePatterns:    []string{},
		Incremental:        false,
		CacheDir:           "",
		ClearCache:         false,
		DetectionMode:      DetectionModeSemantic,
		Workers:            0,
		DiffMode:           DiffModeDisabled,
		RichText:           false,
		SuppressTestLow:    false,
		TestThreshold:      0,
		IgnoreTests:        false,
	}
}

// EffectiveTestThreshold returns the minimum token count for test-file clones.
// When IncludeTests is true, returns 0 (no test-specific filtering).
// When TestThreshold is explicitly set (>0), uses that value.
// Otherwise defaults to max(30, Threshold) to filter common test boilerplate.
func (c *Config) EffectiveTestThreshold() int {
	if c.IncludeTests {
		return 0
	}

	if c.TestThreshold > 0 {
		return c.TestThreshold
	}

	if c.Threshold > 30 {
		return c.Threshold
	}

	return 30
}

// EffectiveSuppressTestLow returns whether low-priority test clones should be suppressed.
// When IncludeTests is true, always returns false.
func (c *Config) EffectiveSuppressTestLow() bool {
	if c.IncludeTests {
		return false
	}

	return c.SuppressTestLow
}
