package config

import (
	"slices"
	"time"
)

// DetectionMethods is a slice of DetectionMethod for type safety.
type DetectionMethods []DetectionMethod

// IsDefault checks if methods have default value.
func (dm DetectionMethods) IsDefault() bool {
	return len(dm) == 1 && dm[0] == DetectionMethodArtDupl
}

// Contains checks if method is in methods list.
func (dm DetectionMethods) Contains(method DetectionMethod) bool {
	return slices.Contains(dm, method)
}

// IsEmpty checks if methods list is empty.
func (dm DetectionMethods) IsEmpty() bool {
	return len(dm) == 0
}

// IsHashOnly checks if only hash detection method is selected.
// This is useful for optimizing the analysis pipeline - when only hash detection
// is used, we can skip AST parsing and work directly with file paths.
func (dm DetectionMethods) IsHashOnly() bool {
	return len(dm) == 1 && dm[0] == DetectionMethodHash
}

// Config represents the dupl configuration with strong typing.
//
// Note: Config uses primitive types (int, string, bool) for JSON marshaling
// compatibility. Typed enums (FileType, DetectionMethod, etc.) provide validation.
type Config struct {
	// Threshold sets the minimum token sequence size to consider as duplicate
	Threshold int `json:"threshold,omitempty"`

	// IncludeVendor includes vendor directory in analysis
	IncludeVendor bool `json:"includeVendor,omitempty"`

	// IncludeNodeModules includes node_modules directory in hash-based analysis.
	// By default, node_modules is excluded in hash detection mode to avoid
	// processing large dependency directories. Set to true to include them.
	IncludeNodeModules bool `json:"includeNodeModules,omitempty"`

	// IncludeExamples includes example/demo directories in analysis.
	// By default, directories named examples/, example/, demo/, demos/ are
	// excluded to avoid inflating false-positive counts with throwaway code.
	IncludeExamples bool `json:"includeExamples,omitempty"`

	// FilesFromStdin reads file paths from stdin when true
	FilesFromStdin bool `json:"filesFromStdin,omitempty"`

	// OutputFormat sets the output format with type safety
	OutputFormat OutputFormat `json:"outputFormat,omitzero"`

	// Verbose enables verbose output
	Verbose bool `json:"verbose,omitempty"`

	// Paths specifies the paths to analyze
	Paths []string `json:"paths,omitempty"`

	// IgnoreFiles specifies file patterns to ignore
	IgnoreFiles []string `json:"ignoreFiles,omitempty"`

	// MaxChildrenSerial sets the maximum children serial for large slices
	MaxChildrenSerial int `json:"maxChildrenSerial,omitempty"`

	// OutputFile specifies the output file (if not stdout)
	OutputFile string `json:"outputFile,omitempty"`

	// SortBy specifies sorting criteria for clone groups
	SortBy SortCriteria `json:"sortBy,omitzero"`

	// DetectionMethods specifies which detection methods to use
	DetectionMethods DetectionMethods `json:"detectionMethods,omitempty"`

	// Profile enables performance profiling output
	Profile bool `json:"profile,omitempty"`

	// Timeout specifies maximum execution time (0 = no timeout)
	Timeout time.Duration `json:"timeout,omitempty,format:nano"`

	// IncludeSQLC includes sqlc.dev generated files in analysis (default: false, filtered)
	IncludeSQLC bool `json:"includeSQLC,omitempty"`

	// IncludeTempl includes templ-generated *_templ.go files in analysis (default: false, filtered).
	// .templ source files are always included regardless of this setting.
	IncludeTempl bool `json:"includeTempl,omitempty"`

	// IncludeProtobuf includes protobuf generated files (.pb.go, _grpc.pb.go)
	IncludeProtobuf bool `json:"includeProtobuf,omitempty"`

	// IncludeMockgen includes mockgen generated files
	IncludeMockgen bool `json:"includeMockgen,omitempty"`

	// IncludeStringer includes stringer generated files
	IncludeStringer bool `json:"includeStringer,omitempty"`

	// IncludeGeneric includes files with standard "Code generated by" comments in analysis (default: false, filtered).
	// This is a catch-all that catches any tool following the Go convention from https://go.dev/s/generatedcode.
	// Includes protoc-gen-connect-go, oapi-codegen, wire, deepcopy-gen, and any other generator.
	IncludeGeneric bool `json:"includeGeneric,omitempty"`

	// Only restricts analysis to a specific file type (FileTypeGo or FileTypeTempl).
	// FileTypeAll (empty string) means analyze all file types.
	Only FileType `json:"only,omitzero"`

	// IncludePatterns specifies file patterns to always include (takes precedence over filter)
	IncludePatterns []string `json:"includePatterns,omitempty"`

	// ExcludePatterns specifies additional file patterns to exclude
	ExcludePatterns []string `json:"excludePatterns,omitempty"`

	// Incremental enables incremental analysis (only analyze changed files)
	Incremental bool `json:"incremental,omitempty"`

	// CacheDir specifies the cache directory for AST caching
	// If empty, uses default .cache/art-dupl
	CacheDir string `json:"cacheDir,omitempty"`

	// ClearCache clears the cache before running (useful for forced full rebuild)
	ClearCache bool `json:"clearCache,omitempty"`

	// MaxCacheEntries limits the number of cached AST files on disk.
	// 0 means unlimited. When exceeded, oldest entries are evicted.
	MaxCacheEntries int `json:"maxCacheEntries,omitempty"`

	// DetectionMode controls how identifier names participate in matching.
	// - "semantic" (default): alpha-normalized identifiers — detects Type 2 renamed clones.
	// - "exact": verbatim name hashing — Type 1 copy-paste only.
	// - "structural": AST shape only, ignores names entirely.
	DetectionMode DetectionMode `json:"detectionMode,omitzero"`

	// Workers specifies the number of concurrent workers for file parsing.
	// 0 or negative means use runtime.GOMAXPROCS(0).
	// 1 means sequential processing (same as Parse()).
	Workers int `json:"workers,omitempty"`

	// SearchWorkers controls suffix tree search parallelism.
	// 0 or 1 = sequential (default), >1 = parallel DFS with N workers.
	SearchWorkers int `json:"searchWorkers,omitempty"`

	// DiffMode enables diff visualization for HTML output.
	// When enabled, duplicate occurrences are shown with visual diff highlighting.
	DiffMode DiffMode `json:"diffMode,omitzero"`

	// RichText enables enhanced text output with classification badges,
	// priority indicators, and actionable suggestions.
	RichText bool `json:"richText,omitempty"`

	// SuppressTestLow suppresses test-file clones classified as low priority.
	// Reduces noise from test boilerplate without hiding production issues.
	SuppressTestLow bool `json:"suppressTestLow,omitempty"`

	// TestThreshold sets a separate minimum token count for test files.
	// When 0, defaults to max(30, Threshold) — test files need substantial
	// clones to be reported, filtering out common test boilerplate noise.
	TestThreshold int `json:"testThreshold,omitempty"`

	// IgnoreTests excludes all *_test.go files from analysis entirely.
	// Use --include-tests to override and analyze test files normally.
	IgnoreTests bool `json:"ignoreTests,omitempty"`

	// IncludeTests disables ALL test-specific filtering: treats *_test.go files
	// identically to production files. Overrides IgnoreTests, SuppressTestLow,
	// and TestThreshold defaults.
	IncludeTests bool `json:"includeTests,omitempty"`

	// MinLines suppresses clone groups whose clones span fewer than N source lines.
	// 0 = disabled (no line-count filtering). Useful for filtering trivial
	// one-liner clones that pass the token threshold but are too short to matter.
	MinLines int `json:"minLines,omitempty"`

	// MinTokens suppresses clone groups where any clone has fewer than N tokens.
	// 0 = disabled. Token-based complement to --threshold (statement-based) and
	// --min-lines (line-based). Useful for filtering clones that meet the
	// statement threshold but are still semantically trivial (e.g., a 5-statement
	// clone where each statement is a single token).
	MinTokens int `json:"minTokens,omitempty"`

	// Quiet suppresses non-essential status output (progress messages,
	// profiling notices). Clone results are still printed.
	Quiet bool `json:"quiet,omitempty"`

	// TypeAware enables go/types-based detection: encodes each local variable's
	// static type into the identifier hash so that different-typed variables with
	// the same name produce different hashes. Eliminates false positives like
	// time.Time.String matching *big.Int.String. Requires go/packages type
	// checking (10-100x slower). Only effective with semantic detection mode.
	TypeAware bool `json:"typeAware,omitempty"`

	// NoActionability disables actionability filtering.
	// When true, all clone groups are reported including boilerplate/non-actionable ones.
	NoActionability bool `json:"noActionability,omitempty"`

	// DisabledPatterns suppresses specific actionability patterns by label.
	// When a pattern label is in this list, clones matching that pattern are
	// reported instead of suppressed. Use --list-patterns to see all labels.
	DisabledPatterns []string `json:"disabledPatterns,omitempty"`

	// Explain enables explanation output for each clone group (clone type,
	// actionability, category, extractability, suggestion).
	Explain bool `json:"explain,omitempty"`

	// NoAcceptDirectives disables //art-dupl:accept inline directive processing.
	// When true, all clone groups are reported regardless of accept directives.
	NoAcceptDirectives bool `json:"noAcceptDirectives,omitempty"`

	// IncludeIgnored disables .gitignore honoring during file enumeration.
	// When true, gitignored files are included in the analysis.
	IncludeIgnored bool `json:"includeIgnored,omitempty"`

	// ShowSuppressed surfaces clone groups that would normally be filtered by
	// actionability patterns, min-lines, test-threshold, or accept directives.
	// Used for calibration to measure recall (false negatives).
	ShowSuppressed bool `json:"showSuppressed,omitempty"`

	// SuggestGenerics enriches output by highlighting generics-extraction
	// candidates: clone groups where the algorithm is identical but the local
	// variable types differ across instances. This is the class of duplication
	// that --type-aware would suppress (because different concrete types produce
	// different hashes) but that Go generics can eliminate. Loads type info
	// (same cost as --type-aware) but does NOT encode types in the hash, so
	// structurally-identical clones on different types still match. All clone
	// groups are shown; generics candidates are annotated with a hint and
	// suggestion. Incompatible with --type-aware (suggest-generics takes
	// precedence).
	SuggestGenerics bool `json:"suggestGenerics,omitempty"`
}

// DefaultThreshold is the default minimum number of duplicated statements to report.
// With statement-level tokenization, each Go statement produces one composite token.
// A threshold of 5 filters trivial patterns (single-call noise, error-check
// boilerplate) while still catching meaningful duplication. Users who want more
// sensitivity can lower to 3; users who want less noise can raise to 10+.
const DefaultThreshold = 5

// DefaultConfig returns a default configuration.
func DefaultConfig() *Config {
	return &Config{
		Threshold:          DefaultThreshold,
		IncludeVendor:      false,
		IncludeNodeModules: false,
		FilesFromStdin:     false,
		OutputFormat:       OutputFormatText,
		Verbose:            false,
		Paths:              []string{"."},
		IgnoreFiles:        []string{},
		MaxChildrenSerial:  10000,
		OutputFile:         "",
		SortBy:             SortBySize,
		DetectionMethods:   DetectionMethods{DetectionMethodArtDupl},
		Profile:            false,
		Timeout:            0,
		IncludeSQLC:        false,
		IncludeTempl:       false,
		IncludeProtobuf:    false,
		IncludeMockgen:     false,
		IncludeStringer:    false,
		IncludeGeneric:     false,
		Only:               "",
		IncludePatterns:    []string{},
		ExcludePatterns:    []string{},
		Incremental:        false,
		CacheDir:           "",
		ClearCache:         false,
		DetectionMode:      DetectionModeSemantic,
		Workers:            0,
		SearchWorkers:      0,
		DiffMode:           DiffModeDisabled,
		RichText:           false,
		SuppressTestLow:    false,
		TestThreshold:      0,
		IgnoreTests:        false,
		MinLines:           0,
		MinTokens:          0,
		TypeAware:          false,
	}
}

// EffectiveTestThreshold returns the minimum token count for test-file clones.
// When IncludeTests is true, returns 0 (no test-specific filtering).
// When TestThreshold is explicitly set (>0), uses that value.
// Otherwise defaults to max(30, Threshold) to filter common test boilerplate.
func (c *Config) EffectiveTestThreshold() int {
	if c.IncludeTests {
		return 0
	}

	if c.TestThreshold > 0 {
		return c.TestThreshold
	}

	if c.Threshold > 30 {
		return c.Threshold
	}

	return 30
}

// EffectiveSuppressTestLow returns whether low-priority test clones should be suppressed.
// When IncludeTests is true, always returns false.
func (c *Config) EffectiveSuppressTestLow() bool {
	if c.IncludeTests {
		return false
	}

	return c.SuppressTestLow
}
