package cmd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/gogenfilter/v3"
)

func TestGeneratorIncludesAny(t *testing.T) {
	tests := []struct {
		name     string
		includes generatorIncludes
		expected bool
	}{
		{"empty", generatorIncludes{}, false},
		{"sqlc only", generatorIncludes{SQLC: true}, true},
		{"templ only", generatorIncludes{Templ: true}, true},
		{"protobuf only", generatorIncludes{Protobuf: true}, true},
		{"mockgen only", generatorIncludes{Mockgen: true}, true},
		{"stringer only", generatorIncludes{Stringer: true}, true},
		{"generic only", generatorIncludes{Generic: true}, true},
		{"all set", generatorIncludes{
			SQLC: true, Templ: true, Protobuf: true, Mockgen: true, Stringer: true, Generic: true,
		}, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.includes.any(); got != tt.expected {
				t.Errorf("any() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestGeneratorIncludesAllowsContent(t *testing.T) {
	sqlcContent := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\nfunc Q() {}\n")
	templContent := []byte("// Code generated by templ. DO NOT EDIT.\npackage x\nvar _ = templ.Component\n")
	protobufContent := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
	mockgenContent := []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n")
	stringerContent := []byte(`// Code generated by "stringer". DO NOT EDIT.
package x
`)
	regularContent := []byte("package main\nfunc main() {}\n")

	tests := []struct {
		name     string
		includes generatorIncludes
		content  []byte
		expected bool
	}{
		{"sqlc flag + sqlc content", generatorIncludes{SQLC: true}, sqlcContent, true},
		{"templ flag + templ content", generatorIncludes{Templ: true}, templContent, true},
		{"protobuf flag + protobuf content", generatorIncludes{Protobuf: true}, protobufContent, true},
		{"mockgen flag + mockgen content", generatorIncludes{Mockgen: true}, mockgenContent, true},
		{"stringer flag + stringer content", generatorIncludes{Stringer: true}, stringerContent, true},
		{"sqlc flag + regular content", generatorIncludes{SQLC: true}, regularContent, false},
		{"no flags + sqlc content", generatorIncludes{}, sqlcContent, false},
		{"sqlc flag + templ content (wrong category)", generatorIncludes{SQLC: true}, templContent, false},
		{"templ flag + sqlc content (wrong category)", generatorIncludes{Templ: true}, sqlcContent, false},
		{"empty content", generatorIncludes{SQLC: true}, []byte{}, false},
		{"all flags + sqlc content", generatorIncludes{
			SQLC: true, Templ: true, Protobuf: true, Mockgen: true, Stringer: true, Generic: true,
		}, sqlcContent, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.includes.allowsContent(tt.content); got != tt.expected {
				t.Errorf("allowsContent() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestShouldIncludeFile_WithGenericOverride(t *testing.T) {
	dir := t.TempDir()

	sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

type Query struct {
	Name string
}

func (q *Query) Execute() error {
	return nil
}`

	sqlcPath := filepath.Join(dir, "sqlc1.go")
	if err := os.WriteFile(sqlcPath, []byte(sqlcCode), 0o644); err != nil {
		t.Fatal(err)
	}

	regularCode := "package main\nfunc main() {}\n"

	regularPath := filepath.Join(dir, "regular.go")
	if err := os.WriteFile(regularPath, []byte(regularCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// Build a filter that has FilterGeneric enabled (default for setupFilter with no includes).
	cfg, err := gogenfilter.WithFilterOptions(
		gogenfilter.FilterTempl,
		gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen,
		gogenfilter.FilterStringer,
		gogenfilter.FilterGeneric,
	)
	if err != nil {
		t.Fatal(err)
	}

	f, err := gogenfilter.NewFilter(cfg)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name     string
		path     string
		includes generatorIncludes
		expected bool
	}{
		{"sqlc file without include flag", sqlcPath, generatorIncludes{}, false},
		{"sqlc file with include-sqlc flag", sqlcPath, generatorIncludes{SQLC: true}, true},
		{"sqlc file with wrong include flag", sqlcPath, generatorIncludes{Templ: true}, false},
		{"regular file without includes", regularPath, generatorIncludes{}, true},
		{"regular file with includes", regularPath, generatorIncludes{SQLC: true}, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := shouldIncludeFile(f, tt.path, nil, tt.includes)
			if got != tt.expected {
				t.Errorf("shouldIncludeFile() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestFilterExcludedGenerated(t *testing.T) {
	templContent := []byte("// Code generated by templ - DO NOT EDIT.\npackage x\nvar _ = templ.Component\n")
	sqlcContent := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\nfunc Q() {}\n")
	protobufContent := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
	regularContent := []byte("package main\nfunc main() {}\n")

	tests := []struct {
		name         string
		content      []byte
		includes     generatorIncludes
		wantFiltered bool
		wantReason   gogenfilter.FilterReason
	}{
		{
			"templ content, not included",
			templContent, generatorIncludes{Generic: true},
			true, gogenfilter.ReasonTempl,
		},
		{
			"templ content, explicitly included",
			templContent, generatorIncludes{Generic: true, Templ: true},
			false, "",
		},
		{
			"sqlc content, not included",
			sqlcContent, generatorIncludes{Generic: true},
			true, gogenfilter.ReasonSQLC,
		},
		{
			"sqlc content, explicitly included",
			sqlcContent, generatorIncludes{Generic: true, SQLC: true},
			false, "",
		},
		{
			"protobuf content, not included",
			protobufContent, generatorIncludes{Generic: true},
			true, gogenfilter.ReasonProtobuf,
		},
		{
			"protobuf content, explicitly included",
			protobufContent, generatorIncludes{Generic: true, Protobuf: true},
			false, "",
		},
		{
			"regular content, not filtered",
			regularContent, generatorIncludes{Generic: true},
			false, "",
		},
		{
			"empty content",
			[]byte{}, generatorIncludes{Generic: true},
			false, "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			reason, filtered := filterExcludedGenerated(tt.content, tt.includes)
			if filtered != tt.wantFiltered {
				t.Errorf("filterExcludedGenerated() filtered = %v, want %v", filtered, tt.wantFiltered)
			}
			if filtered && reason != tt.wantReason {
				t.Errorf("filterExcludedGenerated() reason = %v, want %v", reason, tt.wantReason)
			}
		})
	}
}

func TestShouldIncludeFile_TemplContentDefenseInDepth(t *testing.T) {
	dir := t.TempDir()

	// A templ-generated file WITHOUT the _templ.go suffix — this is the gap scenario.
	// Without FilterGeneric active, this file would bypass FilterTempl (which only
	// matches _templ.go suffix files).
	templNoSuffixCode := `// Code generated by templ - DO NOT EDIT.
package x

import "context"

type Component struct{}

func (c *Component) Render(ctx context.Context) error { return nil }`

	templNoSuffixPath := filepath.Join(dir, "custom_template.go")
	if err := os.WriteFile(templNoSuffixPath, []byte(templNoSuffixCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// A normal _templ.go file — this should be caught by FilterTempl regardless.
	templSuffixPath := filepath.Join(dir, "view_templ.go")
	if err := os.WriteFile(templSuffixPath, []byte(templNoSuffixCode), 0o644); err != nil {
		t.Fatal(err)
	}

	regularCode := "package main\nfunc main() {}\n"
	regularPath := filepath.Join(dir, "main.go")
	if err := os.WriteFile(regularPath, []byte(regularCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// Filter with FilterTempl active but FilterGeneric DISABLED (simulating
	// --include-generated generic). The gap: a templ file without _templ.go
	// suffix bypasses FilterTempl and FilterGeneric is off.
	cfg, err := gogenfilter.WithFilterOptions(
		gogenfilter.FilterTempl,
		gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen,
		gogenfilter.FilterStringer,
	)
	if err != nil {
		t.Fatal(err)
	}

	f, err := gogenfilter.NewFilter(cfg)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name     string
		path     string
		includes generatorIncludes
		expected bool
	}{
		// Without the content-based check, templNoSuffixPath would pass (bug).
		// The check catches it via the "Code generated by templ" marker.
		{
			"templ content without suffix, generic included but not templ",
			templNoSuffixPath, generatorIncludes{Generic: true},
			false,
		},
		{
			"templ content without suffix, templ explicitly included",
			templNoSuffixPath, generatorIncludes{Generic: true, Templ: true},
			true,
		},
		{
			"templ content with suffix, still caught by FilterTempl",
			templSuffixPath, generatorIncludes{Generic: true},
			false,
		},
		{
			"templ content with suffix, templ explicitly included",
			templSuffixPath, generatorIncludes{Generic: true, Templ: true},
			true,
		},
		{
			"regular file, not filtered",
			regularPath, generatorIncludes{Generic: true},
			true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := shouldIncludeFile(f, tt.path, nil, tt.includes)
			if got != tt.expected {
				t.Errorf("shouldIncludeFile() = %v, want %v", got, tt.expected)
			}
		})
	}
}
