package cmd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/gogenfilter/v3"
)

func TestGeneratorIncludesAny(t *testing.T) {
	tests := []struct {
		name     string
		includes generatorIncludes
		expected bool
	}{
		{"empty", generatorIncludes{}, false},
		{"sqlc only", generatorIncludes{SQLC: true}, true},
		{"templ only", generatorIncludes{Templ: true}, true},
		{"protobuf only", generatorIncludes{Protobuf: true}, true},
		{"mockgen only", generatorIncludes{Mockgen: true}, true},
		{"stringer only", generatorIncludes{Stringer: true}, true},
		{"generic only", generatorIncludes{Generic: true}, true},
		{"all set", generatorIncludes{
			SQLC: true, Templ: true, Protobuf: true, Mockgen: true, Stringer: true, Generic: true,
		}, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.includes.any(); got != tt.expected {
				t.Errorf("any() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestGeneratorIncludesAllowsContent(t *testing.T) {
	sqlcContent := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\nfunc Q() {}\n")
	templContent := []byte("// Code generated by templ. DO NOT EDIT.\npackage x\nvar _ = templ.Component\n")
	protobufContent := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
	mockgenContent := []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n")
	stringerContent := []byte(`// Code generated by "stringer". DO NOT EDIT.
package x
`)
	regularContent := []byte("package main\nfunc main() {}\n")

	tests := []struct {
		name     string
		includes generatorIncludes
		content  []byte
		expected bool
	}{
		{"sqlc flag + sqlc content", generatorIncludes{SQLC: true}, sqlcContent, true},
		{"templ flag + templ content", generatorIncludes{Templ: true}, templContent, true},
		{"protobuf flag + protobuf content", generatorIncludes{Protobuf: true}, protobufContent, true},
		{"mockgen flag + mockgen content", generatorIncludes{Mockgen: true}, mockgenContent, true},
		{"stringer flag + stringer content", generatorIncludes{Stringer: true}, stringerContent, true},
		{"sqlc flag + regular content", generatorIncludes{SQLC: true}, regularContent, false},
		{"no flags + sqlc content", generatorIncludes{}, sqlcContent, false},
		{"sqlc flag + templ content (wrong category)", generatorIncludes{SQLC: true}, templContent, false},
		{"templ flag + sqlc content (wrong category)", generatorIncludes{Templ: true}, sqlcContent, false},
		{"empty content", generatorIncludes{SQLC: true}, []byte{}, false},
		{"all flags + sqlc content", generatorIncludes{
			SQLC: true, Templ: true, Protobuf: true, Mockgen: true, Stringer: true, Generic: true,
		}, sqlcContent, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.includes.allowsContent(tt.content); got != tt.expected {
				t.Errorf("allowsContent() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestShouldIncludeFile_WithGenericOverride(t *testing.T) {
	dir := t.TempDir()

	sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

type Query struct {
	Name string
}

func (q *Query) Execute() error {
	return nil
}`

	sqlcPath := filepath.Join(dir, "sqlc1.go")
	if err := os.WriteFile(sqlcPath, []byte(sqlcCode), 0o644); err != nil {
		t.Fatal(err)
	}

	regularCode := "package main\nfunc main() {}\n"

	regularPath := filepath.Join(dir, "regular.go")
	if err := os.WriteFile(regularPath, []byte(regularCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// Build a filter that has FilterGeneric enabled (default for setupFilter with no includes).
	cfg, err := gogenfilter.WithFilterOptions(
		gogenfilter.FilterTempl,
		gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen,
		gogenfilter.FilterStringer,
		gogenfilter.FilterGeneric,
	)
	if err != nil {
		t.Fatal(err)
	}

	f, err := gogenfilter.NewFilter(cfg)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name     string
		path     string
		includes generatorIncludes
		expected bool
	}{
		{"sqlc file without include flag", sqlcPath, generatorIncludes{}, false},
		{"sqlc file with include-sqlc flag", sqlcPath, generatorIncludes{SQLC: true}, true},
		{"sqlc file with wrong include flag", sqlcPath, generatorIncludes{Templ: true}, false},
		{"regular file without includes", regularPath, generatorIncludes{}, true},
		{"regular file with includes", regularPath, generatorIncludes{SQLC: true}, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := shouldIncludeFile(f, tt.path, nil, tt.includes)
			if got != tt.expected {
				t.Errorf("shouldIncludeFile() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestFilterExcludedGenerated(t *testing.T) {
	templContent := []byte("// Code generated by templ - DO NOT EDIT.\npackage x\nvar _ = templ.Component\n")
	sqlcContent := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\nfunc Q() {}\n")
	protobufContent := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
	regularContent := []byte("package main\nfunc main() {}\n")

	tests := []struct {
		name         string
		content      []byte
		includes     generatorIncludes
		wantFiltered bool
		wantReason   gogenfilter.FilterReason
	}{
		{
			name:         "templ content, not included",
			content:      templContent,
			includes:     generatorIncludes{Generic: true},
			wantFiltered: true,
			wantReason:   gogenfilter.ReasonTempl,
		},
		{
			name:         "templ content, explicitly included",
			content:      templContent,
			includes:     generatorIncludes{Generic: true, Templ: true},
			wantFiltered: false,
			wantReason:   "",
		},
		{
			name:         "sqlc content, not included",
			content:      sqlcContent,
			includes:     generatorIncludes{Generic: true},
			wantFiltered: true,
			wantReason:   gogenfilter.ReasonSQLC,
		},
		{
			name:         "sqlc content, explicitly included",
			content:      sqlcContent,
			includes:     generatorIncludes{Generic: true, SQLC: true},
			wantFiltered: false,
			wantReason:   "",
		},
		{
			name:         "protobuf content, not included",
			content:      protobufContent,
			includes:     generatorIncludes{Generic: true},
			wantFiltered: true,
			wantReason:   gogenfilter.ReasonProtobuf,
		},
		{
			name:         "protobuf content, explicitly included",
			content:      protobufContent,
			includes:     generatorIncludes{Generic: true, Protobuf: true},
			wantFiltered: false,
			wantReason:   "",
		},
		{
			name:         "regular content, not filtered",
			content:      regularContent,
			includes:     generatorIncludes{Generic: true},
			wantFiltered: false,
			wantReason:   "",
		},
		{
			name:         "empty content",
			content:      []byte{},
			includes:     generatorIncludes{Generic: true},
			wantFiltered: false,
			wantReason:   "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			reason, filtered := filterExcludedGenerated(tt.content, tt.includes)
			if filtered != tt.wantFiltered {
				t.Errorf("filterExcludedGenerated() filtered = %v, want %v", filtered, tt.wantFiltered)
			}

			if filtered && reason != tt.wantReason {
				t.Errorf("filterExcludedGenerated() reason = %v, want %v", reason, tt.wantReason)
			}
		})
	}
}

func TestShouldIncludeFile_TemplContentDefenseInDepth(t *testing.T) {
	dir := t.TempDir()

	// A templ-generated file WITHOUT the _templ.go suffix — this is the gap scenario.
	// Without FilterGeneric active, this file would bypass FilterTempl (which only
	// matches _templ.go suffix files).
	templNoSuffixCode := `// Code generated by templ - DO NOT EDIT.
package x

import "context"

type Component struct{}

func (c *Component) Render(ctx context.Context) error { return nil }`

	templNoSuffixPath := filepath.Join(dir, "custom_template.go")
	if err := os.WriteFile(templNoSuffixPath, []byte(templNoSuffixCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// A normal _templ.go file — this should be caught by FilterTempl regardless.
	templSuffixPath := filepath.Join(dir, "view_templ.go")
	if err := os.WriteFile(templSuffixPath, []byte(templNoSuffixCode), 0o644); err != nil {
		t.Fatal(err)
	}

	regularCode := "package main\nfunc main() {}\n"
	regularPath := filepath.Join(dir, "main.go")

	if err := os.WriteFile(regularPath, []byte(regularCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// fTemplFiltered: FilterTempl active, FilterGeneric disabled (simulates
	// --include-generated generic without templ). This is the gap scenario:
	// a templ file without _templ.go suffix bypasses FilterTempl.
	fTemplFiltered := newTestFilter(t, gogenfilter.FilterTempl, gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen, gogenfilter.FilterStringer)

	// fTemplAllowed: FilterTempl NOT active (simulates --include-generated templ).
	// No FilterGeneric either (--include-generated generic is also on).
	fTemplAllowed := newTestFilter(t, gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen, gogenfilter.FilterStringer)

	tests := []struct {
		name     string
		path     string
		filter   *gogenfilter.Filter
		includes generatorIncludes
		expected bool
	}{
		// Gap scenario: templ content without _templ.go suffix, FilterGeneric disabled.
		// Without the content check, this would pass. The check catches it.
		{
			name:     "templ content without suffix, generic included but not templ",
			path:     templNoSuffixPath,
			filter:   fTemplFiltered,
			includes: generatorIncludes{Generic: true},
			expected: false,
		},
		{
			name:     "templ content without suffix, templ explicitly included",
			path:     templNoSuffixPath,
			filter:   fTemplAllowed,
			includes: generatorIncludes{Generic: true, Templ: true},
			expected: true,
		},
		// Standard _templ.go suffix — FilterTempl catches it regardless.
		{
			name:     "templ content with suffix, caught by FilterTempl",
			path:     templSuffixPath,
			filter:   fTemplFiltered,
			includes: generatorIncludes{Generic: true},
			expected: false,
		},
		{
			name:     "templ content with suffix, templ included (FilterTempl off)",
			path:     templSuffixPath,
			filter:   fTemplAllowed,
			includes: generatorIncludes{Generic: true, Templ: true},
			expected: true,
		},
		// Regular files always pass.
		{
			name:     "regular file, not filtered",
			path:     regularPath,
			filter:   fTemplFiltered,
			includes: generatorIncludes{Generic: true},
			expected: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := shouldIncludeFile(tt.filter, tt.path, nil, tt.includes)
			if got != tt.expected {
				t.Errorf("shouldIncludeFile() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func newTestFilter(t *testing.T, opts ...gogenfilter.FilterOption) *gogenfilter.Filter {
	t.Helper()

	cfg, err := gogenfilter.WithFilterOptions(opts...)
	if err != nil {
		t.Fatal(err)
	}

	f, err := gogenfilter.NewFilter(cfg)
	if err != nil {
		t.Fatal(err)
	}

	return f
}

func TestFilterStatsSourceBreakdown(t *testing.T) {
	t.Parallel()

	stats := NewFilterStats(nil)

	stats.Record(gogenfilter.FilterResult{Filtered: true, Reason: gogenfilter.ReasonTempl})
	stats.Record(gogenfilter.FilterResult{Filtered: true, Reason: gogenfilter.ReasonSQLC})

	stats.RecordWithSource(
		gogenfilter.FilterResult{Filtered: true, Reason: gogenfilter.ReasonTempl},
		FilterSourceDefenseInDepth,
	)

	if stats.TotalFiltered() != 3 {
		t.Errorf("TotalFiltered = %d, want 3", stats.TotalFiltered())
	}

	sourceBreakdown := stats.SourceBreakdown()
	if sourceBreakdown[string(FilterSourceGogenfilter)] != 2 {
		t.Errorf("gogenfilter count = %d, want 2", sourceBreakdown[string(FilterSourceGogenfilter)])
	}

	if sourceBreakdown[string(FilterSourceDefenseInDepth)] != 1 {
		t.Errorf("defense-in-depth count = %d, want 1", sourceBreakdown[string(FilterSourceDefenseInDepth)])
	}
}

func TestShouldIncludeFile_TracksDefenseInDepthSource(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()

	// A templ-generated file WITHOUT the _templ.go suffix.
	templNoSuffixCode := `// Code generated by templ - DO NOT EDIT.
package x

type Component struct{}

func (c *Component) Render() error { return nil }`

	templNoSuffixPath := filepath.Join(dir, "custom_template.go")
	if err := os.WriteFile(templNoSuffixPath, []byte(templNoSuffixCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// FilterTempl active, FilterGeneric disabled (simulates --include-generated generic).
	f := newTestFilter(t, gogenfilter.FilterTempl, gogenfilter.FilterProtobuf,
		gogenfilter.FilterMockgen, gogenfilter.FilterStringer)

	stats := NewFilterStats(f.FilterReasons())

	got := shouldIncludeFile(f, templNoSuffixPath, stats, generatorIncludes{Generic: true})
	if got {
		t.Error("templ content without suffix should be filtered by defense-in-depth")
	}

	sourceBreakdown := stats.SourceBreakdown()
	if sourceBreakdown[string(FilterSourceDefenseInDepth)] != 1 {
		t.Errorf("defense-in-depth count = %d, want 1", sourceBreakdown[string(FilterSourceDefenseInDepth)])
	}

	if sourceBreakdown[string(FilterSourceGogenfilter)] != 0 {
		t.Errorf("gogenfilter count = %d, want 0", sourceBreakdown[string(FilterSourceGogenfilter)])
	}
}

// TestMarkersMatchGogenfilter is a drift-detection test that verifies our
// hardcoded generation markers (sqlcMarker, templMarker, protobufMarker) are
// consistent with gogenfilter's detection logic. If gogenfilter changes its
// internal marker strings but our constants don't follow, our defense-in-depth
// check would silently miss files. This test catches that drift.
//
// For each filename-gated category, we construct a file with our marker + the
// expected suffix, run it through gogenfilter, and verify the FilterReason
// matches what matchedGeneratedCategory returns for the same content.
func TestMarkersMatchGogenfilter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		filename string
		content  []byte
		filter   gogenfilter.FilterOption
	}{
		{
			name:     "templ",
			filename: "component_templ.go",
			content:  []byte("// Code generated by templ - DO NOT EDIT.\npackage x\nvar _ = templ.Component\n"),
			filter:   gogenfilter.FilterTempl,
		},
		{
			name:     "sqlc",
			filename: "query.sql.go",
			content:  []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\nfunc Q() {}\n"),
			filter:   gogenfilter.FilterSQLC,
		},
		{
			name:     "protobuf",
			filename: "types.pb.go",
			content:  []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n"),
			filter:   gogenfilter.FilterProtobuf,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			// Our matchedGeneratedCategory must classify this content.
			ourReason, ourOk := matchedGeneratedCategory(tt.content)
			if !ourOk {
				t.Fatalf("matchedGeneratedCategory did not detect %s content", tt.name)
			}

			// gogenfilter must also classify this file with the SAME reason.
			f := newTestFilter(t, tt.filter)

			result, err := f.FilterDetailedWithContent(tt.filename, tt.content)
			if err != nil {
				t.Fatalf("FilterDetailedWithContent error: %v", err)
			}

			if !result.Filtered {
				t.Fatalf("gogenfilter did not filter %s file (reason=%s)", tt.name, result.Reason)
			}

			if result.Reason != ourReason {
				t.Errorf("reason mismatch: our markers say %s, gogenfilter says %s — marker drift detected",
					ourReason, result.Reason)
			}
		})
	}
}

// TestMockgenStringerMarkersMatchGogenfilter verifies that our content-based
// detection for mockgen/stringer (delegated to gogenfilter) is consistent.
// Since we call gogenfilter.Is*Generated directly for these, drift is
// structurally impossible — but this test documents the contract.
func TestMockgenStringerMarkersMatchGogenfilter(t *testing.T) {
	t.Parallel()

	mockgenContent := []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n")
	stringerContent := []byte("// Code generated by \"stringer\". DO NOT EDIT.\npackage x\n")

	if !gogenfilter.IsMockgenGenerated("", string(mockgenContent)) {
		t.Error("gogenfilter.IsMockgenGenerated does not match mockgen content")
	}

	if !gogenfilter.IsStringerGenerated("", string(stringerContent)) {
		t.Error("gogenfilter.IsStringerGenerated does not match stringer content")
	}
}
