package cmd

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"slices"
	"testing"
	"time"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/gogenfilter/v3"
)

// TestStdinFeed_CancelUnblocksScanner verifies that cancelling the context
// unblocks the inherently blocking bufio.Scanner.Scan by closing the reader.
// Without the close-on-cancel watcher, this test would hang until the timeout.
func TestStdinFeed_CancelUnblocksScanner(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	t.Cleanup(func() {
		_ = w.Close()
		_ = r.Close()
	})

	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)

	ch := feedFromStdin(ctx, r, nil, nil, generatorIncludes{}, "")

	cancel()

	select {
	case _, ok := <-ch:
		if ok {
			t.Fatal("expected channel closed, got value")
		}
	case <-time.After(2 * time.Second):
		t.Fatal("timed out: stdin reader did not exit after context cancellation")
	}
}

// TestStdinFeed_ReadsPaths verifies that file paths piped to the reader are
// emitted on the channel, and that the channel closes on EOF.
func TestStdinFeed_ReadsPaths(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	want := []string{"foo.go", "bar.go", "baz.go"}
	for _, p := range want {
		if _, err := w.WriteString(p + "\n"); err != nil {
			t.Fatalf("WriteString error: %v", err)
		}
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close error: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)

	ch := feedFromStdin(ctx, r, nil, nil, generatorIncludes{}, "")

	var got []string
	for p := range ch {
		got = append(got, p)
	}

	if !slices.Equal(got, want) {
		t.Errorf("stdin paths = %v, want %v", got, want)
	}
}

// TestStdinFeed_PartialReadThenCancel verifies that paths already sent
// before cancellation are received, and that the goroutine exits promptly
// after cancel even if the pipe is still open.
func TestStdinFeed_PartialReadThenCancel(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	t.Cleanup(func() {
		_ = w.Close()
		_ = r.Close()
	})

	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)

	ch := feedFromStdin(ctx, r, nil, nil, generatorIncludes{}, "")

	if _, err := w.WriteString("first.go\n"); err != nil {
		t.Fatalf("WriteString error: %v", err)
	}

	if _, err := w.WriteString("second.go\n"); err != nil {
		t.Fatalf("WriteString error: %v", err)
	}

	got := make([]string, 0, 2)
	readDone := make(chan struct{})

	go func() {
		for p := range ch {
			got = append(got, p)
		}

		close(readDone)
	}()

	time.Sleep(100 * time.Millisecond)

	cancel()

	select {
	case <-readDone:
	case <-time.After(2 * time.Second):
		t.Fatal("timed out: stdin reader did not exit after cancellation")
	}

	if len(got) < 2 {
		t.Errorf("expected at least 2 paths before cancellation, got %d: %v", len(got), got)
	}
}

// TestStdinFeed_TimeoutUnblocksScanner verifies that a context deadline
// (context.WithTimeout) unblocks the scanner just like an explicit cancel.
func TestStdinFeed_TimeoutUnblocksScanner(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	t.Cleanup(func() {
		_ = w.Close()
		_ = r.Close()
	})

	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	t.Cleanup(cancel)

	ch := feedFromStdin(ctx, r, nil, nil, generatorIncludes{}, "")

	select {
	case _, ok := <-ch:
		if ok {
			t.Fatal("expected channel closed, got value")
		}
	case <-time.After(3 * time.Second):
		t.Fatal("timed out: stdin reader did not exit after context deadline")
	}

	if ctx.Err() == nil {
		t.Error("expected context to be expired after timeout")
	}
}

// TestStdinFeed_FiltersGeneratedCode verifies that feedFromStdin applies
// gogenfilter filtering end-to-end: files marked as generated are excluded
// while normal Go files pass through.
func TestStdinFeed_FiltersGeneratedCode(t *testing.T) {
	tmpDir := t.TempDir()

	normalFile := filepath.Join(tmpDir, "normal.go")
	genFile := filepath.Join(tmpDir, "generated.go")

	if err := os.WriteFile(normalFile, []byte("package main\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatalf("write normalFile: %v", err)
	}

	if err := os.WriteFile(
		genFile,
		[]byte("// Code generated by sqlc. DO NOT EDIT.\npackage main\n"),
		0o600,
	); err != nil {
		t.Fatalf("write genFile: %v", err)
	}

	filterOpts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC, gogenfilter.FilterGeneric)
	if err != nil {
		t.Fatalf("WithFilterOptions: %v", err)
	}

	fltr, err := gogenfilter.NewFilter(filterOpts)
	if err != nil {
		t.Fatalf("NewFilter: %v", err)
	}

	stats := NewFilterStats(fltr.FilterReasons())

	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	if _, err := w.WriteString(normalFile + "\n"); err != nil {
		t.Fatalf("WriteString error: %v", err)
	}

	if _, err := w.WriteString(genFile + "\n"); err != nil {
		t.Fatalf("WriteString error: %v", err)
	}

	if err := w.Close(); err != nil {
		t.Fatalf("Close error: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)

	ch := feedFromStdin(ctx, r, fltr, stats, generatorIncludes{}, config.FileTypeGo)

	var got []string
	for p := range ch {
		got = append(got, p)
	}

	if len(got) != 1 {
		t.Fatalf("expected 1 file (generated filtered), got %d: %v", len(got), got)
	}

	if got[0] != normalFile {
		t.Errorf("expected %q, got %q", normalFile, got[0])
	}

	if stats.TotalFiltered() != 1 {
		t.Errorf("expected 1 filtered file, got %d", stats.TotalFiltered())
	}
}

// TestStdinFeed_StderrSuppressedOnCancel verifies that the ctx.Err()==nil guard
// suppresses scanner error output when the context is cancelled (forced reader close).
func TestStdinFeed_StderrSuppressedOnCancel(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe() error: %v", err)
	}

	t.Cleanup(func() {
		_ = w.Close()
		_ = r.Close()
	})

	origStderr := os.Stderr

	stderrR, stderrW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stderr os.Pipe() error: %v", err)
	}

	os.Stderr = stderrW

	t.Cleanup(func() {
		os.Stderr = origStderr
		_ = stderrW.Close()
		_ = stderrR.Close()
	})

	ctx, cancel := context.WithCancel(context.Background())

	ch := feedFromStdin(ctx, r, nil, nil, generatorIncludes{}, "")

	cancel()

	select {
	case _, ok := <-ch:
		if ok {
			t.Fatal("expected channel closed, got value")
		}
	case <-time.After(3 * time.Second):
		t.Fatal("timed out: stdin reader did not exit after context cancellation")
	}

	_ = stderrW.Close()

	stderrData, err := io.ReadAll(stderrR)
	if err != nil {
		t.Fatalf("reading stderr pipe: %v", err)
	}

	if len(stderrData) > 0 {
		t.Errorf("expected no stderr output on cancellation, got: %q", string(stderrData))
	}
}
