package cmd

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/art-dupl/printer"
	"github.com/LarsArtmann/art-dupl/syntax/golang"
	"github.com/LarsArtmann/gogenfilter/v3"
)

// generationMarkers are the "Code generated by X" comment prefixes used to
// identify generated code categories. gogenfilter's Is*Generated functions are
// filename-gated for SQLC/templ/protobuf, so we detect by content alone here.
const (
	sqlcMarker     = "Code generated by sqlc"
	templMarker    = "Code generated by templ"
	protobufMarker = "Code generated by protoc-gen-go"
)

// detectionMode resolves the active golang.DetectionMode from config.
func detectionMode(cfg *config.Config) golang.DetectionMode {
	switch cfg.DetectionMode {
	case config.DetectionModeSemantic:
		return golang.DetectionModeSemantic
	case config.DetectionModeExact:
		return golang.DetectionModeExact
	case config.DetectionModeStructural:
		return golang.DetectionModeStructural
	default:
		return golang.DetectionModeSemantic
	}
}

// detectionMethodsToString converts detection methods to a comma-separated string.
func detectionMethodsToString(methods config.DetectionMethods) string {
	if len(methods) == 0 {
		return ""
	}

	return strings.Join(detectionMethodsToStringSlice(methods), ",")
}

// detectionMethodsToStringSlice converts detection methods to a slice of strings.
func detectionMethodsToStringSlice(methods config.DetectionMethods) []string {
	if len(methods) == 0 {
		return nil
	}

	result := make([]string, 0, len(methods))
	for _, dm := range methods {
		result = append(result, dm.String())
	}

	return result
}

// newReportMetadata creates ReportMetadata from a Config and sort criteria string.
func newReportMetadata(cfg *config.Config, sortBy string) printer.ReportMetadata {
	return printer.ReportMetadata{
		Semantic:         cfg.DetectionMode.IsSemantic(),
		DetectionMethods: detectionMethodsToStringSlice(cfg.DetectionMethods),
		SortBy:           sortBy,
		IncludeSQLC:      cfg.IncludeSQLC,
		IncludeTempl:     cfg.IncludeTempl,
	}
}

// shouldIncludeFile returns true if the file should be included (not filtered).
// When stats is non-nil, the filter result is recorded for aggregation.
//
// The includes policy overrides FilterGeneric: a file caught only by the generic
// "Code generated by" catch-all is kept when it belongs to a category the user
// explicitly asked to include (--include-sqlc, --include-templ, ...). Without
// this, --include-sqlc would have no effect because FilterGeneric still matches
// sqlc files.
//
// When includes are active, file content is read once and passed to
// FilterDetailedWithContent (gogenfilter v3.2.0), avoiding a double read.
// When no includes are active, the standard two-phase FilterDetailed is used
// (filename check first, content read only if needed).
func shouldIncludeFile(
	f *gogenfilter.Filter,
	path string,
	stats *FilterStats,
	includes generatorIncludes,
) bool {
	if f == nil {
		return true
	}

	if !includes.any() {
		return shouldIncludeFileStandard(f, path, stats)
	}

	content, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return true
	}

	result, err := f.FilterDetailedWithContent(path, content)
	if err != nil {
		return true
	}

	if result.Filtered && result.Reason == gogenfilter.ReasonGeneric &&
		includes.allowsContent(content) {
		return true
	}

	if !result.Filtered {
		if reason, filtered := filterExcludedGenerated(content, includes); filtered {
			stats.Record(gogenfilter.FilterResult{
				Filtered: true,
				Reason:   reason,
				Path:     path,
			})
			return false
		}
	}

	stats.Record(result)

	return !result.Filtered
}

// shouldIncludeFileStandard is the no-includes path: two-phase filter, no
// upfront content read.
func shouldIncludeFileStandard(f *gogenfilter.Filter, path string, stats *FilterStats) bool {
	result, err := f.FilterDetailed(path)
	if err != nil {
		return true
	}

	stats.Record(result)

	return !result.Filtered
}

// generatorIncludes records which generated-code categories the user explicitly
// asked to include via --include-generated flags, so shouldIncludeFile can bypass
// the generic catch-all (FilterGeneric) for files belonging to an included category.
//
// The Generic field tracks whether --include-generated generic (or all) is active.
// When Generic is true, FilterGeneric is disabled, creating a gap: filename-gated
// category filters (FilterSQLC, FilterTempl, FilterProtobuf) only match files with
// the expected suffix (_sqlc.go, _templ.go, *.pb.go). A generated file without the
// suffix would slip through. The filterExcludedGenerated content check closes this gap.
type generatorIncludes struct {
	SQLC     bool
	Templ    bool
	Protobuf bool
	Mockgen  bool
	Stringer bool
	Generic  bool
}

// newGeneratorIncludes builds the policy from a config.
func newGeneratorIncludes(cfg *config.Config) generatorIncludes {
	return generatorIncludes{
		SQLC:     cfg.IncludeSQLC,
		Templ:    cfg.IncludeTempl,
		Protobuf: cfg.IncludeProtobuf,
		Mockgen:  cfg.IncludeMockgen,
		Stringer: cfg.IncludeStringer,
		Generic:  cfg.IncludeGeneric,
	}
}

func (g generatorIncludes) any() bool {
	return g.SQLC || g.Templ || g.Protobuf || g.Mockgen || g.Stringer || g.Generic
}

// allowsContent reports whether the file content indicates generation by a
// category the user explicitly asked to include. It checks the "Code generated
// by X" comment directly, bypassing gogenfilter's filename-gated Is*Generated
// functions (which require both filename AND content to match for SQLC/templ/
// protobuf). Mockgen and stringer are content-only in gogenfilter, so we
// delegate to their Is*Generated functions.
func (g generatorIncludes) allowsContent(content []byte) bool {
	c := string(content)

	switch {
	case g.SQLC && strings.Contains(c, sqlcMarker):
		return true
	case g.Templ && strings.Contains(c, templMarker):
		return true
	case g.Protobuf && strings.Contains(c, protobufMarker):
		return true
	case g.Mockgen && gogenfilter.IsMockgenGenerated("", c):
		return true
	case g.Stringer && gogenfilter.IsStringerGenerated("", c):
		return true
	default:
		return false
	}
}

// filterExcludedGenerated is a content-based defense-in-depth check for files
// that bypass gogenfilter's filename-gated category filters. When FilterGeneric
// is disabled (--include-generated generic), only filename-based detection
// remains for templ, sqlc, and protobuf (all require specific suffixes:
// _templ.go, _sqlc.go, *.pb.go). A generated file without the expected suffix
// would slip through. This function catches such files by checking content
// directly.
//
// Returns the matching FilterReason and true when the file should be filtered.
// Returns empty string and false when the file should pass (either no marker
// found, or the category is explicitly included).
func filterExcludedGenerated(content []byte, includes generatorIncludes) (gogenfilter.FilterReason, bool) {
	c := string(content)

	switch {
	case !includes.Templ && strings.Contains(c, templMarker):
		return gogenfilter.ReasonTempl, true
	case !includes.SQLC && strings.Contains(c, sqlcMarker):
		return gogenfilter.ReasonSQLC, true
	case !includes.Protobuf && strings.Contains(c, protobufMarker):
		return gogenfilter.ReasonProtobuf, true
	default:
		return "", false
	}
}
