package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/art-dupl/printer"
	"github.com/LarsArtmann/art-dupl/syntax/golang"
	"github.com/LarsArtmann/gogenfilter/v3"
)

// generationMarkers are the "Code generated by X" comment prefixes used to
// identify generated code categories. gogenfilter's Is*Generated functions are
// filename-gated for SQLC/templ/protobuf, so we detect by content alone here.
const (
	sqlcMarker     = "Code generated by sqlc"
	templMarker    = "Code generated by templ"
	protobufMarker = "Code generated by protoc-gen-go"
	// generatedHeader is the common prefix of every "Code generated by X"
	// comment. Files without it cannot be generated code, so it is used as a
	// cheap fast-path that skips the per-category marker scans and the string
	// conversion needed for mockgen/stringer detection. Inlined as
	// []byte(generatedHeader) inside bytes.Contains, which the compiler
	// stack-allocates for a constant needle.
	generatedHeader = "Code generated"
)

// detectionMode resolves the active golang.DetectionMode from config.
func detectionMode(cfg *config.Config) golang.DetectionMode {
	switch cfg.DetectionMode {
	case config.DetectionModeSemantic:
		return golang.DetectionModeSemantic
	case config.DetectionModeExact:
		return golang.DetectionModeExact
	case config.DetectionModeStructural:
		return golang.DetectionModeStructural
	default:
		return golang.DetectionModeSemantic
	}
}

// detectionMethodsToString converts detection methods to a comma-separated string.
func detectionMethodsToString(methods config.DetectionMethods) string {
	if len(methods) == 0 {
		return ""
	}

	return strings.Join(detectionMethodsToStringSlice(methods), ",")
}

// detectionMethodsToStringSlice converts detection methods to a slice of strings.
func detectionMethodsToStringSlice(methods config.DetectionMethods) []string {
	if len(methods) == 0 {
		return nil
	}

	result := make([]string, 0, len(methods))
	for _, dm := range methods {
		result = append(result, dm.String())
	}

	return result
}

// newReportMetadata creates ReportMetadata from a Config and sort criteria string.
func newReportMetadata(cfg *config.Config, sortBy string) printer.ReportMetadata {
	return printer.ReportMetadata{
		Semantic:         cfg.DetectionMode.IsSemantic(),
		DetectionMethods: detectionMethodsToStringSlice(cfg.DetectionMethods),
		SortBy:           sortBy,
		IncludeSQLC:      cfg.IncludeSQLC,
		IncludeTempl:     cfg.IncludeTempl,
	}
}

// shouldIncludeFile returns true if the file should be included (not filtered).
// When stats is non-nil, the filter result is recorded for aggregation.
//
// The includes policy overrides FilterGeneric: a file caught only by the generic
// "Code generated by" catch-all is kept when it belongs to a category the user
// explicitly asked to include (--include-sqlc, --include-templ, ...). Without
// this, --include-sqlc would have no effect because FilterGeneric still matches
// sqlc files.
//
// When includes are active, file content is read once and passed to
// FilterDetailedWithContent (gogenfilter v3.2.0), avoiding a double read.
// When no includes are active, the standard two-phase FilterDetailed is used
// (filename check first, content read only if needed).
func shouldIncludeFile(
	f *gogenfilter.Filter,
	path string,
	stats *FilterStats,
	includes generatorIncludes,
) bool {
	if f == nil {
		return true
	}

	if !includes.any() {
		return shouldIncludeFileStandard(f, path, stats)
	}

	content, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return true
	}

	result, err := f.FilterDetailedWithContent(path, content)
	if err != nil {
		return true
	}

	if result.Filtered && result.Reason == gogenfilter.ReasonGeneric &&
		includes.allowsContent(content) {
		return true
	}

	if !result.Filtered {
		if reason, filtered := filterExcludedGenerated(content, includes); filtered {
			stats.RecordWithSource(gogenfilter.FilterResult{
				Filtered: true,
				Reason:   reason,
				Path:     path,
			}, FilterSourceDefenseInDepth)

			return false
		}
	}

	stats.Record(result)

	return !result.Filtered
}

// shouldIncludeFileStandard is the no-includes path: two-phase filter, no
// upfront content read.
func shouldIncludeFileStandard(f *gogenfilter.Filter, path string, stats *FilterStats) bool {
	result, err := f.FilterDetailed(path)
	if err != nil {
		return true
	}

	stats.Record(result)

	return !result.Filtered
}

// generatorIncludes records which generated-code categories the user explicitly
// asked to include via --include-generated flags, so shouldIncludeFile can bypass
// the generic catch-all (FilterGeneric) for files belonging to an included category.
//
// The Generic field tracks whether --include-generated generic (or all) is active.
// When Generic is true, FilterGeneric is disabled, creating a gap: filename-gated
// category filters (FilterSQLC, FilterTempl, FilterProtobuf) only match files with
// the expected suffix (_sqlc.go, _templ.go, *.pb.go). A generated file without the
// suffix would slip through. The filterExcludedGenerated content check closes this gap.
type generatorIncludes struct {
	SQLC     bool
	Templ    bool
	Protobuf bool
	Mockgen  bool
	Stringer bool
	Generic  bool
}

// newGeneratorIncludes builds the policy from a config.
func newGeneratorIncludes(cfg *config.Config) generatorIncludes {
	return generatorIncludes{
		SQLC:     cfg.IncludeSQLC,
		Templ:    cfg.IncludeTempl,
		Protobuf: cfg.IncludeProtobuf,
		Mockgen:  cfg.IncludeMockgen,
		Stringer: cfg.IncludeStringer,
		Generic:  cfg.IncludeGeneric,
	}
}

func (g generatorIncludes) any() bool {
	return g.SQLC || g.Templ || g.Protobuf || g.Mockgen || g.Stringer || g.Generic
}

// matchedGeneratedCategory reports which filename-gated generation category
// (templ, sqlc, or protobuf) the content indicates, by checking the
// "Code generated by X" comment directly. It returns the matching
// gogenfilter.FilterReason and true, or "" and false for regular files.
//
// Only the three filename-gated categories are considered: gogenfilter detects
// mockgen and stringer by content alone (no filename gate), so the
// defense-in-depth gap this closes does not apply to them. The common
// "Code generated" header is checked first as a fast-path so regular files
// (the common case) never pay for the per-category marker scans.
func matchedGeneratedCategory(content []byte) (gogenfilter.FilterReason, bool) {
	if !bytes.Contains(content, []byte(generatedHeader)) {
		return "", false
	}

	switch {
	case bytes.Contains(content, []byte(templMarker)):
		return gogenfilter.ReasonTempl, true
	case bytes.Contains(content, []byte(sqlcMarker)):
		return gogenfilter.ReasonSQLC, true
	case bytes.Contains(content, []byte(protobufMarker)):
		return gogenfilter.ReasonProtobuf, true
	default:
		return "", false
	}
}

// categoryIncluded reports whether the user explicitly asked to include the
// given filename-gated category via a --include-generated flag.
func (g generatorIncludes) categoryIncluded(reason gogenfilter.FilterReason) bool {
	switch reason { //nolint:exhaustive // only filename-gated categories are relevant; default covers the rest
	case gogenfilter.ReasonTempl:
		return g.Templ
	case gogenfilter.ReasonSQLC:
		return g.SQLC
	case gogenfilter.ReasonProtobuf:
		return g.Protobuf
	default:
		return false
	}
}

// allowsContent reports whether the file content indicates generation by a
// category the user explicitly asked to include. It checks the "Code generated
// by X" comment directly, bypassing gogenfilter's filename-gated Is*Generated
// functions (which require both filename AND content to match for SQLC/templ/
// protobuf). Mockgen and stringer are content-only in gogenfilter, so we
// delegate to their Is*Generated functions.
func (g generatorIncludes) allowsContent(content []byte) bool {
	// Fast-path: no generation marker means no category can match. This also
	// avoids the string conversion below for the overwhelmingly common case of
	// a regular (non-generated) file.
	if !bytes.Contains(content, []byte(generatedHeader)) {
		return false
	}

	if reason, ok := matchedGeneratedCategory(content); ok && g.categoryIncluded(reason) {
		return true
	}

	// mockgen/stringer are content-only in gogenfilter (no filename gate), so
	// they are not part of matchedGeneratedCategory's filename-gated scope.
	c := string(content)

	return (g.Mockgen && gogenfilter.IsMockgenGenerated("", c)) ||
		(g.Stringer && gogenfilter.IsStringerGenerated("", c))
}

// filterExcludedGenerated is a content-based defense-in-depth check for files
// that bypass gogenfilter's filename-gated category filters. When FilterGeneric
// is disabled (--include-generated generic), only filename-based detection
// remains for templ, sqlc, and protobuf (all require specific suffixes:
// _templ.go, _sqlc.go, *.pb.go). A generated file without the expected suffix
// would slip through. This function catches such files by checking content
// directly.
//
// Returns the matching FilterReason and true when the file should be filtered.
// Returns empty string and false when the file should pass (either no marker
// found, or the category is explicitly included).
func filterExcludedGenerated(content []byte, includes generatorIncludes) (gogenfilter.FilterReason, bool) {
	reason, ok := matchedGeneratedCategory(content)
	if !ok || includes.categoryIncluded(reason) {
		return "", false
	}

	return reason, true
}
