package cmd

import (
	"bytes"
	"strings"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/art-dupl/printer"
	"github.com/LarsArtmann/art-dupl/syntax/golang"
	"github.com/LarsArtmann/gogenfilter/v3"
)

// generationMarkers are the "Code generated by X" comment prefixes used to
// identify generated code categories for the generic-override path
// (allowsContent). gogenfilter now handles content-only detection natively
// (v3.4.0+), so these markers are only needed to classify files caught by
// FilterGeneric into specific categories for the --include-generated override.
const (
	sqlcMarker     = "Code generated by sqlc"
	templMarker    = "Code generated by templ"
	protobufMarker = "Code generated by protoc-gen-go"
	// generatedHeader is the common prefix of every "Code generated by X"
	// comment. Files without it cannot be generated code, so it is used as a
	// cheap fast-path that skips the per-category marker scans and the string
	// conversion needed for mockgen/stringer detection. Inlined as
	// []byte(generatedHeader) inside bytes.Contains, which the compiler
	// stack-allocates for a constant needle.
	generatedHeader = "Code generated"
)

// detectionMode resolves the active golang.DetectionMode from config.
func detectionMode(cfg *config.Config) golang.DetectionMode {
	switch cfg.DetectionMode {
	case config.DetectionModeSemantic:
		return golang.DetectionModeSemantic
	case config.DetectionModeExact:
		return golang.DetectionModeExact
	case config.DetectionModeStructural:
		return golang.DetectionModeStructural
	default:
		return golang.DetectionModeSemantic
	}
}

// detectionMethodsToString converts detection methods to a comma-separated string.
func detectionMethodsToString(methods config.DetectionMethods) string {
	if len(methods) == 0 {
		return ""
	}

	return strings.Join(detectionMethodsToStringSlice(methods), ",")
}

// detectionMethodsToStringSlice converts detection methods to a slice of strings.
func detectionMethodsToStringSlice(methods config.DetectionMethods) []string {
	if len(methods) == 0 {
		return nil
	}

	result := make([]string, 0, len(methods))
	for _, dm := range methods {
		result = append(result, dm.String())
	}

	return result
}

// newReportMetadata creates ReportMetadata from a Config and sort criteria string.
func newReportMetadata(cfg *config.Config, sortBy string) printer.ReportMetadata {
	return printer.ReportMetadata{
		Semantic:         cfg.DetectionMode.IsSemantic(),
		DetectionMethods: detectionMethodsToStringSlice(cfg.DetectionMethods),
		SortBy:           sortBy,
		IncludeSQLC:      cfg.IncludeSQLC,
		IncludeTempl:     cfg.IncludeTempl,
	}
}

// shouldIncludeFile returns true if the file should be included (not filtered).
// When stats is non-nil, the filter result is recorded for aggregation.
//
// The includes policy overrides FilterGeneric: a file caught only by the generic
// "Code generated by" catch-all is kept when it belongs to a category the user
// explicitly asked to include (--include-sqlc, --include-templ, ...). Without
// this, --include-sqlc would have no effect because FilterGeneric still matches
// sqlc files.
//
// When includes are active, FilterDetailedAndContent (gogenfilter v3.4.0)
// performs a lazy content read: the file is only opened when phase-2 detection
// actually needs it (i.e., filename/pattern detection did not already decide).
// The returned content is reused for the generic-override classification,
// avoiding a double read. When no includes are active, the standard two-phase
// FilterDetailed is used (filename check first, content read only if needed).
func shouldIncludeFile(
	f *gogenfilter.Filter,
	path string,
	stats *FilterStats,
	includes generatorIncludes,
) bool {
	if f == nil {
		return true
	}

	if !includes.any() {
		return shouldIncludeFileStandard(f, path, stats)
	}

	result, content, err := f.FilterDetailedAndContent(path)
	if err != nil {
		return true
	}

	if result.Filtered && result.Reason == gogenfilter.ReasonGeneric &&
		content != nil && includes.allowsContent(content) {
		return true
	}

	stats.Record(result)

	return !result.Filtered
}

// shouldIncludeFileStandard is the no-includes path: two-phase filter, no
// upfront content read.
func shouldIncludeFileStandard(f *gogenfilter.Filter, path string, stats *FilterStats) bool {
	result, err := f.FilterDetailed(path)
	if err != nil {
		return true
	}

	stats.Record(result)

	return !result.Filtered
}

// generatorIncludes records which generated-code categories the user explicitly
// asked to include via --include-generated. Keyed by gogenfilter.FilterReason
// so that categoryIncluded is a direct map lookup (no switch needed).
// Adding a new category is now a 1-line change to newGeneratorIncludes.
type generatorIncludes map[gogenfilter.FilterReason]bool

// newGeneratorIncludes builds the policy from a config.
func newGeneratorIncludes(cfg *config.Config) generatorIncludes {
	return generatorIncludes{
		gogenfilter.ReasonSQLC:     cfg.IncludeSQLC,
		gogenfilter.ReasonTempl:    cfg.IncludeTempl,
		gogenfilter.ReasonProtobuf: cfg.IncludeProtobuf,
		gogenfilter.ReasonMockgen:  cfg.IncludeMockgen,
		gogenfilter.ReasonStringer: cfg.IncludeStringer,
		gogenfilter.ReasonGeneric:  cfg.IncludeGeneric,
	}
}

func (g generatorIncludes) any() bool {
	for _, v := range g {
		if v {
			return true
		}
	}

	return false
}

// matchedGeneratedCategory reports which generation category (templ, sqlc,
// or protobuf) the content indicates, by checking the "Code generated by X"
// comment directly. It returns the matching gogenfilter.FilterReason and true,
// or "" and false for regular files.
//
// Used by allowsContent to classify files caught by FilterGeneric into specific
// categories, so the --include-generated override can decide whether to keep them.
// The common "Code generated" header is checked first as a fast-path so regular
// files (the common case) never pay for the per-category marker scans.
func matchedGeneratedCategory(content []byte) (gogenfilter.FilterReason, bool) {
	if !bytes.Contains(content, []byte(generatedHeader)) {
		return "", false
	}

	switch {
	case bytes.Contains(content, []byte(templMarker)):
		return gogenfilter.ReasonTempl, true
	case bytes.Contains(content, []byte(sqlcMarker)):
		return gogenfilter.ReasonSQLC, true
	case bytes.Contains(content, []byte(protobufMarker)):
		return gogenfilter.ReasonProtobuf, true
	default:
		return "", false
	}
}

// categoryIncluded reports whether the user explicitly asked to include the
// given category via a --include-generated flag. Direct map lookup — no switch.
func (g generatorIncludes) categoryIncluded(reason gogenfilter.FilterReason) bool {
	return g[reason]
}

// allowsContent reports whether the file content indicates generation by a
// category the user explicitly asked to include. Used to override FilterGeneric
// for files whose content matches a specific included category. Checks the
// "Code generated by X" comment markers directly for templ/sqlc/protobuf,
// and delegates to gogenfilter's Is*Generated for mockgen/stringer (which are
// content-only in gogenfilter — no filename gate).
func (g generatorIncludes) allowsContent(content []byte) bool {
	// Fast-path: no generation marker means no category can match. This also
	// avoids the string conversion below for the overwhelmingly common case of
	// a regular (non-generated) file.
	if !bytes.Contains(content, []byte(generatedHeader)) {
		return false
	}

	if reason, ok := matchedGeneratedCategory(content); ok && g.categoryIncluded(reason) {
		return true
	}

	// mockgen/stringer are content-only in gogenfilter (no filename gate), so
	// they are not part of matchedGeneratedCategory's filename-gated scope.
	c := string(content)

	return (g[gogenfilter.ReasonMockgen] && gogenfilter.IsMockgenGenerated("", c)) ||
		(g[gogenfilter.ReasonStringer] && gogenfilter.IsStringerGenerated("", c))
}
