package provider

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/LarsArtmann/art-dupl/printer/finding"
	gofinding "github.com/larsartmann/go-finding"
	toolsdk "github.com/larsartmann/go-finding/toolsdk"
)

const toolName = finding.ToolName

const duplicatedFunction = `func processOrder(orderID string, quantity int) (int, error) {
	total := quantity * 3
	if total > 100 {
		total = total - 10
	}
	if orderID == "" {
		return 0, errors.New("empty order")
	}
	return total, nil
}
`

const renamedFunction = `func processShipment(shipmentID string, boxes int) (int, error) {
	count := boxes * 3
	if count > 100 {
		count = count - 10
	}
	if shipmentID == "" {
		return 0, errors.New("empty shipment")
	}
	return count, nil
}
`

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()

	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir for %s: %v", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func dirContext(t *testing.T, dir string) context.Context {
	t.Helper()

	return gofinding.WithWorkingDir(context.Background(), dir)
}

func TestProviderRegistersValidSpec(t *testing.T) {
	var spec *toolsdk.Spec

	for i := range toolsdk.All() {
		if toolsdk.All()[i].Name == toolName {
			spec = &toolsdk.All()[i]

			break
		}
	}

	if spec == nil {
		t.Fatalf("toolsdk registry has no %q spec; registered: %d specs", toolName, len(toolsdk.All()))
	}

	if spec.Description == "" {
		t.Error("spec Description must not be empty")
	}

	if spec.Detect == nil {
		t.Error("spec Detect must be set")
	}

	if spec.Detect != nil && spec.Detect.Name() != toolName {
		t.Errorf("Detect.Name() = %q, want %q", spec.Detect.Name(), toolName)
	}

	if len(spec.Trigger.Files) == 0 {
		t.Error("spec Trigger.Files must not be empty")
	}

	if len(spec.Inputs) == 0 {
		t.Error("spec Inputs must not be empty")
	}
}

func TestDetectFindsType1AndType2Clones(t *testing.T) {
	dir := t.TempDir()
	header := "package fixtures\n\nimport \"errors\"\n\n"

	writeFile(t, dir, "a.go", header+duplicatedFunction)
	writeFile(t, dir, "b.go", header+duplicatedFunction)
	writeFile(t, dir, "c.go", header+renamedFunction)

	findings, err := cloneDetector{}.Detect(dirContext(t, dir))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) < 3 {
		t.Fatalf("Detect returned %d findings, want >= 3 (one per occurrence): %v", len(findings), findings)
	}

	files := map[string]bool{}
	groupIDs := map[gofinding.GroupID]int{}

	for _, f := range findings {
		if f.ToolName != toolName {
			t.Errorf("finding ToolName = %q, want %q", f.ToolName, toolName)
		}

		if f.GroupID == "" {
			t.Error("finding GroupID must not be empty")
		}

		if f.Rule != gofinding.RuleName(finding.RuleCloneDetected) {
			t.Errorf("finding Rule = %q, want %q", f.Rule, finding.RuleCloneDetected)
		}

		if f.Snippet == "" {
			t.Error("finding Snippet must be populated (IncludeFragments)")
		}

		files[string(f.Position.File)] = true
		groupIDs[f.GroupID]++
	}

	for _, want := range []string{"a.go", "b.go", "c.go"} {
		if !files[want] {
			t.Errorf("no finding for %s; files seen: %v", want, files)
		}
	}
}

func TestDetectCleanRepoReturnsNoFindings(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "only.go", "package fixtures\n\nfunc unique() int { return 42 }\n")

	findings, err := cloneDetector{}.Detect(dirContext(t, dir))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) != 0 {
		t.Errorf("Detect returned %d findings on a clone-free repo, want 0", len(findings))
	}
}

func TestDetectOnEmptyWorkingDir(t *testing.T) {
	findings, err := cloneDetector{}.Detect(dirContext(t, t.TempDir()))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) != 0 {
		t.Errorf("Detect returned %d findings on an empty dir, want 0", len(findings))
	}
}

func TestCollectSourceFilesExcludesDefaults(t *testing.T) {
	dir := t.TempDir()

	writeFile(t, dir, "real.go", "package fixtures\n")
	writeFile(t, dir, "real.templ", "package templates\n\ntempl page() {\n\t<div>ok</div>\n}\n")
	writeFile(t, dir, "vendor/lib.go", "package lib\n")
	writeFile(t, dir, "node_modules/pkg.go", "package pkg\n")
	writeFile(t, dir, "examples/demo.go", "package demo\n")
	writeFile(t, dir, ".git/config", "")
	writeFile(t, dir, "generated.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
	writeFile(t, dir, "templ_page_templ.go", "// Code generated by templ. DO NOT EDIT.\n\npackage templates\n")
	writeFile(t, dir, "README.md", "# docs\n")

	files, err := collectSourceFiles(dir)
	if err != nil {
		t.Fatalf("collectSourceFiles: %v", err)
	}

	want := []string{filepath.Join(dir, "real.go"), filepath.Join(dir, "real.templ")}

	if len(files) != len(want) {
		t.Fatalf("collectSourceFiles returned %v, want %v", files, want)
	}

	for i, path := range want {
		if files[i] != path {
			t.Errorf("files[%d] = %q, want %q", i, files[i], path)
		}
	}
}

func TestProviderVersionResolvesFromDeps(t *testing.T) {
	version := providerVersion()
	if version == "" {
		t.Error("providerVersion must not return empty")
	}
}
