package provider

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/LarsArtmann/art-dupl/internal/gitignore"
	"github.com/LarsArtmann/art-dupl/printer/finding"
	gofinding "github.com/larsartmann/go-finding"
	toolsdk "github.com/larsartmann/go-finding/toolsdk"
)

const toolName = finding.ToolName

const duplicatedFunction = `func processOrder(orderID string, quantity int) (int, error) {
	total := quantity * 3
	adjusted := total + 7
	scaled := adjusted * 2
	if scaled > 100 {
		scaled = scaled - 10
	}
	if orderID == "" {
		return 0, errors.New("empty order")
	}
	normalized := scaled / 2
	finalTotal := normalized + adjusted
	return finalTotal, nil
}
`

const renamedFunction = `func processShipment(shipmentID string, boxes int) (int, error) {
	total := boxes * 3
	adjusted := total + 11
	scaled := adjusted * 2
	if scaled > 100 {
		scaled = scaled - 10
	}
	if shipmentID == "" {
		return 0, errors.New("empty shipment")
	}
	normalized := scaled / 2
	finalTotal := normalized + adjusted
	return finalTotal, nil
}
`

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()

	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir for %s: %v", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func dirContext(t *testing.T, dir string) context.Context {
	t.Helper()

	return gofinding.WithWorkingDir(context.Background(), dir)
}

func TestProviderRegistersValidSpec(t *testing.T) {
	var spec *toolsdk.Spec

	for i := range toolsdk.All() {
		if toolsdk.All()[i].Name == toolName {
			spec = &toolsdk.All()[i]

			break
		}
	}

	if spec == nil {
		t.Fatalf("toolsdk registry has no %q spec; registered: %d specs", toolName, len(toolsdk.All()))
	}

	if spec.Description == "" {
		t.Error("spec Description must not be empty")
	}

	if spec.Detect == nil {
		t.Error("spec Detect must be set")
	}

	if spec.Detect != nil && spec.Detect.Name() != toolName {
		t.Errorf("Detect.Name() = %q, want %q", spec.Detect.Name(), toolName)
	}

	if len(spec.Trigger.Files) == 0 {
		t.Error("spec Trigger.Files must not be empty")
	}

	if len(spec.Inputs) == 0 {
		t.Error("spec Inputs must not be empty")
	}
}

func TestDetectFindsType1AndType2Clones(t *testing.T) {
	dir := t.TempDir()
	header := "package fixtures\n\nimport \"errors\"\n\n"

	writeFile(t, dir, "a.go", header+duplicatedFunction)
	writeFile(t, dir, "b.go", header+duplicatedFunction)
	writeFile(t, dir, "c.go", header+renamedFunction)

	findings, err := cloneDetector{}.Detect(dirContext(t, dir))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) < 3 {
		t.Fatalf("Detect returned %d findings, want >= 3 (one per occurrence): %v", len(findings), findings)
	}

	files := map[string]bool{}
	groupIDs := map[gofinding.GroupID]int{}

	for _, f := range findings {
		if f.ToolName != toolName {
			t.Errorf("finding ToolName = %q, want %q", f.ToolName, toolName)
		}

		if f.GroupID == "" {
			t.Error("finding GroupID must not be empty")
		}

		if f.Rule != gofinding.RuleName(finding.RuleCloneDetected) {
			t.Errorf("finding Rule = %q, want %q", f.Rule, finding.RuleCloneDetected)
		}

		if f.Snippet == "" {
			t.Error("finding Snippet must be populated (IncludeFragments)")
		}

		for key, value := range f.Metadata {
			if value == "" {
				t.Errorf("finding metadata %q is empty; unclassified keys must be dropped", key)
			}
		}

		files[filepath.Base(string(f.Position.File))] = true
		groupIDs[f.GroupID]++
	}

	for _, want := range []string{"a.go", "b.go", "c.go"} {
		if !files[want] {
			t.Errorf("no finding for %s; files seen: %v", want, files)
		}
	}
}

func TestDetectCleanRepoReturnsNoFindings(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "only.go", "package fixtures\n\nfunc unique() int { return 42 }\n")

	findings, err := cloneDetector{}.Detect(dirContext(t, dir))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) != 0 {
		t.Errorf("Detect returned %d findings on a clone-free repo, want 0", len(findings))
	}
}

func TestDetectOnEmptyWorkingDir(t *testing.T) {
	findings, err := cloneDetector{}.Detect(dirContext(t, t.TempDir()))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) != 0 {
		t.Errorf("Detect returned %d findings on an empty dir, want 0", len(findings))
	}
}

func TestCollectSourceFilesExcludesDefaults(t *testing.T) {
	dir := t.TempDir()

	writeFile(t, dir, "real.go", "package fixtures\n")
	writeFile(t, dir, "real.templ", "package templates\n\ntempl page() {\n\t<div>ok</div>\n}\n")
	writeFile(t, dir, "vendor/lib.go", "package lib\n")
	writeFile(t, dir, "node_modules/pkg.go", "package pkg\n")
	writeFile(t, dir, "examples/demo.go", "package demo\n")
	writeFile(t, dir, ".git/config", "")
	writeFile(t, dir, "generated.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
	writeFile(t, dir, "templ_page_templ.go", "// Code generated by templ. DO NOT EDIT.\n\npackage templates\n")
	writeFile(t, dir, "README.md", "# docs\n")

	files, err := collectSourceFiles(dir, nil)
	if err != nil {
		t.Fatalf("collectSourceFiles: %v", err)
	}

	want := []string{filepath.Join(dir, "real.go"), filepath.Join(dir, "real.templ")}

	if len(files) != len(want) {
		t.Fatalf("collectSourceFiles returned %v, want %v", files, want)
	}

	for i, path := range want {
		if files[i] != path {
			t.Errorf("files[%d] = %q, want %q", i, files[i], path)
		}
	}
}

func TestProviderVersionResolvesFromDeps(t *testing.T) {
	version := providerVersion()
	if version == "" {
		t.Error("providerVersion must not return empty")
	}
}

func TestCapAdvisorySeverities(t *testing.T) {
	tests := []struct {
		name         string
		in           gofinding.Severity
		want         gofinding.Severity
		wantTag      bool
		wantTagValue string
	}{
		{
			"error downgraded to warning",
			gofinding.SeverityError,
			gofinding.SeverityWarning,
			true,
			"original-severity-error",
		},
		{
			"critical downgraded to warning",
			gofinding.SeverityCritical,
			gofinding.SeverityWarning,
			true,
			"original-severity-critical",
		},
		{"warning untouched", gofinding.SeverityWarning, gofinding.SeverityWarning, false, ""},
		{"info untouched", gofinding.SeverityInfo, gofinding.SeverityInfo, false, ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			findings := []gofinding.Finding{
				gofinding.NewFinding(
					"rule",
					"art-dupl",
					"msg",
					tt.in,
					gofinding.Pos("a.go", 1, 1),
					gofinding.ConfidenceNone,
				),
			}

			capAdvisorySeverities(findings)

			if findings[0].Severity != tt.want {
				t.Errorf("Severity = %q, want %q", findings[0].Severity, tt.want)
			}

			gotTag := ""

			for _, tag := range findings[0].Tags {
				if string(tag) == tt.wantTagValue {
					gotTag = string(tag)
				}
			}

			if tt.wantTag && gotTag == "" {
				t.Errorf("Tags = %v, want %q present", findings[0].Tags, tt.wantTagValue)
			}

			if !tt.wantTag && len(findings[0].Tags) != 0 {
				t.Errorf("Tags = %v, want none for untouched severity", findings[0].Tags)
			}
		})
	}
}

// TestDetectFindingsNeverExceedWarningSeverity pins the interchange contract
// regardless of threshold tuning: the provider path must never emit error or
// critical severity, because interchange consumers gate on error-or-above
// over findings nothing can auto-fix (detector-only provider).
func TestDetectFindingsNeverExceedWarningSeverity(t *testing.T) {
	dir := t.TempDir()
	header := "package fixtures\n\nimport \"errors\"\n\n"

	writeFile(t, dir, "a.go", header+duplicatedFunction)
	writeFile(t, dir, "b.go", header+duplicatedFunction)
	writeFile(t, dir, "c.go", header+renamedFunction)
	writeFile(t, dir, "d.go", header+renamedFunction)

	findings, err := cloneDetector{}.Detect(dirContext(t, dir))
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}

	if len(findings) == 0 {
		t.Fatal("Detect returned no findings; fixtures must contain clones")
	}

	for _, f := range findings {
		if f.Severity == gofinding.SeverityError || f.Severity == gofinding.SeverityCritical {
			t.Errorf(
				"finding %s carries gate-failing severity %q; SDK interchange must cap at warning",
				f.ID,
				f.Severity,
			)
		}
	}
}

func TestCollectSourceFiles_GitignorePattern(t *testing.T) {
	dir := t.TempDir()

	write := func(name, content string) {
		t.Helper()

		if err := os.WriteFile(filepath.Join(dir, filepath.FromSlash(name)), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := os.MkdirAll(filepath.Join(dir, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}

	write(".gitignore", "ignored.go\n!keep.go\n")
	write("kept.go", "package a\n")
	write("ignored.go", "package a\n")
	write("keep.go", "package a\n")
	write("sub/nested.go", "package a\n")
	write("sub/.gitignore", "nested.go\n")
	write("sub/other.go", "package a\n")

	ignore := gitignore.LoadTree(dir, io.Discard)
	if ignore == nil {
		t.Fatal("expected a matcher for the fixture's .gitignore files")
	}

	files, err := collectSourceFiles(dir, ignore)
	if err != nil {
		t.Fatalf("collectSourceFiles: %v", err)
	}

	got := make(map[string]bool, len(files))
	for _, f := range files {
		rel, relErr := filepath.Rel(dir, f)
		if relErr != nil {
			t.Fatal(relErr)
		}

		got[filepath.ToSlash(rel)] = true
	}

	for _, want := range []string{"kept.go", "keep.go", "sub/other.go"} {
		if !got[want] {
			t.Errorf("expected %s in results (kept or negated), got %v", want, files)
		}
	}

	for _, banned := range []string{"ignored.go", "sub/nested.go"} {
		if got[banned] {
			t.Errorf("%s is gitignored but was collected", banned)
		}
	}
}

func TestCollectSourceFiles_NoGitignoreFallback(t *testing.T) {
	dir := t.TempDir()

	if err := os.WriteFile(filepath.Join(dir, "a.go"), []byte("package a\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if ignore := gitignore.LoadTree(dir, io.Discard); ignore != nil {
		t.Fatal("expected nil matcher when no .gitignore exists anywhere")
	}

	files, err := collectSourceFiles(dir, nil)
	if err != nil {
		t.Fatalf("collectSourceFiles: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("nil matcher must disable the gitignore layer, got %v", files)
	}
}

func TestProviderDetect_ConcurrentSameWorkingDir(t *testing.T) {
	dir := t.TempDir()

	src := "package a\n\nfunc Alpha(items []int) int {\n\ttotal := 0\n\tscaled := 0\n\toffset := 100\n\tflag := false\n\tfor _, item := range items {\n\t\ttotal += item\n\t\tscaled += item * 2\n\t}\n\tif total > offset {\n\t\tflag = true\n\t}\n\treturn total\n}\n"

	for _, name := range []string{"a1.go", "a2.go"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	const workers = 8

	results := make(chan []gofinding.Finding, workers)
	errs := make(chan error, workers)

	for range workers {
		go func() {
			ctx := gofinding.WithWorkingDir(context.Background(), dir)

			findings, err := cloneDetector{}.Detect(ctx)
			if err != nil {
				errs <- err

				return
			}

			results <- findings
		}()
	}

	var first []gofinding.Finding

	for range workers {
		select {
		case err := <-errs:
			t.Fatalf("concurrent Detect: %v", err)
		case findings := <-results:
			if first == nil {
				first = findings
			} else if len(findings) != len(first) {
				t.Fatalf("racy Detect: got %d findings, want %d", len(findings), len(first))
			}
		case <-time.After(30 * time.Second):
			t.Fatal("timeout waiting for concurrent Detect")
		}
	}

	if len(first) == 0 {
		t.Fatal("fixture clone not detected through Provider.Detect")
	}
}

func TestFindingsFromGroups_GroupIDStableAcrossRuns(t *testing.T) {
	dir := t.TempDir()

	src := "package b\n\nfunc Beta(items []int) int {\n\ttotal := 0\n\tscaled := 0\n\toffset := 100\n\tflag := false\n\tfor _, item := range items {\n\t\ttotal += item\n\t\tscaled += item * 2\n\t}\n\tif total > offset {\n\t\tflag = true\n\t}\n\treturn total\n}\n"

	for _, name := range []string{"b1.go", "b2.go"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	ctx := toolsdk.EnsureContext(gofinding.WithWorkingDir(context.Background(), dir))

	findingsA, err := cloneDetector{}.Detect(ctx)
	if err != nil {
		t.Fatalf("detect A: %v", err)
	}

	findingsB, err := cloneDetector{}.Detect(ctx)
	if err != nil {
		t.Fatalf("detect B: %v", err)
	}

	if len(findingsA) == 0 || len(findingsA) != len(findingsB) {
		t.Fatalf("unstable finding counts: %d vs %d", len(findingsA), len(findingsB))
	}

	for i := range findingsA {
		if findingsA[i].GroupID != findingsB[i].GroupID {
			t.Fatalf("GroupID not stable at %d: %q vs %q", i, findingsA[i].GroupID, findingsB[i].GroupID)
		}
	}
}

func TestStripEmptyMetadata_DropsFullClassificationKeySet(t *testing.T) {
	findings := []gofinding.Finding{{
		// A CLI-run finding carries EVERY metadata key; the SDK path
		// zero-values Classification, so after stripEmptyMetadata the
		// classification set must be GONE while interchange keys survive.
		GroupID: "abc",
		Metadata: map[string]string{
			finding.MetadataKeyGroupSize:            "4",
			finding.MetadataKeyGroupTokens:          "16",
			finding.MetadataKeyDetectionMethod:      "semantic",
			finding.MetadataKeyCloneType:            "type-2",
			finding.MetadataKeyCategory:             "block",
			finding.MetadataKeyPriority:             "high",
			finding.MetadataKeyActionability:        "actionable",
			finding.MetadataKeyNonActionablePattern: "",
		},
	}}

	for _, key := range []string{
		finding.MetadataKeyCloneType,
		finding.MetadataKeyCategory,
		finding.MetadataKeyPriority,
		finding.MetadataKeyActionability,
		finding.MetadataKeyNonActionablePattern,
		finding.MetadataKeyGenericsCandidate,
		finding.MetadataKeyGenericsHint,
	} {
		findings[0].Metadata[key] = "" // zero-valued = what the SDK path produces
	}

	stripEmptyMetadata(findings)

	for _, key := range []string{
		finding.MetadataKeyCloneType,
		finding.MetadataKeyCategory,
		finding.MetadataKeyPriority,
		finding.MetadataKeyActionability,
		finding.MetadataKeyNonActionablePattern,
		finding.MetadataKeyGenericsCandidate,
		finding.MetadataKeyGenericsHint,
	} {
		if _, ok := findings[0].Metadata[key]; ok {
			t.Errorf("classification key %q survived stripEmptyMetadata; BuildFlow would render a ghost column", key)
		}
	}

	for _, key := range []string{
		finding.MetadataKeyGroupSize,
		finding.MetadataKeyGroupTokens,
		finding.MetadataKeyDetectionMethod,
	} {
		if findings[0].Metadata[key] == "" {
			t.Errorf("interchange key %q must survive stripEmptyMetadata", key)
		}
	}
}

func TestCollectSourceFiles_GeneratedContentFiltered(t *testing.T) {
	dir := t.TempDir()

	write := func(name, content string) {
		t.Helper()

		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// gogenfilter content-only detection (v3.4.0+): generated files are
	// caught even with unexpected filenames; hand-written files never are.
	write("weird_name.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
	write("hand_written.go", "package app\n\nfunc Run() {}\n")

	files, err := collectSourceFiles(dir, nil)
	if err != nil {
		t.Fatalf("collectSourceFiles: %v", err)
	}

	joined := strings.Join(files, ";")
	if strings.Contains(joined, "weird_name.go") {
		t.Errorf("content-generated file must be filtered, got %v", files)
	}

	if !strings.Contains(joined, "hand_written.go") {
		t.Errorf("hand-written file must survive, got %v", files)
	}
}

func TestLoadTree_SlashVariantsIgnored(t *testing.T) {
	dir := t.TempDir()

	if err := os.WriteFile(filepath.Join(dir, ".gitignore"), []byte("skipme/\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	ignore := gitignore.LoadTree(dir, io.Discard)
	if ignore == nil {
		t.Fatal("expected matcher")
	}

	inside := filepath.Join(dir, "skipme", "a.go")

	if !ignore.IsIgnored(inside) {
		t.Errorf("native-separator path under dir-only pattern must be ignored: %s", inside)
	}

	forward := dir + "/skipme/a.go"

	if !ignore.IsIgnored(forward) {
		t.Errorf("forward-slash path under dir-only pattern must be ignored: %s", forward)
	}
}

func TestDetect_MultiModuleWorkspaceShape(t *testing.T) {
	dir := t.TempDir()

	write := func(rel, content string) {
		t.Helper()

		path := filepath.Join(dir, filepath.FromSlash(rel))

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Three modules plus workspace scaffolding.
	for _, mod := range []string{"mod-a", "mod-b", "mod-c"} {
		write(mod+"/go.mod", "module example.com/"+mod+"\n\ngo 1.27\n")
	}

	// Cross-module clone pair: identical 6-statement bodies in mod-a and
	// mod-b (function names differ — package-level API surface).

	cloneBody := "package %s\n\nfunc Process%s(items []int) int {\n\ttotal := 0\n\tscaled := 0\n\toffset := 100\n\tflag := false\n\tfor _, item := range items {\n\t\ttotal += item\n\t\tscaled += item * 2\n\t}\n\tif total > offset {\n\t\tflag = true\n\t}\n\treturn total\n}\n"

	write("mod-a/clone.go", fmt.Sprintf(cloneBody, "a", "A"))
	write("mod-b/clone.go", fmt.Sprintf(cloneBody, "b", "B"))
	// mod-c: a templ file (parsed structurally) and a unique Go file.
	write("mod-c/page.templ", "package c\n\ntempl page() {\n\t<div>unique</div>\n}\n")
	write("mod-c/unique.go", "package c\n\nfunc UniqueC() int { return 7 }\n")

	// Noise that must NOT reach detection: vendor copy of the clone,
	// generated file, dot-dir file.
	write("mod-a/vendor/example.com/mod-b/clone.go", fmt.Sprintf(cloneBody, "b", "B"))
	write("mod-b/gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage b\n")
	write(".hidden/skip.go", "package h\n")

	ctx := toolsdk.EnsureContext(gofinding.WithWorkingDir(context.Background(), dir))

	findings, err := cloneDetector{}.Detect(ctx)
	if err != nil {
		t.Fatalf("detect: %v", err)
	}

	var crossModule bool

	for _, f := range findings {
		if strings.Contains(string(f.Position.File), "mod-a") {
			crossModule = true
		}

		for _, loc := range f.Related {
			if strings.Contains(string(loc.Position.File), "mod-b") {
				crossModule = true
			}
		}

		if strings.Contains(string(f.Position.File), "vendor/") ||
			strings.Contains(string(f.Position.File), ".hidden") ||
			strings.Contains(string(f.Position.File), "gen.go") {
			t.Errorf("finding reaches excluded file: %s", f.Position.File)
		}
	}

	if !crossModule {
		t.Fatalf("cross-module clone not detected; findings: %+v", findings)
	}
}
