package printer

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/art-dupl/domain"
)

// classificationStats tracks counts for HTML summary.
type classificationStats struct {
	categoryCounts map[CloneCategory]int
	priorityCounts map[ClonePriority]int
	testCount      int
	prodCount      int
	totalClones    int
	totalTokens    int
}

// ReportMetadata contains CLI settings used for the report.
type ReportMetadata struct {
	Semantic         bool
	DetectionMethods []string
	SortBy           string
	IncludeSQLC      bool
	IncludeTempl     bool
}

// htmlprinter generates HTML output for code duplication reports.
// mu guards all mutable per-run state mutated by PrintClones (iota, dupls,
// stats) so concurrent PrintClones calls stay race-free; the writer itself
// remains caller-serialized.
type htmlprinter struct {
	ReadFile

	iota             int
	w                io.Writer
	threshold        int
	mu               sync.Mutex
	dupls            [][]domain.ProcessedClone
	diffMode         config.DiffMode
	stats            classificationStats
	metadata         ReportMetadata
	suppressionStats SuppressionStats
}

// NewHTML creates a new HTML printer.
// Supports optional threshold parameter (default: 15).
func NewHTML(w io.Writer, fread ReadFile, threshold ...int) Printer {
	return NewHTMLWithOptions(w, fread, config.DiffModeDisabled, ReportMetadata{}, threshold...)
}

// NewHTMLWithOptions creates a new HTML printer with full options.
// diffMode enables visual diff highlighting between duplicate occurrences.
// metadata contains CLI settings to display in the report.
func NewHTMLWithOptions(
	w io.Writer,
	fread ReadFile,
	diffMode config.DiffMode,
	metadata ReportMetadata,
	threshold ...int,
) Printer {
	thresh := 15
	if len(threshold) > 0 {
		thresh = threshold[0]
	}

	return &htmlprinter{
		w:         w,
		ReadFile:  fread,
		threshold: thresh,
		dupls:     make([][]domain.ProcessedClone, 0),
		diffMode:  diffMode,
		stats: classificationStats{
			categoryCounts: make(map[CloneCategory]int),
			priorityCounts: make(map[ClonePriority]int),
		},
		metadata: metadata,
	}
}

func (p *htmlprinter) PrintHeader() error {
	if _, err := fmt.Fprintf(p.w, htmlTemplate, p.threshold); err != nil {
		return err
	}

	return p.writeMetadata()
}

func (p *htmlprinter) writeMetadata() error {
	metaStr := buildMetadataBadgesHTML(p.metadata)
	if metaStr == "" {
		return nil
	}

	_, err := fmt.Fprintf(
		p.w,
		`<script>document.getElementById('report-metadata').innerHTML = %s;</script>`,
		strconv.Quote(metaStr),
	)

	return err
}

// cloneGroupErr wraps an error with "op for clone group #N (hash: H)" context.

func (p *htmlprinter) PrintClones(
	group domain.ProcessedCloneGroup,
	sortBy ...config.SortCriteria,
) error {
	clones := SortGroupClones(group, sortBy...)

	// All mutated per-run state is guarded by mu — previously only dupls was
	// locked while iota and stats mutated unguarded next to it, a mixed-access
	// race if PrintClones ever ran concurrently.
	p.mu.Lock()
	p.iota++
	p.dupls = append(p.dupls, clones)

	for _, cl := range clones {
		p.stats.categoryCounts[cl.Classification.Category]++
		p.stats.priorityCounts[cl.Classification.Priority]++

		if cl.Classification.IsTest {
			p.stats.testCount++
		} else {
			p.stats.prodCount++
		}

		p.stats.totalClones++
		p.stats.totalTokens += cl.Classification.Tokens
	}

	groupIndex := p.iota
	p.mu.Unlock()

	sort.Sort(byNameAndLineProcessed(clones))
	viewData := toCloneGroupView(groupIndex, group.Hash, clones)

	ctx := context.Background()

	if p.diffMode.IsEnabled() && len(clones) > 1 {
		groupDiff := ComputeCloneGroupDiff(clones)
		diffData := toDiffView(groupIndex, groupDiff)

		if len(groupDiff.Others) == 0 {
			return cloneGroupFull(viewData).Render(ctx, p.w)
		}

		return cloneGroupDiffFull(viewData, diffData).Render(ctx, p.w)
	}

	return cloneGroupFull(viewData).Render(ctx, p.w)
}

func (p *htmlprinter) buildSummarySection() string {
	if p.stats.totalClones == 0 && !p.hasSuppression() {
		return ""
	}

	return buildSummaryHTML(toSummaryView(p.stats, p.suppressionStats))
}

// hasSuppression reports whether any clone group was suppressed from output.
func (p *htmlprinter) hasSuppression() bool {
	s := p.suppressionStats

	return s.DetectedTotal > 0 && s.DetectedTotal > s.Shown
}

// SetSuppressionStats implements SuppressionStatsSetter so the HTML summary
// shows the detected-vs-actionable breakdown, mirroring the text footer.
func (p *htmlprinter) SetSuppressionStats(stats SuppressionStats) {
	p.suppressionStats = stats
}

func (p *htmlprinter) PrintFooter() error {
	summary := p.buildSummarySection()

	_, err := fmt.Fprint(p.w, summary+`
</div>
<footer>
<p>Generated by art-dupl · Code Duplication Detection Tool</p>
</footer>
<script>
function copyCode(elementId) {
	const code = document.getElementById(elementId).innerText;
	navigator.clipboard.writeText(code).then(() => {
		const btn = event.target;
		const original = btn.innerText;
		btn.innerText = '✓ Copied!';
		setTimeout(() => btn.innerText = original, 2000);
	});
}
function showDiff(index, groupId) {
	const comparisons = document.querySelectorAll('[id^="diff-compare-' + groupId + '-"]');
	comparisons.forEach(function(comp) {
		comp.classList.remove('active');
	});
	const selected = document.getElementById('diff-compare-' + groupId + '-' + index);
	if (selected) {
		selected.classList.add('active');
	}
}

function toggleDiffView(groupId, mode) {
	const comparisons = document.querySelectorAll('[id^="diff-compare-' + groupId + '-"]');
	comparisons.forEach(function(comp) {
		const content = comp.querySelector('.diff-content');
		if (content) {
			if (mode === 'inline') {
				content.classList.add('inline');
			} else {
				content.classList.remove('inline');
			}
		}
	});

	const buttons = document.querySelectorAll('[id^="diff-toggle-' + groupId + '-"]');
	buttons.forEach(function(btn) {
		btn.classList.remove('active');
		if (btn.dataset.mode === mode) {
			btn.classList.add('active');
		}
	});

	try {
		localStorage.setItem('artdupl-diff-mode', mode);
	} catch (e) {
	}
}

function filterClones(filter) {
	document.querySelectorAll('.filter-btn').forEach(function(btn) {
		btn.classList.remove('active');
		if (btn.dataset.filter === filter) {
			btn.classList.add('active');
		}
	});

	document.querySelectorAll('.clone-group').forEach(function(group) {
		if (filter === 'all') {
			group.style.display = '';
		} else if (filter === 'prod') {
			group.style.display = group.dataset.test === 'false' ? '' : 'none';
		} else if (filter === 'test') {
			group.style.display = group.dataset.test === 'true' ? '' : 'none';
		} else if (filter.startsWith('cat-')) {
			var cat = filter.substring(4);
			group.style.display = group.dataset.category === cat ? '' : 'none';
		}
	});
}

function collapseAll(collapse) {
	document.querySelectorAll('.clone-group').forEach(function(group) {
		if (collapse) {
			group.classList.add('collapsed');
		} else {
			group.classList.remove('collapsed');
		}
	});
}

document.addEventListener('DOMContentLoaded', function() {
	try {
		const savedMode = localStorage.getItem('artdupl-diff-mode');
		if (savedMode === 'inline') {
			const allContents = document.querySelectorAll('.diff-content');
			allContents.forEach(function(content) {
				content.classList.add('inline');
			});
			const allToggles = document.querySelectorAll('.diff-view-toggle button');
			allToggles.forEach(function(btn) {
				btn.classList.remove('active');
				if (btn.dataset.mode === 'inline') {
					btn.classList.add('active');
				}
			});
		}
	} catch (e) {
	}

	var summary = document.querySelector('.summary-section');
	var statsGrid = document.querySelector('.stats-grid');
	if (summary && statsGrid) {
		statsGrid.parentNode.insertBefore(summary, statsGrid.nextSibling);
	}
});
</script>
</body>
</html>
`)

	return err
}

// OutputHTML generates HTML output with sorting.
func (p *htmlprinter) OutputHTML(threshold int, sortBy config.SortCriteria) error {
	var allClones []domain.ProcessedClone

	p.mu.Lock()
	for i := range len(p.dupls) {
		allClones = append(allClones, p.dupls[i]...)
	}

	p.iota = 0
	p.mu.Unlock()

	SortProcessedClonesByCriteria(allClones, sortBy)

	for _, cl := range allClones {
		err := p.PrintClones(
			domain.NewProcessedCloneGroup("", []domain.ProcessedClone{cl}),
			sortBy,
		)
		if err != nil {
			return fmt.Errorf(
				"output HTML (threshold: %d, sortBy: %s): %w",
				threshold,
				sortBy.String(),
				err,
			)
		}
	}

	return nil
}

// priorityHigher returns true if p1 is higher priority than p2.
func priorityHigher(p1, p2 ClonePriority) bool {
	return p1.Rank() > p2.Rank()
}

func suggestionHTML(suggestion string) string {
	if suggestion == "" {
		return ""
	}

	return fmt.Sprintf(`<div class="suggestion">💡 %s</div>`, strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&#34;",
		"'", "&#39;",
	).Replace(suggestion))
}

// writeCloneOccurrences renders clone occurrences (non-diff mode) using templ.
func (p *htmlprinter) writeCloneOccurrences(clones []domain.ProcessedClone) error {
	for i, cl := range clones {
		occData := toCloneOccurrenceView(cl)

		err := cloneOccurrence(
			occData,
			p.iota,
			i,
		).Render(context.Background(), p.w)
		if err != nil {
			return err
		}
	}

	return nil
}

func (p *htmlprinter) writeCloneGroupFooter() error {
	_, err := fmt.Fprint(p.w, "</div></div>\n")

	return err
}
