package printer

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/LarsArtmann/art-dupl/config"
	"github.com/LarsArtmann/art-dupl/syntax"
)

func (p *htmlprinter) buildSummarySection() string {
	if p.stats.totalClones == 0 {
		return ""
	}

	var sb strings.Builder

	// Summary section header
	sb.WriteString(`<div class="summary-section">`)
	sb.WriteString(`<h2>📊 Summary</h2>`)

	// Overview stats
	sb.WriteString(`<div class="summary-grid">`)
	sb.WriteString(
		`<div class="summary-item"><span class="summary-label">Total Clones</span><span class="summary-value">`,
	)
	sb.WriteString(strconv.Itoa(p.stats.totalClones))
	sb.WriteString(`</span></div>`)
	sb.WriteString(
		`<div class="summary-item"><span class="summary-label">Total Tokens</span><span class="summary-value">`,
	)
	sb.WriteString(strconv.Itoa(p.stats.totalTokens))
	sb.WriteString(`</span></div>`)
	sb.WriteString(
		`<div class="summary-item"><span class="summary-label">Production</span><span class="summary-value">`,
	)
	sb.WriteString(strconv.Itoa(p.stats.prodCount))
	sb.WriteString(`</span></div>`)
	sb.WriteString(
		`<div class="summary-item"><span class="summary-label">Test Code</span><span class="summary-value">`,
	)
	sb.WriteString(strconv.Itoa(p.stats.testCount))
	sb.WriteString(`</span></div>`)
	sb.WriteString(`</div>`)

	// Category breakdown
	if len(p.stats.categoryCounts) > 0 {
		sb.WriteString(
			`<div class="summary-category"><h3>By Category</h3><div class="category-list">`,
		)

		for _, cat := range orderedCategories() {
			if count := p.stats.categoryCounts[cat]; count > 0 {
				sb.WriteString(`<span class="category-tag">`)
				sb.WriteString(cat.GetCategoryEmoji())
				sb.WriteString(" ")
				sb.WriteString(string(cat))
				sb.WriteString(": ")
				sb.WriteString(strconv.Itoa(count))
				sb.WriteString(`</span>`)
			}
		}

		sb.WriteString(`</div></div>`)
	}

	// Priority breakdown
	if len(p.stats.priorityCounts) > 0 {
		sb.WriteString(
			`<div class="summary-category"><h3>By Priority</h3><div class="priority-list">`,
		)

		for _, pri := range orderedPriorities() {
			if count := p.stats.priorityCounts[pri]; count > 0 {
				sb.WriteString(`<span class="priority-tag priority-`)
				sb.WriteString(string(pri))
				sb.WriteString(`">`)
				sb.WriteString(pri.GetPriorityEmoji())
				sb.WriteString(" ")
				sb.WriteString(string(pri))
				sb.WriteString(": ")
				sb.WriteString(strconv.Itoa(count))
				sb.WriteString(`</span>`)
			}
		}

		sb.WriteString(`</div></div>`)
	}

	// Filter buttons
	sb.WriteString(`<div class="filter-buttons"><h3>Filters</h3>`)
	sb.WriteString(
		`<button class="filter-btn active" data-filter="all" onclick="filterClones('all')">All</button>`,
	)
	sb.WriteString(
		`<button class="filter-btn" data-filter="prod" onclick="filterClones('prod')">📦 Production</button>`,
	)
	sb.WriteString(
		`<button class="filter-btn" data-filter="test" onclick="filterClones('test')">🧪 Test</button>`,
	)
	sb.WriteString(`<span class="filter-separator">|</span>`)

	for _, cat := range orderedCategories() {
		sb.WriteString(`<button class="filter-btn" data-filter="cat-`)
		sb.WriteString(string(cat))
		sb.WriteString(`" onclick="filterClones('cat-`)
		sb.WriteString(string(cat))
		sb.WriteString(`')">`)
		sb.WriteString(cat.GetCategoryEmoji())
		sb.WriteString(`</button>`)
	}

	sb.WriteString(`</div>`)
	sb.WriteString(`</div>`)

	return sb.String()
}

// orderedCategories returns categories in a stable order for display.
func orderedCategories() []CloneCategory {
	return []CloneCategory{
		CategoryFunction,
		CategoryMethod,
		CategoryHandler,
		CategoryStruct,
		CategoryInterface,
		CategoryLoop,
		CategoryConditional,
		CategoryAssignment,
		CategoryExpression,
		CategoryTest,
		CategoryUnknown,
	}
}

// orderedPriorities returns priorities in a stable order for display.
func orderedPriorities() []ClonePriority {
	return []ClonePriority{
		PriorityCritical,
		PriorityHigh,
		PriorityMedium,
		PriorityLow,
	}
}

func (p *htmlprinter) PrintFooter() error {
	summary := p.buildSummarySection()

	_, err := fmt.Fprint(p.w, summary+`
</div>
<footer>
<p>Generated by art-dupl · Code Duplication Detection Tool</p>
</footer>
<script>
function copyCode(elementId) {
	const code = document.getElementById(elementId).innerText;
	navigator.clipboard.writeText(code).then(() => {
		const btn = event.target;
		const original = btn.innerText;
		btn.innerText = '✓ Copied!';
		setTimeout(() => btn.innerText = original, 2000);
	});
}
function showDiff(index, groupId) {
	// Hide all diff comparisons for this group
	const comparisons = document.querySelectorAll('[id^="diff-compare-' + groupId + '-"]');
	comparisons.forEach(function(comp) {
		comp.classList.remove('active');
	});
	// Show selected comparison
	const selected = document.getElementById('diff-compare-' + groupId + '-' + index);
	if (selected) {
		selected.classList.add('active');
	}
}

// Diff view mode toggle: side-by-side vs inline
function toggleDiffView(groupId, mode) {
	const comparisons = document.querySelectorAll('[id^="diff-compare-' + groupId + '-"]');
	comparisons.forEach(function(comp) {
		const content = comp.querySelector('.diff-content');
		if (content) {
			if (mode === 'inline') {
				content.classList.add('inline');
			} else {
				content.classList.remove('inline');
			}
		}
	});

	// Update toggle button states
	const buttons = document.querySelectorAll('[id^="diff-toggle-' + groupId + '-"]');
	buttons.forEach(function(btn) {
		btn.classList.remove('active');
		if (btn.dataset.mode === mode) {
			btn.classList.add('active');
		}
	});

	// Save preference
	try {
		localStorage.setItem('artdupl-diff-mode', mode);
	} catch (e) {
		// Ignore localStorage errors
	}
}

// Filter clones by test/prod or category
function filterClones(filter) {
	// Update active button state
	document.querySelectorAll('.filter-btn').forEach(function(btn) {
		btn.classList.remove('active');
		if (btn.dataset.filter === filter) {
			btn.classList.add('active');
		}
	});

	// Filter clone groups
	document.querySelectorAll('.clone-group').forEach(function(group) {
		if (filter === 'all') {
			group.style.display = '';
		} else if (filter === 'prod') {
			group.style.display = group.dataset.test === 'false' ? '' : 'none';
		} else if (filter === 'test') {
			group.style.display = group.dataset.test === 'true' ? '' : 'none';
		} else if (filter.startsWith('cat-')) {
			var cat = filter.substring(4);
			group.style.display = group.dataset.category === cat ? '' : 'none';
		}
	});
}

// Initialize diff view mode from saved preference
document.addEventListener('DOMContentLoaded', function() {
	try {
		const savedMode = localStorage.getItem('artdupl-diff-mode');
		if (savedMode === 'inline') {
			// Apply inline mode to all diff comparisons
			const allContents = document.querySelectorAll('.diff-content');
			allContents.forEach(function(content) {
				content.classList.add('inline');
			});
			// Update all toggle buttons
			const allToggles = document.querySelectorAll('.diff-view-toggle button');
			allToggles.forEach(function(btn) {
				btn.classList.remove('active');
				if (btn.dataset.mode === 'inline') {
					btn.classList.add('active');
				}
			});
		}
	} catch (e) {
		// Ignore localStorage errors
	}

	// Move summary section to top (after header)
	var summary = document.querySelector('.summary-section');
	var statsGrid = document.querySelector('.stats-grid');
	if (summary && statsGrid) {
		statsGrid.parentNode.insertBefore(summary, statsGrid.nextSibling);
	}
});
</script>
</body>
</html>
`)

	return err
}

// OutputHTML generates HTML output with sorting.
func (p *htmlprinter) OutputHTML(threshold int, sortBy config.SortCriteria) error {
	// Store clones for sorting - flatten the 3D structure to 2D
	var allDups [][]*syntax.Node

	p.dupMutex.Lock()
	for i := range len(p.dupls) {
		// p.dupls[i] is [][]*syntax.Node, add each clone group to allDups
		for j := range len(p.dupls[i]) {
			allDups = append(allDups, p.dupls[i][j])
		}
	}
	p.dupMutex.Unlock()

	// Apply sorting based on the specified criteria
	// Apply sorting based on specified criteria
	allDups = SortNodesByCriteria(allDups, sortBy)

	// Clear previous output
	p.iota = 0

	// Print sorted clones
	for _, dup := range allDups {
		err := p.PrintClones([][]*syntax.Node{dup}, sortBy)
		if err != nil {
			return err
		}
	}

	return nil
}
