package bdd

import (
	"github.com/LarsArtmann/art-dupl/internal/testutil"
	. "github.com/onsi/ginkgo/v2"
)

var _ = Describe("Additional Filter Categories", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = CreateBDDTestSetup()
	})

	Context("When analyzing code with protobuf generated files", func() {
		It("should exclude .pb.go files by default", func() {
			pbCode := `// Code generated by protoc-gen-go. DO NOT EDIT.
package pb
func process() { println(1) }`

			assertGenFileFiltered(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"api.pb.go",
				pbCode,
				"3",
			)
		})

		It("should include .pb.go files when --include-protobuf is used", func() {
			pbCode := `// Code generated by protoc-gen-go. DO NOT EDIT.
package pb
func process() { println(1) }`

			assertGeneratedFileIncluded(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"api.pb.go",
				pbCode,
				"--include-protobuf",
				"3",
			)
		})
	})

	Context("When analyzing code with mockgen generated files", func() {
		It("should exclude mockgen files by default", func() {
			mockCode := `// Code generated by MockGen. DO NOT EDIT.
package mocks
func process() { println(1) }`

			assertGenFileFiltered(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"mock_service.go",
				mockCode,
				"3",
			)
		})

		It("should include mockgen files when --include-mockgen is used", func() {
			mockCode := `// Code generated by MockGen. DO NOT EDIT.
package mocks
func process() { println(1) }`

			assertGeneratedFileIncluded(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"mock_service.go",
				mockCode,
				"--include-mockgen",
				"3",
			)
		})
	})

	Context("When analyzing code with stringer generated files", func() {
		// Content-based detection (stringer/generic) may not work with
		// absolute paths due to os.DirFS(".") default in gogenfilter.
		// These tests are pending until the FS issue is resolved.
		PIt("should exclude stringer files by default", func() {
			// Note: stringer detection is content-based and requires file path
			// resolution through the filter's FS, which may not work with
			// absolute paths. This test documents the current behavior.
			stringerCode := `// Code generated by "stringer" -type=Status
package status
func process() { println(1) }`

			assertGenFileFiltered(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"status_string.go",
				stringerCode,
				"3",
			)
		})

		PIt("should include stringer files when --include-stringer is used", func() {
			stringerCode := `// Code generated by "stringer" -type=Status
package status
func process() { println(1) }`

			assertGeneratedFileIncluded(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"status_string.go",
				stringerCode,
				"--include-stringer",
				"3",
			)
		})
	})

	Context("When analyzing code with generic generated files", func() {
		// Content-based detection (stringer/generic) may not work with
		// absolute paths due to os.DirFS(".") default in gogenfilter.
		// These tests are pending until the FS issue is resolved.
		PIt("should exclude files with Code generated comments by default", func() {
			// Note: generic detection is content-based and requires file path
			// resolution through the filter's FS, which may not work with
			// absolute paths. This test documents the current behavior.
			genericCode := `// Code generated by custom-tool. DO NOT EDIT.
package gen
func process() { println(1) }`

			assertGenFileFiltered(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"generated.go",
				genericCode,
				"3",
			)
		})

		PIt("should include generic generated files when --include-generic is used", func() {
			genericCode := `// Code generated by custom-tool. DO NOT EDIT.
package gen
func process() { println(1) }`

			assertGeneratedFileIncluded(
				setup,
				[]string{serviceFile1, serviceFile2},
				testRegularCode,
				"generated.go",
				genericCode,
				"--include-generic",
				"3",
			)
		})
	})
})
