package bdd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
)

// testCodeSamples contains code samples used in configuration tests.
const (
	simpleTestCode = `package main
func test() {}`
	multiConfigTestCode = `package main
func multiConfig() {}`
	pathTestCode = `package main
func pathTest() {}`
	overrideTestCode = `package main
func overrideTest() {}`
	formatOverrideTestCode = `package main
func formatOverride() string {
	return "test"
}`
	malformedTestCode = `package main
func malformedTest() {}`
	missingConfigCode = `package main
func missingConfig() {}`
	invalidTypeCode = `package main
func invalidType() {}`
	detectionMethodCode = `package main
func detectionMethod() string {
	return "test"
}`
	singleMethodCode = `package main
func singleMethod() string {
	return "hash only"
}`
	filterGenCode = `package main
func filterGen() {}`
	sqlcCode = `// Code generated by sqlc. DO NOT EDIT.
package db
func SQLCQuery() {}`
	templCode = `package components
import "github.com/a-h/templ"
func TemplComponent() templ.Component {
	return nil
}`
	statsConfigCode = `package main
func statsConfig() {}`
	emptyConfigCode = `package main
func emptyConfig() {}`
	whitespaceConfigCode = `package main
func whitespaceConfig() {}`
	unknownFieldCode = `package main
func unknownField() {}`
	nestedConfigCode = `package main
func nestedConfig() {}`
	unicodeConfigCode = `package main
func unicodeConfig() {}`
)

// BDD Test Suite for Configuration File Handling
//
// These tests verify configuration file loading and parsing behavior,
// including JSON configuration support and command-line overrides.
//
// The scenarios cover:
// - Loading configuration from JSON files
// - Configuration precedence (CLI flags override config file)
// - Invalid configuration handling
// - Configuration validation

// newBDDTestSetup creates a new BDDTestSetup and registers cleanup for Ginkgo tests.
func newBDDTestSetup() *testutil.BDDTestSetup {
	setup, err := testutil.NewBDDTestSetupForGinkgo()
	Expect(err).NotTo(HaveOccurred())
	DeferCleanup(func() {
		Expect(setup.Cleanup()).NotTo(HaveOccurred())
	})

	return setup
}

var _ = Describe("Configuration File Loading", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = newBDDTestSetup()
	})

	// runWithConfig creates a config file, test files, and runs art-dupl
	runWithConfig := func(configContent, code string, fileNames []string) ([]byte, error) {
		return setup.RunWithConfigFile("dupl.json", configContent, code, fileNames)
	}

	Context("When using a valid JSON configuration file", func() {
		It("should load threshold from config file", func() {
			configContent := `{
				"threshold": 50,
				"outputFormat": "json"
			}`
			output, err := runWithConfig(
				configContent,
				simpleTestCode,
				[]string{"test1.go", "test2.go"},
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})

		It("should load multiple settings from config file", func() {
			configContent := `{
				"threshold": 20,
				"outputFormat": "json",
				"vendor": true,
				"verbose": true
			}`
			output, err := runWithConfig(
				configContent,
				multiConfigTestCode,
				[]string{"multi1.go", "multi2.go"},
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})

		It("should load paths from config file", func() {
			// Create subdirectories
			err := setup.CreateSubdirectories("src", "lib")
			Expect(err).NotTo(HaveOccurred())

			// Create config with paths
			configContent := `{
				"threshold": 15,
				"paths": ["./src", "./lib"]
			}`
			configPath := filepath.Join(setup.TmpDir, "dupl.json")
			err = os.WriteFile(configPath, []byte(configContent), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Create test files in subdirectories
			err = setup.CreateFileWithContent("src/file.go", pathTestCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateFileWithContent("lib/file.go", pathTestCode)
			Expect(err).NotTo(HaveOccurred())

			// Change to temp directory so relative paths work
			originalDir, _ := os.Getwd()

			defer func() { _ = os.Chdir(originalDir) }() // test cleanup

			_ = os.Chdir(setup.TmpDir) // test setup

			// Run with config file (uses paths from config)
			output, err := setup.RunArtDupl("--config", configPath)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})
	})

	Context("When CLI flags override config file settings", func() {
		It("should use CLI threshold over config threshold", func() {
			configContent := `{
				"threshold": 50
			}`
			output, err := runWithConfig(
				configContent,
				overrideTestCode,
				[]string{"override1.go", "override2.go"},
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})

		It("should use CLI output format over config format", func() {
			configContent := `{
				"threshold": 15,
				"outputFormat": "text"
			}`
			// Create config file manually
			configPath := filepath.Join(setup.TmpDir, "dupl.json")
			err := os.WriteFile(configPath, []byte(configContent), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Create test files
			err = setup.CreateDuplicateFiles([]string{"fmt1.go", "fmt2.go"}, formatOverrideTestCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with --json flag to override config
			output, err := setup.RunArtDupl("--config", configPath, "--json", setup.TmpDir)
			Expect(err).ToNot(HaveOccurred())

			// Verify JSON output
			var result map[string]any

			err = json.Unmarshal(output, &result)
			Expect(err).ToNot(HaveOccurred())
			Expect(result).To(HaveKey("clone_groups"))
		})
	})

	Context("When configuration file has invalid format", func() {
		It("should handle malformed JSON gracefully", func() {
			configContent := `{ invalid json content }`
			output, err := runWithConfig(
				configContent,
				malformedTestCode,
				[]string{"malformed1.go", "malformed2.go"},
			)
			Expect(err).To(HaveOccurred())
			Expect(string(output)).To(ContainSubstring("error"))
		})

		It("should handle missing config file gracefully", func() {
			configPath := filepath.Join(setup.TmpDir, "nonexistent.json")
			err := setup.CreateDuplicateFiles(
				[]string{"missing1.go", "missing2.go"},
				missingConfigCode,
			)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--config", configPath, setup.TmpDir)
			Expect(err).To(HaveOccurred())
			Expect(string(output)).ToNot(BeEmpty())
		})

		It("should handle config with invalid field types", func() {
			configContent := `{
				"threshold": "not a number",
				"outputFormat": 12345
			}`
			output, err := runWithConfig(
				configContent,
				invalidTypeCode,
				[]string{"invalid1.go", "invalid2.go"},
			)
			_ = err

			Expect(output).ToNot(BeNil())
		})
	})

	Context("When configuration file has detection method settings", func() {
		It("should load detection methods from config", func() {
			configContent := `{
				"threshold": 15,
				"detectionMethods": ["hash", "art-dupl"]
			}`
			output, err := runWithConfig(
				configContent,
				detectionMethodCode,
				[]string{"detect1.go", "detect2.go"},
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})

		It("should load single detection method from config", func() {
			configContent := `{
				"threshold": 15,
				"detectionMethods": ["hash"]
			}`
			output, err := runWithConfig(
				configContent,
				singleMethodCode,
				[]string{"single1.go", "single2.go"},
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})
	})

	// runConfigTest is a helper to run config tests with standard validation
	runConfigTest := func(configContent, code string, fileNames []string) {
		output, err := runWithConfig(configContent, code, fileNames)
		Expect(err).ToNot(HaveOccurred())
		Expect(output).ToNot(BeNil())
	}

	Context("When configuration file has filtering settings", func() {
		It("should load filter-generated setting from config", func() {
			configContent := `{
				"threshold": 15,
				"filterGenerated": true
			}`
			runConfigTest(configContent, filterGenCode, []string{"filter1.go", "filter2.go"})
		})

		It("should load include-sqlc setting from config", func() {
			configContent := `{
				"threshold": 15,
				"filterGenerated": true,
				"includeSqlc": true
			}`
			runConfigTest(configContent, sqlcCode, []string{"query1.go", "query2.go"})
		})

		It("should load include-templ setting from config", func() {
			configContent := `{
				"threshold": 15,
				"filterGenerated": true,
				"includeTempl": true
			}`
			runConfigTest(configContent, templCode, []string{"comp1.go", "comp2.go"})
		})
	})

	// runPatternTest is a helper to run pattern-based config tests
	runPatternTest := func(dir1, dir2, patternType, patternValue, funcName string) {
		err := setup.CreateSubdirectories(dir1, dir2)
		Expect(err).NotTo(HaveOccurred())

		configContent := fmt.Sprintf(`{
			"threshold": 15,
			"%s": ["%s"]
		}`, patternType, patternValue)
		configPath := filepath.Join(setup.TmpDir, "dupl.json")
		err = os.WriteFile(configPath, []byte(configContent), 0o644)
		Expect(err).NotTo(HaveOccurred())

		code := fmt.Sprintf(`package main
func %s() {}`, funcName)
		err = setup.CreateFileWithContent(filepath.Join(dir1, "file.go"), code)
		Expect(err).NotTo(HaveOccurred())
		err = setup.CreateFileWithContent(filepath.Join(dir2, "file.go"), code)
		Expect(err).NotTo(HaveOccurred())

		output, err := setup.RunArtDupl("--config", configPath, setup.TmpDir)
		Expect(err).ToNot(HaveOccurred())
		Expect(output).ToNot(BeNil())
	}

	// runStatsConfigTest is a helper to run stats subcommand tests with config
	runStatsConfigTest := func(threshold int, fileNames []string) {
		configContent := fmt.Sprintf(`{
			"threshold": %d,
			"outputFormat": "json"
		}`, threshold)
		configPath := filepath.Join(setup.TmpDir, "dupl.json")
		err := os.WriteFile(configPath, []byte(configContent), 0o644)
		Expect(err).NotTo(HaveOccurred())

		err = setup.CreateDuplicateFiles(fileNames, statsConfigCode)
		Expect(err).NotTo(HaveOccurred())

		output, err := setup.RunSubcommand("stats", "--config", configPath)
		Expect(err).ToNot(HaveOccurred())
		Expect(output).ToNot(BeNil())
	}

	Context("When configuration file has pattern settings", func() {
		It("should load include patterns from config", func() {
			runPatternTest("src", "vendor", "includePatterns", "src/*", "patternTest")
		})

		It("should load exclude patterns from config", func() {
			runPatternTest("src", "test", "excludePatterns", "test/*", "excludeTest")
		})
	})

	Context("When using stats subcommand with config file", func() {
		It("should load stats configuration from file", func() {
			runStatsConfigTest(20, []string{"stats1.go", "stats2.go"})
		})
	})
})

var _ = Describe("Configuration File Edge Cases", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = newBDDTestSetup()
	})

	Context("When configuration file is empty", func() {
		It("should handle empty config file gracefully", func() {
			output, err := setup.RunWithConfigFile(
				"empty.json",
				"",
				emptyConfigCode,
				[]string{"empty1.go", "empty2.go"},
			)
			// May error or use defaults
			_ = err

			Expect(output).ToNot(BeNil())
		})

		It("should handle config with only whitespace", func() {
			output, err := setup.RunWithConfigFile(
				"whitespace.json",
				"   \n\t  ",
				whitespaceConfigCode,
				[]string{"ws1.go", "ws2.go"},
			)
			// May error or use defaults
			_ = err

			Expect(output).ToNot(BeNil())
		})
	})

	Context("When configuration file has extra fields", func() {
		It("should ignore unknown fields in config", func() {
			configContent := `{
				"threshold": 15,
				"unknownField": "should be ignored",
				"anotherUnknown": 12345
			}`
			output, err := setup.RunWithConfigFile(
				"dupl.json",
				configContent,
				unknownFieldCode,
				[]string{"unknown1.go", "unknown2.go"},
			)
			// Should work and ignore unknown fields
			_ = err

			Expect(output).ToNot(BeNil())
		})
	})

	Context("When using deeply nested config files", func() {
		It("should handle config in nested directory", func() {
			// Create nested directory structure
			nestedDir := filepath.Join(setup.TmpDir, "nested", "config")
			err := os.MkdirAll(nestedDir, 0o755)
			Expect(err).NotTo(HaveOccurred())

			// Create config in nested directory
			configContent := `{
				"threshold": 25
			}`
			configPath := filepath.Join(nestedDir, "dupl.json")
			err = os.WriteFile(configPath, []byte(configContent), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Create test files
			code := `package main
func nestedConfig() {}`
			err = setup.CreateDuplicateFiles([]string{"nested1.go", "nested2.go"}, code)
			Expect(err).NotTo(HaveOccurred())

			// Run with nested config path
			output, err := setup.RunArtDupl("--config", configPath, setup.TmpDir)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})
	})

	Context("When configuration has special characters", func() {
		It("should handle config with unicode content", func() {
			// Create config with unicode
			configContent := fmt.Sprintf(`{
				"threshold": 15,
				"paths": ["%s"]
			}`, setup.TmpDir)
			configPath := filepath.Join(setup.TmpDir, "unicode.json")
			err := os.WriteFile(configPath, []byte(configContent), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Create test files
			err = setup.CreateDuplicateFiles(
				[]string{"unicode1.go", "unicode2.go"},
				unicodeConfigCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with unicode config
			output, err := setup.RunArtDupl("--config", configPath)
			Expect(err).ToNot(HaveOccurred())
			Expect(output).ToNot(BeNil())
		})
	})
})
