package bdd

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
)

// BDD Test Suite for Default Filtering Behavior
//
// These tests verify that generated code is filtered by default in the main command,
// ensuring users don't see noise from auto-generated files.
//
// Generated code types covered:
// - Templ: *_templ.go files (templ.guide)
// - SQLC: *.sql.go, models.go, querier.go, batch.go files (sqlc.dev)

func TestDefaultFiltering(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "art-dupl Default Filtering BDD Suite")
}

// assertGeneratedFileFiltered is a helper to verify generated files are filtered out.
// It creates duplicate regular files, a generated file, runs art-dupl, and verifies
// that regular files appear in output while the generated file does not.
func assertGeneratedFileFiltered(
	setup *testutil.BDDTestSetup,
	regularFiles []string,
	regularCode string,
	generatedFile string,
	generatedCode string,
	threshold string,
) string {
	err := setup.CreateDuplicateFiles(regularFiles, regularCode)
	Expect(err).NotTo(HaveOccurred())
	err = setup.CreateTestFile(generatedFile, generatedCode)
	Expect(err).NotTo(HaveOccurred())

	output, err := setup.RunArtDupl("--threshold", threshold)
	Expect(err).ToNot(HaveOccurred())
	outputStr := string(output)

	// Should find duplicates in regular files
	for _, file := range regularFiles {
		Expect(outputStr).To(ContainSubstring(file))
	}
	// Should NOT include generated file
	Expect(outputStr).ToNot(ContainSubstring(generatedFile))

	return outputStr
}

var _ = Describe("Default Filtering Behavior", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		var err error
		setup, err = testutil.NewBDDTestSetupForGinkgo()
		Expect(err).NotTo(HaveOccurred())
	})

	AfterEach(func() {
		Expect(setup.Cleanup()).NotTo(HaveOccurred())
	})

	Context("When analyzing code with templ generated files", func() {
		It("should exclude *_templ.go files by default", func() {
			regularCode := `package main

import "fmt"

func process() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`
			templCode := `package main

import "github.com/a-h/templ"

func Page() templ.Component {
	return nil
}

func process() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

			assertGeneratedFileFiltered(
				setup,
				[]string{"handler1.go", "handler2.go"},
				regularCode,
				"page_templ.go",
				templCode,
				"5",
			)
		})

		It("should exclude multiple templ files by default", func() {
			regularCode := `package main
func common() { println(1) }`

			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func common() { println(1) }`

			err := setup.CreateTestFile("regular.go", regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("header_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("footer_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("layout_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should only show regular file
			Expect(outputStr).To(ContainSubstring("regular.go"))
			Expect(outputStr).ToNot(ContainSubstring("header_templ.go"))
			Expect(outputStr).ToNot(ContainSubstring("footer_templ.go"))
			Expect(outputStr).ToNot(ContainSubstring("layout_templ.go"))
		})

		It("should include templ files when --include-templ is used", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"regular1.go", "regular2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with --include-templ
			output, err := setup.RunArtDupl("--include-templ", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should now include templ file
			Expect(outputStr).To(ContainSubstring("page_templ.go"))
		})
	})

	Context("When analyzing code with SQLC generated files", func() {
		It("should exclude *.sql.go files by default", func() {
			regularCode := `package main

import "fmt"

func query() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

func query() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

			assertGeneratedFileFiltered(
				setup,
				[]string{"service1.go", "service2.go"},
				regularCode,
				"queries.sql.go",
				sqlcCode,
				"5",
			)
		})

		It("should exclude models.go files by default", func() {
			regularCode := `package main
func validate() { println(1) }`
			modelsCode := `package db
func validate() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"service1.go", "service2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("models.go", modelsCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			Expect(outputStr).To(ContainSubstring("service1.go"))
			Expect(outputStr).ToNot(ContainSubstring("models.go"))
		})

		It("should exclude querier.go files by default", func() {
			regularCode := `package main
func query() { println(1) }`
			querierCode := `package db
func query() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"service1.go", "service2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("querier.go", querierCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			Expect(outputStr).To(ContainSubstring("service1.go"))
			Expect(outputStr).ToNot(ContainSubstring("querier.go"))
		})

		It("should exclude batch.go files by default", func() {
			regularCode := `package main
func batch() { println(1) }`
			batchCode := `package db
func batch() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"service1.go", "service2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("batch.go", batchCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			Expect(outputStr).To(ContainSubstring("service1.go"))
			Expect(outputStr).ToNot(ContainSubstring("batch.go"))
		})

		It("should include SQLC files when --include-sqlc is used", func() {
			regularCode := `package main
func query() { println(1) }`
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db
func query() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"service1.go", "service2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("queries.sql.go", sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with --include-sqlc
			output, err := setup.RunArtDupl("--include-sqlc", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should now include sqlc file
			Expect(outputStr).To(ContainSubstring("queries.sql.go"))
		})
	})

	Context("When both templ and sqlc files are present", func() {
		It("should filter both by default", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db
func process() { println(1) }`

			err := setup.CreateTestFile("regular.go", regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("queries.sql.go", sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should only show regular file
			Expect(outputStr).To(ContainSubstring("regular.go"))
			Expect(outputStr).ToNot(ContainSubstring("page_templ.go"))
			Expect(outputStr).ToNot(ContainSubstring("queries.sql.go"))
		})

		It("should include both when both flags are used", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db
func process() { println(1) }`

			err := setup.CreateTestFile("regular.go", regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("queries.sql.go", sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with both include flags
			output, err := setup.RunArtDupl("--include-templ", "--include-sqlc", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should show all files
			Expect(outputStr).To(ContainSubstring("regular.go"))
			Expect(outputStr).To(ContainSubstring("page_templ.go"))
			Expect(outputStr).To(ContainSubstring("queries.sql.go"))
		})
	})

	Context("When vendor directory is present", func() {
		It("should exclude vendor directory by default", func() {
			regularCode := `package main
func vendorFunc() { println(1) }`

			err := setup.CreateVendorDuplicateFiles("vendor/github.com/example", regularCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunArtDupl("--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should not mention vendor files
			Expect(outputStr).ToNot(ContainSubstring("vendor"))
		})

		It("should include vendor when --vendor flag is used", func() {
			regularCode := `package main
func vendorFunc() { println(1) }`

			err := setup.CreateVendorDuplicateFiles("vendor/github.com/example", regularCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with --vendor flag
			output, err := setup.RunArtDupl("--vendor", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())
			outputStr := string(output)

			// Should now show vendor files
			Expect(outputStr).To(ContainSubstring("vendor"))
		})
	})
})

var _ = Describe("Filtering in Different Output Formats", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		var err error
		setup, err = testutil.NewBDDTestSetupForGinkgo()
		Expect(err).NotTo(HaveOccurred())
	})

	AfterEach(func() {
		Expect(setup.Cleanup()).NotTo(HaveOccurred())
	})

	Context("When using JSON output", func() {
		It("should not include templ files in JSON output by default", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"file1.go", "file2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with JSON output
			stdout, _, err := setup.RunArtDuplAndCapture("--json", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())

			// Should not contain templ file
			Expect(string(stdout)).ToNot(ContainSubstring("page_templ.go"))
		})
	})

	Context("When using HTML output", func() {
		It("should not include templ files in HTML output by default", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"file1.go", "file2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with HTML output
			output, err := setup.RunArtDupl("--html", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())

			// Should not contain templ file
			Expect(string(output)).ToNot(ContainSubstring("page_templ.go"))
		})
	})

	Context("When using plumbing output", func() {
		It("should not include templ files in plumbing output by default", func() {
			regularCode := `package main
func process() { println(1) }`
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }
func process() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{"file1.go", "file2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with plumbing output
			output, err := setup.RunArtDupl("--plumbing", "--threshold", "3")
			Expect(err).ToNot(HaveOccurred())

			// Should not contain templ file
			Expect(string(output)).ToNot(ContainSubstring("page_templ.go"))
		})
	})
})
