package bdd

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// buildFilterCmd creates an exec.CommandContext for running art-dupl with filter patterns.
func buildFilterCmd(
	binaryPath, tmpDir string,
	threshold int,
	includePatterns, excludePatterns []string,
) *exec.Cmd {
	args := make([]string, 0, 1+2*len(includePatterns)+2*len(excludePatterns)+2)

	args = append(args, tmpDir)
	for _, p := range includePatterns {
		args = append(args, "--include-pattern", p)
	}

	for _, p := range excludePatterns {
		args = append(args, "--exclude-pattern", p)
	}

	args = append(args, "--threshold", strconv.Itoa(threshold))

	return exec.CommandContext(context.Background(), binaryPath, args...)
}

// BDD Test Suite for Filter Features
//
// These tests verify the filtering capabilities of art-dupl,
// including generated code filtering and custom pattern inclusion/exclusion.
//
// The scenarios cover:
// - Filtering generated code (sqlc, templ)
// - Including specific patterns
// - Excluding specific patterns
// - Pattern precedence rules

var _ = Describe("Filter Features", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = CreateBDDTestSetup()
	})

	Context("When filtering generated code", func() {
		It("should exclude sqlc generated code by default", func() {
			// Create regular Go file with enough tokens for threshold
			regularCode := `package main

import "fmt"

func regularFunction() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
		fmt.Println(i * 2)
	}
}`

			// Create sqlc generated code with standard sqlc filename and content markers
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.10.0

package db

type User struct {
	ID   int
	Name string
}

func (u *User) Validate() bool {
	return u.ID > 0 && u.Name != ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"regular1.go", "regular2.go"},
				regularCode,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"models.go", "querier.go"},
				sqlcCode,
			)
			Expect(err).NotTo(HaveOccurred())

			cmd := exec.Command(
				setup.BinaryPath,
				setup.TmpDir,
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should find regular file duplicates
			Expect(outputStr).To(ContainSubstring("regular1.go"))
			// Should not include sqlc generated files
			Expect(outputStr).ToNot(ContainSubstring("models.go"))
		})

		It("should exclude templ generated code by default", func() {
			// Create regular Go file with enough tokens
			regularCode := `package main

import "fmt"

func handler() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
		fmt.Println(i * 2)
	}
}`

			// Create templ generated code (with _templ.go suffix and templ.Component import) with enough tokens
			templCode := `package components

import "github.com/a-h/templ"

func Header() templ.Component {
	return nil
}

func Footer() templ.Component {
	return nil
}

func Body() templ.Component {
	return nil
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"handler1.go", "handler2.go"},
				regularCode,
			)
			Expect(err).NotTo(HaveOccurred())
			// Use _templ.go suffix to match filter's filename detection
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"header_templ.go", "footer_templ.go"},
				templCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			cmd = exec.Command(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			Expect(outputStr).To(ContainSubstring("handler"))
			// templ files should be filtered by default
			Expect(outputStr).ToNot(ContainSubstring("templ"))
		})

		It("should include sqlc files when --include-sqlc is specified", func() {
			// Create sqlc generated code with enough tokens
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

type Query struct {
	Name string
}

func (q *Query) Execute() error {
	return nil
}

func (q *Query) Validate() bool {
	return q.Name != ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"sqlc1.go", "sqlc2.go"},
				sqlcCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with include-sqlc
			cmd = exec.Command(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				"--include-sqlc",
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include sqlc files
			Expect(outputStr).To(ContainSubstring("sqlc"))
		})

		It("should include templ files with --include-templ", func() {
			// Create templ generated code with enough tokens
			templCode := `// Code generated by templ. DO NOT EDIT.
package templ

func Component() string {
	return ""
}

func Button() string {
	return ""
}

func Link() string {
	return ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"templ1.go", "templ2.go"},
				templCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with --include-templ to include templ files
			cmd = exec.Command(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				"--include-templ",
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include templ files when --include-templ is used
			Expect(outputStr).To(ContainSubstring("templ"))
		})
	})

	Context("When using include patterns", func() {
		It("should analyze only files matching include patterns", func() {
			// Create different files with enough tokens
			includeCode := `package main

import "fmt"

func include() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			excludeCode := `package main

import "fmt"

func exclude() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/include1.go", "pkg1/include2.go"},
				includeCode,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/exclude1.go", "pkg2/exclude2.go"},
				excludeCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with include pattern for pkg1
			cmd = exec.Command(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				"--include-pattern",
				"pkg1/*",
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})

		It("should support multiple include patterns", func() {
			// Create files with enough tokens
			code1 := `package pkg1

import "fmt"

func one() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			code2 := `package pkg2

import "fmt"

func two() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/file1.go", "pkg1/file2.go"},
				code1,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/file3.go", "pkg2/file4.go"},
				code2,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with multiple include patterns
			cmd = buildFilterCmd(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				10,
				[]string{"pkg1/*", "pkg2/*"},
				nil,
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze both pkg1 and pkg2
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).To(ContainSubstring("pkg2"))
		})
	})

	Context("When using exclude patterns", func() {
		It("should exclude files matching exclude patterns", func() {
			// Create files with enough tokens
			code1 := `package pkg1

import "fmt"

func keep() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			code2 := `package pkg2

import "fmt"

func discard() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/keep1.go", "pkg1/keep2.go"},
				code1,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/discard1.go", "pkg2/discard2.go"},
				code2,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with exclude pattern for pkg2
			cmd = exec.Command(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				"--exclude-pattern",
				"pkg2/*",
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})
	})

	Context("When combining include and exclude patterns", func() {
		It("should give include patterns precedence over exclude patterns", func() {
			// Create files with enough tokens
			code := `package main

import "fmt"

func test() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"specific/file1.go", "specific/file2.go"},
				code,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"general/file1.go", "general/file2.go"},
				code,
			)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with both include and exclude - include should take precedence
			cmd = buildFilterCmd(
				"./art-dupl-filter_features-test",
				setup.TmpDir,
				10,
				[]string{"specific/*"},
				[]string{"*/file.go"},
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Include pattern should override exclude pattern
			Expect(outputStr).To(ContainSubstring("specific"))
		})
	})

	Context("When filtering vendor directory", func() {
		var (
			vendorDir   string
			vendorCode  string
			buildBinary string
		)

		BeforeEach(func() {
			vendorDir = filepath.Join(setup.TmpDir, "vendor")
			err := os.MkdirAll(vendorDir, 0o755)
			Expect(err).NotTo(HaveOccurred())

			vendorCode = `package vendor

import "fmt"

func vendorFunc() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err = os.WriteFile(filepath.Join(vendorDir, "vendor1.go"), []byte(vendorCode), 0o644)
			Expect(err).NotTo(HaveOccurred())
			err = os.WriteFile(filepath.Join(vendorDir, "vendor2.go"), []byte(vendorCode), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command(
				"go",
				"build",
				"-o",
				"./art-dupl-filter_features-test",
				"../cmd/art-dupl/main.go",
			)
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())
			buildBinary = "./art-dupl-filter_features-test"
		})

		It("should exclude vendor directory by default", func() {
			code := `package main

import "fmt"

func duplicate() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles([]string{"main1.go", "main2.go"}, code)
			Expect(err).NotTo(HaveOccurred())

			// Run without vendor flag (should exclude vendor)
			cmd := exec.Command(buildBinary, setup.TmpDir, "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze main files
			Expect(outputStr).To(ContainSubstring("main"))
			Expect(outputStr).ToNot(ContainSubstring("vendor"))
		})

		It("should include vendor directory when --vendor is specified", func() {
			// Run with vendor flag
			cmd := exec.Command(
				buildBinary,
				setup.TmpDir,
				"--vendor",
				"--threshold",
				"10",
			)
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze vendor files
			Expect(outputStr).To(ContainSubstring("vendor"))
		})
	})
})
