package bdd

import (
	"os"
	"path/filepath"
	"strconv"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// buildFilterArgs constructs arguments for running art-dupl with filter patterns.
func buildFilterArgs(
	tmpDir string,
	threshold int,
	includePatterns, excludePatterns []string,
) []string {
	args := make([]string, 0, 1+2*len(includePatterns)+2*len(excludePatterns)+2)

	args = append(args, tmpDir)
	for _, p := range includePatterns {
		args = append(args, "--include-pattern", p)
	}

	for _, p := range excludePatterns {
		args = append(args, "--exclude-pattern", p)
	}

	args = append(args, "--threshold", strconv.Itoa(threshold))

	return args
}

// BDD Test Suite for Filter Features
//
// These tests verify the filtering capabilities of art-dupl,
// including generated code filtering and custom pattern inclusion/exclusion.
//
// The scenarios cover:
// - Filtering generated code (sqlc, templ)
// - Including specific patterns
// - Excluding specific patterns
// - Pattern precedence rules

var _ = Describe("Filter Features", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = CreateBDDTestSetup()
	})

	Context("When filtering generated code", func() {
		It("should exclude sqlc generated code by default", func() {
			// Create regular Go file with enough tokens for threshold
			regularCode := `package main

import "fmt"

func regularFunction() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
		fmt.Println(i * 2)
	}
}`

			// Create sqlc generated code with standard sqlc filename and content markers
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.10.0

package db

type User struct {
	ID   int
	Name string
}

func (u *User) Validate() bool {
	return u.ID > 0 && u.Name != ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"regular1.go", regularFile2},
				regularCode,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"models.go", "querier.go"},
				sqlcCode,
			)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.Executor(setup.TmpDir, "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should find regular file duplicates
			Expect(outputStr).To(ContainSubstring("regular1.go"))
			// Should not include sqlc generated files
			Expect(outputStr).ToNot(ContainSubstring("models.go"))
		})

		It("should exclude templ generated code by default", func() {
			// Create regular Go file with enough tokens
			regularCode := `package main

import "fmt"

func handler() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
		fmt.Println(i * 2)
	}
}`

			// Create templ generated code (with _templ.go suffix and templ.Component import) with enough tokens
			templCode := `package components

import "github.com/a-h/templ"

func Header() templ.Component {
	return nil
}

func Footer() templ.Component {
	return nil
}

func Body() templ.Component {
	return nil
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"handler1.go", "handler2.go"},
				regularCode,
			)
			Expect(err).NotTo(HaveOccurred())
			// Use _templ.go suffix to match filter's filename detection
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"header_templ.go", "footer_templ.go"},
				templCode,
			)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.Executor(setup.TmpDir, "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			Expect(outputStr).To(ContainSubstring("handler"))
			// templ files should be filtered by default
			Expect(outputStr).ToNot(ContainSubstring("templ"))
		})

		It("should include sqlc files when --include-generated sqlc is specified", func() {
			// Create sqlc generated code with enough tokens
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

type Query struct {
	Name string
}

func (q *Query) Execute() error {
	return nil
}

func (q *Query) Validate() bool {
	return q.Name != ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"sqlc1.go", "sqlc2.go"},
				sqlcCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with --include-generated sqlc
			output, err := setup.Executor(setup.TmpDir, "--include-generated", "sqlc", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include sqlc files
			Expect(outputStr).To(ContainSubstring("sqlc"))
		})

		It("should include templ files with --include-generated templ", func() {
			// Create templ generated code with enough tokens
			templCode := `// Code generated by templ. DO NOT EDIT.
package templ

func Component() string {
	return ""
}

func Button() string {
	return ""
}

func Link() string {
	return ""
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"templ1.go", "templ2.go"},
				templCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with --include-generated templ to include templ files
			output, err := setup.Executor(setup.TmpDir, "--include-generated", "templ", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include templ files when --include-generated templ is used
			Expect(outputStr).To(ContainSubstring("templ"))
		})
	})

	Context("When using include patterns", func() {
		It("should analyze only files matching include patterns", func() {
			// Create different files with enough tokens
			includeCode := `package main

import "fmt"

func include() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			excludeCode := `package main

import "fmt"

func exclude() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/include1.go", "pkg1/include2.go"},
				includeCode,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/exclude1.go", "pkg2/exclude2.go"},
				excludeCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with include pattern for pkg1
			output, err := setup.Executor(
				setup.TmpDir,
				"--include-pattern",
				"pkg1/*",
				"--threshold", "1",
			)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})

		It("should support multiple include patterns", func() {
			// Create files with enough tokens
			code1 := `package pkg1

import "fmt"

func one() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			code2 := `package pkg2

import "fmt"

func two() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/file1.go", "pkg1/file2.go"},
				code1,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/file3.go", "pkg2/file4.go"},
				code2,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with multiple include patterns
			args := buildFilterArgs(setup.TmpDir, 1, []string{"pkg1/*", "pkg2/*"}, nil)
			output, err := setup.Executor(args...)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze both pkg1 and pkg2
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).To(ContainSubstring("pkg2"))
		})
	})

	Context("When using exclude patterns", func() {
		It("should exclude files matching exclude patterns", func() {
			// Create files with enough tokens
			code1 := `package pkg1

import "fmt"

func keep() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			code2 := `package pkg2

import "fmt"

func discard() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg1/keep1.go", "pkg1/keep2.go"},
				code1,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"pkg2/discard1.go", "pkg2/discard2.go"},
				code2,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with exclude pattern for pkg2
			output, err := setup.Executor(
				setup.TmpDir,
				"--exclude-pattern",
				"pkg2/*",
				"--threshold", "1",
			)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})
	})

	Context("When combining include and exclude patterns", func() {
		It("should give include patterns precedence over exclude patterns", func() {
			// Create files with enough tokens
			code := `package main

import "fmt"

func test() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"specific/file1.go", "specific/file2.go"},
				code,
			)
			Expect(err).NotTo(HaveOccurred())
			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"general/file1.go", "general/file2.go"},
				code,
			)
			Expect(err).NotTo(HaveOccurred())

			// Run with both include and exclude - include should take precedence
			args := buildFilterArgs(setup.TmpDir, 1, []string{"specific/*"}, []string{"*/file.go"})
			output, err := setup.Executor(args...)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Include pattern should override exclude pattern
			Expect(outputStr).To(ContainSubstring("specific"))
		})
	})

	Context("When filtering vendor directory", func() {
		var (
			vendorDir    string
			excludedCode string
		)

		BeforeEach(func() {
			vendorDir = filepath.Join(setup.TmpDir, "vendor")
			err := os.MkdirAll(vendorDir, 0o755)
			Expect(err).NotTo(HaveOccurred())

			excludedCode = `package vendor

import "fmt"

func vendorFunc() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			for _, name := range []string{"vendor1.go", "vendor2.go"} {
				err = os.WriteFile(filepath.Join(vendorDir, name), []byte(excludedCode), 0o644)
				Expect(err).NotTo(HaveOccurred())
			}
		})

		It("should exclude vendor directory by default", func() {
			code := `package main

import "fmt"

func duplicate() {
	for i := 0; i < 5; i++ {
		fmt.Println(i)
	}
}`

			err := setup.FileProcessor.WriteDuplicateFiles([]string{"main1.go", "main2.go"}, code)
			Expect(err).NotTo(HaveOccurred())

			// Run without vendor flag (should exclude vendor)
			output, err := setup.Executor(setup.TmpDir, "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze main files
			Expect(outputStr).To(ContainSubstring("main"))
			Expect(outputStr).ToNot(ContainSubstring("vendor"))
		})

		It("should include vendor directory when --vendor is specified", func() {
			// Run with vendor flag
			output, err := setup.Executor(setup.TmpDir, "--vendor", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze vendor files
			Expect(outputStr).To(ContainSubstring("vendor"))
		})
	})

	Context("When using --include-generated generic with defense-in-depth", func() {
		It("should exclude non-suffix templ files via content check", func() {
			// Code with 7+ separate top-level statements to exceed threshold 5.
			dupCode := `package main

func parseHeader(data []byte) (int, int, int) {
	header := data[:4]
	version := int(header[0])
	flags := int(header[1])
	length := int(header[2])<<8 | int(header[3])
	body := data[4 : 4+length]
	tail := data[4+length:]
	return version, flags, len(tail)
}`

			// Same code but prefixed with a templ generation marker.
			// File has NO _templ.go suffix — defense-in-depth must catch it.
			templNoSuffixCode := `// Code generated by templ - DO NOT EDIT.

` + dupCode

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"regular1.go", "regular2.go"},
				dupCode,
			)
			Expect(err).NotTo(HaveOccurred())

			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"gen_template.go"},
				templNoSuffixCode,
			)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.Executor(setup.TmpDir, "--include-generated", "generic", "--threshold", "5")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Regular duplicates should still be detected.
			Expect(outputStr).To(ContainSubstring("regular1.go"))

			// Non-suffix templ file must be excluded by defense-in-depth content check.
			Expect(outputStr).ToNot(ContainSubstring("gen_template.go"))
		})

		It("should include non-suffix templ files when templ category is included", func() {
			dupCode := `package main

func parseHeader(data []byte) (int, int, int) {
	header := data[:4]
	version := int(header[0])
	flags := int(header[1])
	length := int(header[2])<<8 | int(header[3])
	body := data[4 : 4+length]
	tail := data[4+length:]
	return version, flags, len(tail)
}`

			templNoSuffixCode := `// Code generated by templ - DO NOT EDIT.

` + dupCode

			err := setup.FileProcessor.WriteDuplicateFiles(
				[]string{"regular3.go", "regular4.go"},
				dupCode,
			)
			Expect(err).NotTo(HaveOccurred())

			err = setup.FileProcessor.WriteDuplicateFiles(
				[]string{"gen_template2.go"},
				templNoSuffixCode,
			)
			Expect(err).NotTo(HaveOccurred())

			// Both generic AND templ included — defense-in-depth allows templ content.
			output, err := setup.Executor(setup.TmpDir, "--include-generated", "generic,templ", "--threshold", "5")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Regular duplicates detected.
			Expect(outputStr).To(ContainSubstring("regular3.go"))
			// Templ file now included since templ category is explicitly included.
			Expect(outputStr).To(ContainSubstring("gen_template2.go"))
		})
	})
})