package bdd

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/LarsArtmann/art-dupl/internal/utils"
)

// BDD Test Suite for Filter Features
//
// These tests verify the filtering capabilities of art-dupl,
// including generated code filtering and custom pattern inclusion/exclusion.
//
// The scenarios cover:
// - Filtering generated code (sqlc, templ)
// - Including specific patterns
// - Excluding specific patterns
// - Pattern precedence rules

func TestFilterFeatures(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "art-dupl Filter Features BDD Suite")
}

var _ = Describe("Filter Features", func() {
	var (
		tempDir       string
		fileProcessor *utils.FileProcessor
	)

	BeforeEach(func() {
		var err error
		tempDir, err = os.MkdirTemp("", "art-dupl-filter-bdd-*")
		Expect(err).NotTo(HaveOccurred())

		fileProcessor = utils.NewFileProcessor(tempDir)
	})

	AfterEach(func() {
		_ = os.RemoveAll(tempDir)
		_ = os.Remove("./art-dupl-filter_features-test")
	})

	Context("When filtering generated code", func() {
		It("should exclude sqlc generated code by default with --filter-generated", func() {
			// Create regular Go file
			regularCode := `package main

func regularFunction() error {
	return nil
}`

			// Create sqlc generated code (typical pattern)
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.10.0

package db

type User struct {
	ID   int
	Name string
}`

			err := fileProcessor.WriteDuplicateFiles([]string{"regular1.go", "regular2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"sqlc_models.go", "sqlc_other.go"}, sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with filter-generated flag
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--filter-generated", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should find regular file duplicates
			Expect(outputStr).To(ContainSubstring("regular1.go"))
			// Should not include sqlc generated files
			Expect(outputStr).ToNot(ContainSubstring("sqlc"))
		})

		It("should exclude templ generated code by default", func() {
			// Create regular Go file
			regularCode := `package main

func handler() error {
	return nil
}`

			// Create templ generated code (typical pattern)
			templCode := `// Code generated by templ. DO NOT EDIT.
// version: v0.1.0

package templ

func Render() string {
	return "rendered"
}`

			err := fileProcessor.WriteDuplicateFiles([]string{"handler1.go", "handler2.go"}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"templ_handler.go", "templ_view.go"}, templCode)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run default (templ should be filtered)
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			Expect(outputStr).To(ContainSubstring("handler"))
			// templ files should be filtered by default
			Expect(outputStr).ToNot(ContainSubstring("templ"))
		})

		It("should include sqlc files when --include-sqlc is specified", func() {
			// Create sqlc generated code
			sqlcCode := `// Code generated by sqlc. DO NOT EDIT.
package db

type Query struct {
	Name string
}`

			err := fileProcessor.WriteDuplicateFiles([]string{"sqlc1.go", "sqlc2.go"}, sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with filter-generated but include-sqlc
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--filter-generated", "--include-sqlc", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include sqlc files
			Expect(outputStr).To(ContainSubstring("sqlc"))
		})

		It("should include templ files when --include-templ is specified", func() {
			// Create templ generated code
			templCode := `// Code generated by templ. DO NOT EDIT.
package templ

func Component() string {
	return ""
}`

			err := fileProcessor.WriteDuplicateFiles([]string{"templ1.go", "templ2.go"}, templCode)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with include-templ
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--include-templ", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should include templ files
			Expect(outputStr).To(ContainSubstring("templ"))
		})
	})

	Context("When using include patterns", func() {
		It("should analyze only files matching include patterns", func() {
			// Create different files
			includeCode := `package main

func include() string {
	return "include me"
}`

			excludeCode := `package main

func exclude() string {
	return "exclude me"
}`

			err := fileProcessor.WriteDuplicateFiles([]string{"pkg1/include1.go", "pkg1/include2.go"}, includeCode)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"pkg2/exclude1.go", "pkg2/exclude2.go"}, excludeCode)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with include pattern for pkg1
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--include-pattern", "pkg1/*", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})

		It("should support multiple include patterns", func() {
			// Create files
			code1 := `package pkg1

func one() {}`

			code2 := `package pkg2

func two() {}`

			err := fileProcessor.WriteDuplicateFiles([]string{"pkg1/file1.go", "pkg1/file2.go"}, code1)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"pkg2/file3.go", "pkg2/file4.go"}, code2)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with multiple include patterns
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--include-pattern", "pkg1/*", "--include-pattern", "pkg2/*", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze both pkg1 and pkg2
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).To(ContainSubstring("pkg2"))
		})
	})

	Context("When using exclude patterns", func() {
		It("should exclude files matching exclude patterns", func() {
			// Create files
			code1 := `package pkg1

func keep() {}`

			code2 := `package pkg2

func discard() {}`

			err := fileProcessor.WriteDuplicateFiles([]string{"pkg1/keep1.go", "pkg1/keep2.go"}, code1)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"pkg2/discard1.go", "pkg2/discard2.go"}, code2)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with exclude pattern for pkg2
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--exclude-pattern", "pkg2/*", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze pkg1 files
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).ToNot(ContainSubstring("pkg2"))
		})
	})

	Context("When combining include and exclude patterns", func() {
		It("should give include patterns precedence over exclude patterns", func() {
			// Create files
			code := `package main

func test() {}`

			err := fileProcessor.WriteTextFile("specific/file.go", code)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteTextFile("general/file.go", code)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with both include and exclude - include should take precedence
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--include-pattern", "specific/*", "--exclude-pattern", "*/file.go", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Include pattern should override exclude pattern
			Expect(outputStr).To(ContainSubstring("specific"))
		})
	})

	Context("When filtering vendor directory", func() {
		It("should exclude vendor directory by default", func() {
			// Create vendor directory
			vendorDir := filepath.Join(tempDir, "vendor")
			err := os.MkdirAll(vendorDir, 0o755)
			Expect(err).NotTo(HaveOccurred())

			// Create files in vendor and main
			code := `package main

func duplicate() {}`

			err = os.WriteFile(filepath.Join(vendorDir, "vendor1.go"), []byte(code), 0o644)
			Expect(err).NotTo(HaveOccurred())
			err = os.WriteFile(filepath.Join(vendorDir, "vendor2.go"), []byte(code), 0o644)
			Expect(err).NotTo(HaveOccurred())
			err = fileProcessor.WriteDuplicateFiles([]string{"main1.go", "main2.go"}, code)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run without vendor flag (should exclude vendor)
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should only analyze main files
			Expect(outputStr).To(ContainSubstring("main"))
			Expect(outputStr).ToNot(ContainSubstring("vendor"))
		})

		It("should include vendor directory when --vendor is specified", func() {
			// Create vendor directory
			vendorDir := filepath.Join(tempDir, "vendor")
			err := os.MkdirAll(vendorDir, 0o755)
			Expect(err).NotTo(HaveOccurred())

			// Create files in vendor
			vendorCode := `package vendor

func vendorFunc() {}`

			err = os.WriteFile(filepath.Join(vendorDir, "vendor1.go"), []byte(vendorCode), 0o644)
			Expect(err).NotTo(HaveOccurred())
			err = os.WriteFile(filepath.Join(vendorDir, "vendor2.go"), []byte(vendorCode), 0o644)
			Expect(err).NotTo(HaveOccurred())

			// Build art-dupl binary
			cmd := exec.Command("go", "build", "-o", "./art-dupl-filter_features-test", "../cmd/art-dupl/main.go")
			err = cmd.Run()
			Expect(err).NotTo(HaveOccurred())

			// Run with vendor flag
			cmd = exec.Command("./art-dupl-filter_features-test", tempDir, "--vendor", "--threshold", "10")
			output, err := cmd.CombinedOutput()
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Should analyze vendor files
			Expect(outputStr).To(ContainSubstring("vendor"))
		})
	})
})
