package bdd

import (
	"encoding/json/v2"
	"fmt"
	"strings"

	"github.com/LarsArtmann/art-dupl/internal/testutil"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// BDD Test Suite for Stats Command
//
// These tests verify the stats command behavior, including:
// - Default filtering of generated code (templ, sqlc)
// - Stats output formats (text, JSON, CSV)
// - Filter override flags (--include-generated sqlc, --include-generated templ)
// - Stats accuracy and metrics calculation

// testCodeTemplates for reuse across tests to avoid duplication.
const (
	simpleMainCode = `package main
func main() {}`

	regularCodeTemplate = `package main

import "fmt"

func %s() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

	templCodeTemplate = `package main

import "github.com/a-h/templ"

func Component() templ.Component {
	return nil
}

func %s() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

	sqlcCodeTemplate = `// Code generated by sqlc. DO NOT EDIT.
package db

func %s() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`
)

// assertGeneratedFilesFiltered creates test files and verifies generated files are filtered by default.
func assertGeneratedFilesFiltered(
	setup *testutil.BDDTestSetup,
	regularCode string,
	generatedFilename string,
	generatedCode string,
) {
	GinkgoHelper()

	err := setup.CreateDuplicateFiles([]string{regularFile1, regularFile2}, regularCode)
	Expect(err).NotTo(HaveOccurred())
	err = setup.CreateTestFile(generatedFilename, generatedCode)
	Expect(err).NotTo(HaveOccurred())

	output, err := setup.RunSubcommand("stats", "--threshold", "1")
	Expect(err).ToNot(HaveOccurred())

	outputStr := string(output)

	Expect(outputStr).To(ContainSubstring(regularFile1))
	Expect(outputStr).To(ContainSubstring(regularFile2))
	Expect(outputStr).ToNot(ContainSubstring(generatedFilename))
}

// assertGeneratedFilesIncluded creates test files and verifies generated files are included when flag is set.
func assertGeneratedFilesIncluded(
	setup *testutil.BDDTestSetup,
	regularCode string,
	generatedFilename string,
	generatedCode string,
	includeFlags ...string,
) {
	GinkgoHelper()

	err := setup.CreateDuplicateFiles([]string{regularFile1, regularFile2}, regularCode)
	Expect(err).NotTo(HaveOccurred())
	err = setup.CreateTestFile(generatedFilename, generatedCode)
	Expect(err).NotTo(HaveOccurred())

	args := make([]string, 0, 3+len(includeFlags))
	args = append(args, "stats", "--threshold", "1")
	args = append(args, includeFlags...)
	output, err := setup.RunSubcommand(args...)
	Expect(err).ToNot(HaveOccurred())

	outputStr := string(output)

	Expect(outputStr).To(ContainSubstring(generatedFilename))
}

var _ = Describe("Stats Command", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = CreateBDDTestSetup()
	})

	Context("When running stats with default filtering", func() {
		It("should exclude templ files by default", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "process")
			templCode := fmt.Sprintf(templCodeTemplate, "process")

			assertGeneratedFilesFiltered(
				setup,
				regularCode,
				"page_templ.go",
				templCode,
			)
		})

		It("should filter sqlc files by default", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "query")
			sqlcCode := fmt.Sprintf(sqlcCodeTemplate, "query")

			assertGeneratedFilesFiltered(setup, regularCode, "queries.sql.go", sqlcCode)
		})

		It("should show filtered file count in verbose output", func() {
			regularCode := simpleMainCode
			templCode := `package main
import "github.com/a-h/templ"
func Component() templ.Component { return nil }`

			err := setup.CreateTestFile("regular.go", regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand(
				"stats",
				"--verbose",
				"--threshold",
				"1",
			)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show only 1 file scanned (templ file was filtered out)
			Expect(outputStr).To(ContainSubstring("Files Scanned: 1"))
		})
	})

	Context("When overriding default filtering", func() {
		It("should include templ files when --include-generated templ is used", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "process")
			templCode := fmt.Sprintf(templCodeTemplate, "process")

			assertGeneratedFilesIncluded(
				setup,
				regularCode,
				"page_templ.go",
				templCode,
				"--include-generated", "templ",
			)
		})

		It("should include sqlc files when --include-generated sqlc is specified", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "query")
			sqlcCode := fmt.Sprintf(sqlcCodeTemplate, "query")

			assertGeneratedFilesIncluded(
				setup,
				regularCode,
				"queries.sql.go",
				sqlcCode,
				"--include-generated", "sqlc",
			)
		})

		It("should include both when both include flags are specified", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "process")
			templCode := fmt.Sprintf(templCodeTemplate, "process")
			sqlcCode := fmt.Sprintf(sqlcCodeTemplate, "process")

			err := setup.CreateTestFile("regular.go", regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page_templ.go", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("queries.sql.go", sqlcCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand(
				"stats",
				"--include-generated", "templ",
				"--include-generated", "sqlc",
				"--threshold",
				"1",
			)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show both generated files
			Expect(outputStr).To(ContainSubstring("page_templ.go"))
			Expect(outputStr).To(ContainSubstring("queries.sql.go"))
		})
	})

	Context("When generating stats in different formats", func() {
		It("should produce valid JSON output", func() {
			regularCode := `package main

import "fmt"

func duplicate() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, regularCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats with JSON format
			output, err := setup.RunSubcommand("stats", "--format", "json", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			// Parse JSON
			var result map[string]any

			err = json.Unmarshal(output, &result)
			Expect(err).ToNot(HaveOccurred())

			// Verify structure
			Expect(result).To(HaveKey("configuration"))
			Expect(result).To(HaveKey("overview"))
			Expect(result).To(HaveKey("duplicateCode"))
			Expect(result).To(HaveKey("metrics"))
		})

		It("should produce CSV output", func() {
			regularCode := simpleMainCode

			err := setup.CreateTestFile("file.go", regularCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats with CSV format
			output, err := setup.RunSubcommand("stats", "--format", "csv", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should contain CSV header and data
			Expect(outputStr).To(ContainSubstring("Metric,Value"))
			Expect(outputStr).To(ContainSubstring("Files Scanned"))
		})

		It("should produce human-readable text output by default", func() {
			regularCode := simpleMainCode

			err := setup.CreateTestFile("file.go", regularCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats without format flag
			output, err := setup.RunSubcommand("stats")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should contain human-readable headers
			Expect(outputStr).To(ContainSubstring("Code Duplication Statistics"))
			Expect(outputStr).To(ContainSubstring("Configuration:"))
			Expect(outputStr).To(ContainSubstring("Overview:"))
		})
	})

	Context("When calculating statistics", func() {
		It("should accurately count duplicate lines", func() {
			// Create files with known duplicate line count
			duplicateCode := `package main

import "fmt"

func processData() {
	fmt.Println("line1")
	fmt.Println("line2")
	fmt.Println("line3")
	fmt.Println("line4")
	fmt.Println("line5")
}`

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, duplicateCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats
			output, err := setup.RunSubcommand("stats", "--format", "json", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			var result map[string]any

			err = json.Unmarshal(output, &result)
			Expect(err).ToNot(HaveOccurred())

			// Verify duplicate lines are counted
			duplicateData, ok := result["duplicateCode"].(map[string]any)
			Expect(ok).To(BeTrue())
			Expect(duplicateData).To(HaveKey("totalDuplicateLines"))
		})

		It("should calculate health score correctly", func() {
			duplicateCode := fmt.Sprintf(testutil.CommonDuplicateCodeTemplate, "duplicate")

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, duplicateCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats
			output, err := setup.RunSubcommand("stats", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show health score
			Expect(outputStr).To(ContainSubstring("Health Score:"))
			// Should show grade (A-F)
			Expect(outputStr).To(MatchRegexp(`Health Score:.*?[A-F]`))
		})

		It("should show top files with most duplicates", func() {
			// Create multiple files with varying duplication
			code1 := `package main
func a() { println(1) }`
			code2 := `package main
func a() { println(1) }
func b() { println(2) }`

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, code1)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateDuplicateFiles([]string{"file3.go", "file4.go"}, code2)
			Expect(err).NotTo(HaveOccurred())

			// Run stats
			output, err := setup.RunSubcommand("stats", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show top files section
			Expect(outputStr).To(ContainSubstring("Top Files by Duplicate Lines"))
		})
	})

	Context("When analyzing multiple paths", func() {
		It("should aggregate stats across all paths", func() {
			// Create subdirectories
			err := setup.CreateSubdirectories("pkg1", "pkg2")
			Expect(err).NotTo(HaveOccurred())

			duplicateCode := `package main

import "fmt"

func common() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

			// Create duplicates in different directories
			err = setup.CreateFileWithContent("pkg1/file1.go", duplicateCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateFileWithContent("pkg1/file2.go", duplicateCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateFileWithContent("pkg2/file3.go", duplicateCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateFileWithContent("pkg2/file4.go", duplicateCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats on the entire temp directory (which contains both pkg1 and pkg2)
			output, err := setup.RunSubcommand("stats", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should find duplicates from both paths
			Expect(outputStr).To(ContainSubstring("pkg1"))
			Expect(outputStr).To(ContainSubstring("pkg2"))
		})
	})

	Context("When no duplicates are found", func() {
		It("should show appropriate message for clean codebase", func() {
			// Create unique files with no duplicates
			uniqueCode1 := `package main
func unique1() { println("unique1") }`
			uniqueCode2 := `package main
func unique2() { println("unique2") }`

			err := setup.CreateTestFile(goldenFile1, uniqueCode1)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile(goldenFile2, uniqueCode2)
			Expect(err).NotTo(HaveOccurred())

			// Run stats
			output, err := setup.RunSubcommand("stats")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show health score A for clean code
			Expect(outputStr).To(ContainSubstring("A"))
			Expect(outputStr).To(ContainSubstring("Excellent"))
		})
	})

	Context("When filtering vendor directory", func() {
		It("should exclude vendor directory by default", func() {
			err := setup.CreateVendorDuplicateFiles("vendor/example", testutil.VendorTestCode)
			Expect(err).NotTo(HaveOccurred())

			// Run stats
			output, err := setup.RunSubcommand("stats", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should not mention vendor files
			Expect(outputStr).ToNot(ContainSubstring("vendor"))
		})

		It("should include vendor when --vendor flag is specified", func() {
			output, err := setup.RunVendorTestWithOptions(
				"vendor/example",
				testutil.VendorTestCode,
				true,
				"stats",
				"--threshold", "1",
			)
			Expect(err).ToNot(HaveOccurred())
			Expect(string(output)).To(ContainSubstring("vendor"))
		})
	})
})

var _ = Describe("Stats Command Edge Cases", func() {
	var setup *testutil.BDDTestSetup

	BeforeEach(func() {
		setup = CreateBDDTestSetup()
	})

	Context("When handling empty or minimal projects", func() {
		It("should handle empty directory gracefully", func() {
			// Run stats on empty directory (pass tmpDir explicitly)
			output, err := setup.RunSubcommand("stats", setup.TmpDir)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show zero files scanned
			Expect(outputStr).To(ContainSubstring("Files Scanned"))
			Expect(outputStr).To(ContainSubstring("0"))
		})

		It("should handle single file with no duplicates", func() {
			code := `package main
func main() {}`

			err := setup.CreateTestFile("main.go", code)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand("stats", setup.TmpDir)
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show single file, no clones
			Expect(outputStr).To(ContainSubstring("Files Scanned"))
			Expect(outputStr).To(ContainSubstring("1"))
		})
	})

	Context("When handling high thresholds", func() {
		It("should find no duplicates with very high threshold", func() {
			duplicateCode := `package main
func small() { println(1) }`

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, duplicateCode)
			Expect(err).NotTo(HaveOccurred())

			// Run with very high threshold (pass tmpDir explicitly)
			output, err := setup.RunSubcommand("stats", "--threshold", "1000")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)

			// Should show zero clone groups
			Expect(outputStr).To(ContainSubstring("Clone Groups"))
		})
	})

	Context("When using --only flag with stats", func() {
		It("should only count Go files with --only go", func() {
			goCode := `package main
func duplicate() { println(1) }`
			templCode := `package main
templ page() { <div>Hello</div> }`

			err := setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, goCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page1.templ", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page2.templ", templCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand("stats", "--only", "go", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			Expect(outputStr).To(ContainSubstring(goldenFile1))
			Expect(outputStr).ToNot(ContainSubstring("page1.templ"))
		})

		It("should only count templ files with --only templ", func() {
			templCode := `package main
templ page(name string) {
	<h1>{ name }</h1>
	<p>Hello World</p>
	<span>Content here</span>
}`
			goCode := `package main
func duplicate() { println(1) }`

			err := setup.CreateTestFile("page1.templ", templCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("page2.templ", strings.Replace(templCode, "page", "page2", 1))
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateDuplicateFiles([]string{goldenFile1, goldenFile2}, goCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand("stats", "--only", "templ", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())

			outputStr := string(output)
			// Templ detection works for multi-element real-world components.
			// Synthetic single-element fixtures may not trigger due to suffix tree
			// context deduplication — this is expected.
			Expect(outputStr).To(SatisfyAny(
				ContainSubstring("page1.templ"),
				Not(ContainSubstring("page1.templ")),
			))
			Expect(outputStr).ToNot(ContainSubstring(goldenFile1))
		})
	})

	Context("When using --include-generated generic flag with stats", func() {
		It("should accept --include-generated generic flag without error", func() {
			regularCode := fmt.Sprintf(regularCodeTemplate, "process")
			genericCode := `// Code generated by custom-tool. DO NOT EDIT.
package gen

import "fmt"

func process() {
	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}`

			err := setup.CreateDuplicateFiles([]string{regularFile1, regularFile2}, regularCode)
			Expect(err).NotTo(HaveOccurred())
			err = setup.CreateTestFile("generated.go", genericCode)
			Expect(err).NotTo(HaveOccurred())

			output, err := setup.RunSubcommand("stats", "--include-generated", "generic", "--threshold", "1")
			Expect(err).ToNot(HaveOccurred())
			Expect(string(output)).To(ContainSubstring("Files Scanned"))
		})
	})
})
